PACKAGE_NAME=fr.husi
VERSION_NAME=1.0.0-beta
VERSION_CODE=440

HYSTERIA2_VERSION_NAME=2.7.1-1
HYSTERIA2_VERSION=18

JUICITY_VERSION_NAME=0.5.0-0
JUICITY_VERSION=3

NAIVE_VERSION_NAME=127.0.6533.64-3
NAIVE_VERSION=5

MIERU_VERSION_NAME=3.28.0-1
MIERU_VERSION=35

SHADOWQUIC_VERSION_NAME=0.3.3-1
SHADOWQUIC_VERSION=15
