PACKAGE_NAME=fr.husi
VERSION_NAME=1.2.2
VERSION_CODE=475

HYSTERIA2_VERSION_NAME=2.9.2-0
HYSTERIA2_VERSION=22

JUICITY_VERSION_NAME=rust-0.1.0.alpha.5-0
JUICITY_VERSION=101

NAIVE_VERSION_NAME=127.0.6533.64-3
NAIVE_VERSION=5

MIERU_VERSION_NAME=3.32.0-0
MIERU_VERSION=40

SHADOWQUIC_VERSION_NAME=0.3.6-0
SHADOWQUIC_VERSION=18
