PACKAGE_NAME=fr.husi
VERSION_NAME=1.2.3
VERSION_CODE=476

HYSTERIA2_VERSION_NAME=2.9.2-0
HYSTERIA2_VERSION=22

JUICITY_VERSION_NAME=0.5.0-0
JUICITY_VERSION=3

NAIVE_VERSION_NAME=127.0.6533.64-3
NAIVE_VERSION=5

MIERU_VERSION_NAME=3.34.0-0
MIERU_VERSION=42

SHADOWQUIC_VERSION_NAME=0.3.11-0
SHADOWQUIC_VERSION=22
