#!/bin/bash

EXEC=""
TARGET="buildScript"
declare -a PARAMS
declare -i INDEX=0

for e in "$@"; do
  TARGET="$TARGET/$e"
  PARAMS[$INDEX]="$e"
  ((INDEX += 1))
  shift
  if [ -x "${TARGET}.sh" ]; then
    EXEC="${TARGET}.sh"
    PARAMS=()
    INDEX=0
  fi
done

echo ">> $EXEC"
exec "$EXEC" "${PARAMS[@]}"
