name: 错误反馈
description: "提交 虎兕 漏洞"
body:
  - type: textarea
    attributes:
      label: 版本
      description: 您可以在 “关于” 页面找到它。
      render: shell
  - type: textarea
    attributes:
      label: 描述
      description: 请提供错误的详细描述。
    validations:
      required: true
  - type: textarea
    attributes:
      label: 重现方式
      description: 请提供重现错误的步骤。
    validations:
      required: true
  - type: textarea
    attributes:
      label: 日志
      description: |-
        如果您可以进入 “日志” 界面，请在该界面选择分享日志。
        如果崩溃导致您无法进入软件，请检查 `/sdcard/Android/data/fr.husi/stderr.log` 文件以导出崩溃日志。
      render: shell
  - type: checkboxes
    attributes:
      label: 完整性要求
      description: |-
        请勾选以下所有选项以证明您已经阅读并理解了以下要求，否则该 issue 将被关闭。
        虎兕 不是讨好无法作出任何意义上的贡献的最终用户并获取非道德影响力的项目，也不是为 “机场” 黑产服务的客户端，更不是广告引流工具。如果您在此处欺骗以故意浪费开发者的时间，您将被永久封锁。
      options:
        - label: 我确定我的问题是 虎兕 本身的问题而不是我自身网络环境或服务器的问题。
          required: true
        - label: 我保证提供了可以在本地重现该问题的配置文件与流程。
          required: true
        - label: 我保证提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。
          required: true
