package io.nekohasekai.sagernet.compose.theme

import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color

/** 雨浥轻尘 */
object Blue {
    val primaryLight = Color(0xFF0061A4)
    val onPrimaryLight = Color(0xFFFFFFFF)
    val primaryContainerLight = Color(0xFF2196F3)
    val onPrimaryContainerLight = Color(0xFF002C4F)
    val secondaryLight = Color(0xFF0058BD)
    val onSecondaryLight = Color(0xFFFFFFFF)
    val secondaryContainerLight = Color(0xFF1E70E4)
    val onSecondaryContainerLight = Color(0xFFFEFCFF)
    val tertiaryLight = Color(0xFF006493)
    val onTertiaryLight = Color(0xFFFFFFFF)
    val tertiaryContainerLight = Color(0xFF03A9F4)
    val onTertiaryContainerLight = Color(0xFF003A58)
    val errorLight = Color(0xFFBA1A1A)
    val onErrorLight = Color(0xFFFFFFFF)
    val errorContainerLight = Color(0xFFFFDAD6)
    val onErrorContainerLight = Color(0xFF93000A)
    val backgroundLight = Color(0xFFF8F9FF)
    val onBackgroundLight = Color(0xFF181C22)
    val surfaceLight = Color(0xFFF8F9FF)
    val onSurfaceLight = Color(0xFF181C22)
    val surfaceVariantLight = Color(0xFFDBE3F0)
    val onSurfaceVariantLight = Color(0xFF404752)
    val outlineLight = Color(0xFF707883)
    val outlineVariantLight = Color(0xFFBFC7D4)
    val scrimLight = Color(0xFF000000)
    val inverseSurfaceLight = Color(0xFF2D3137)
    val inverseOnSurfaceLight = Color(0xFFEEF1F9)
    val inversePrimaryLight = Color(0xFF9ECAFF)
    val surfaceDimLight = Color(0xFFD7DAE2)
    val surfaceBrightLight = Color(0xFFF8F9FF)
    val surfaceContainerLowestLight = Color(0xFFFFFFFF)
    val surfaceContainerLowLight = Color(0xFFF1F3FC)
    val surfaceContainerLight = Color(0xFFEBEEF6)
    val surfaceContainerHighLight = Color(0xFFE5E8F0)
    val surfaceContainerHighestLight = Color(0xFFDFE2EA)

    val primaryLightMediumContrast = Color(0xFF003862)
    val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
    val primaryContainerLightMediumContrast = Color(0xFF0070BC)
    val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
    val secondaryLightMediumContrast = Color(0xFF003475)
    val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
    val secondaryContainerLightMediumContrast = Color(0xFF0A69DC)
    val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
    val tertiaryLightMediumContrast = Color(0xFF003A57)
    val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
    val tertiaryContainerLightMediumContrast = Color(0xFF0074A9)
    val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
    val errorLightMediumContrast = Color(0xFF740006)
    val onErrorLightMediumContrast = Color(0xFFFFFFFF)
    val errorContainerLightMediumContrast = Color(0xFFCF2C27)
    val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
    val backgroundLightMediumContrast = Color(0xFFF8F9FF)
    val onBackgroundLightMediumContrast = Color(0xFF181C22)
    val surfaceLightMediumContrast = Color(0xFFF8F9FF)
    val onSurfaceLightMediumContrast = Color(0xFF0D1117)
    val surfaceVariantLightMediumContrast = Color(0xFFDBE3F0)
    val onSurfaceVariantLightMediumContrast = Color(0xFF2F3741)
    val outlineLightMediumContrast = Color(0xFF4B535E)
    val outlineVariantLightMediumContrast = Color(0xFF666E79)
    val scrimLightMediumContrast = Color(0xFF000000)
    val inverseSurfaceLightMediumContrast = Color(0xFF2D3137)
    val inverseOnSurfaceLightMediumContrast = Color(0xFFEEF1F9)
    val inversePrimaryLightMediumContrast = Color(0xFF9ECAFF)
    val surfaceDimLightMediumContrast = Color(0xFFC3C6CE)
    val surfaceBrightLightMediumContrast = Color(0xFFF8F9FF)
    val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
    val surfaceContainerLowLightMediumContrast = Color(0xFFF1F3FC)
    val surfaceContainerLightMediumContrast = Color(0xFFE5E8F0)
    val surfaceContainerHighLightMediumContrast = Color(0xFFDADDE5)
    val surfaceContainerHighestLightMediumContrast = Color(0xFFCED2D9)

    val primaryLightHighContrast = Color(0xFF002E51)
    val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
    val primaryContainerLightHighContrast = Color(0xFF004B81)
    val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
    val secondaryLightHighContrast = Color(0xFF002A61)
    val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
    val secondaryContainerLightHighContrast = Color(0xFF004699)
    val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
    val tertiaryLightHighContrast = Color(0xFF002F48)
    val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
    val tertiaryContainerLightHighContrast = Color(0xFF004E73)
    val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
    val errorLightHighContrast = Color(0xFF600004)
    val onErrorLightHighContrast = Color(0xFFFFFFFF)
    val errorContainerLightHighContrast = Color(0xFF98000A)
    val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
    val backgroundLightHighContrast = Color(0xFFF8F9FF)
    val onBackgroundLightHighContrast = Color(0xFF181C22)
    val surfaceLightHighContrast = Color(0xFFF8F9FF)
    val onSurfaceLightHighContrast = Color(0xFF000000)
    val surfaceVariantLightHighContrast = Color(0xFFDBE3F0)
    val onSurfaceVariantLightHighContrast = Color(0xFF000000)
    val outlineLightHighContrast = Color(0xFF252D37)
    val outlineVariantLightHighContrast = Color(0xFF424A55)
    val scrimLightHighContrast = Color(0xFF000000)
    val inverseSurfaceLightHighContrast = Color(0xFF2D3137)
    val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
    val inversePrimaryLightHighContrast = Color(0xFF9ECAFF)
    val surfaceDimLightHighContrast = Color(0xFFB5B9C0)
    val surfaceBrightLightHighContrast = Color(0xFFF8F9FF)
    val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
    val surfaceContainerLowLightHighContrast = Color(0xFFEEF1F9)
    val surfaceContainerLightHighContrast = Color(0xFFDFE2EA)
    val surfaceContainerHighLightHighContrast = Color(0xFFD1D4DC)
    val surfaceContainerHighestLightHighContrast = Color(0xFFC3C6CE)

    val primaryDark = Color(0xFF9ECAFF)
    val onPrimaryDark = Color(0xFF003258)
    val primaryContainerDark = Color(0xFF2196F3)
    val onPrimaryContainerDark = Color(0xFF002C4F)
    val secondaryDark = Color(0xFFADC6FF)
    val onSecondaryDark = Color(0xFF002E6A)
    val secondaryContainerDark = Color(0xFF4D8EFF)
    val onSecondaryContainerDark = Color(0xFF002456)
    val tertiaryDark = Color(0xFF8DCDFF)
    val onTertiaryDark = Color(0xFF00344F)
    val tertiaryContainerDark = Color(0xFF03A9F4)
    val onTertiaryContainerDark = Color(0xFF003A58)
    val errorDark = Color(0xFFFFB4AB)
    val onErrorDark = Color(0xFF690005)
    val errorContainerDark = Color(0xFF93000A)
    val onErrorContainerDark = Color(0xFFFFDAD6)
    val backgroundDark = Color(0xFF0F1419)
    val onBackgroundDark = Color(0xFFDFE2EA)
    val surfaceDark = Color(0xFF0F1419)
    val onSurfaceDark = Color(0xFFDFE2EA)
    val surfaceVariantDark = Color(0xFF404752)
    val onSurfaceVariantDark = Color(0xFFBFC7D4)
    val outlineDark = Color(0xFF89919D)
    val outlineVariantDark = Color(0xFF404752)
    val scrimDark = Color(0xFF000000)
    val inverseSurfaceDark = Color(0xFFDFE2EA)
    val inverseOnSurfaceDark = Color(0xFF2D3137)
    val inversePrimaryDark = Color(0xFF0061A4)
    val surfaceDimDark = Color(0xFF0F1419)
    val surfaceBrightDark = Color(0xFF353940)
    val surfaceContainerLowestDark = Color(0xFF0A0E14)
    val surfaceContainerLowDark = Color(0xFF181C22)
    val surfaceContainerDark = Color(0xFF1C2026)
    val surfaceContainerHighDark = Color(0xFF262A30)
    val surfaceContainerHighestDark = Color(0xFF31353B)

    val primaryDarkMediumContrast = Color(0xFFC6DEFF)
    val onPrimaryDarkMediumContrast = Color(0xFF002746)
    val primaryContainerDarkMediumContrast = Color(0xFF2196F3)
    val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
    val secondaryDarkMediumContrast = Color(0xFFCFDCFF)
    val onSecondaryDarkMediumContrast = Color(0xFF002455)
    val secondaryContainerDarkMediumContrast = Color(0xFF4D8EFF)
    val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
    val tertiaryDarkMediumContrast = Color(0xFFBDE1FF)
    val onTertiaryDarkMediumContrast = Color(0xFF00283F)
    val tertiaryContainerDarkMediumContrast = Color(0xFF03A9F4)
    val onTertiaryContainerDarkMediumContrast = Color(0xFF001523)
    val errorDarkMediumContrast = Color(0xFFFFD2CC)
    val onErrorDarkMediumContrast = Color(0xFF540003)
    val errorContainerDarkMediumContrast = Color(0xFFFF5449)
    val onErrorContainerDarkMediumContrast = Color(0xFF000000)
    val backgroundDarkMediumContrast = Color(0xFF0F1419)
    val onBackgroundDarkMediumContrast = Color(0xFFDFE2EA)
    val surfaceDarkMediumContrast = Color(0xFF0F1419)
    val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
    val surfaceVariantDarkMediumContrast = Color(0xFF404752)
    val onSurfaceVariantDarkMediumContrast = Color(0xFFD5DDEA)
    val outlineDarkMediumContrast = Color(0xFFABB2BF)
    val outlineVariantDarkMediumContrast = Color(0xFF89919D)
    val scrimDarkMediumContrast = Color(0xFF000000)
    val inverseSurfaceDarkMediumContrast = Color(0xFFDFE2EA)
    val inverseOnSurfaceDarkMediumContrast = Color(0xFF262A30)
    val inversePrimaryDarkMediumContrast = Color(0xFF004A7F)
    val surfaceDimDarkMediumContrast = Color(0xFF0F1419)
    val surfaceBrightDarkMediumContrast = Color(0xFF41454B)
    val surfaceContainerLowestDarkMediumContrast = Color(0xFF04080D)
    val surfaceContainerLowDarkMediumContrast = Color(0xFF1A1E24)
    val surfaceContainerDarkMediumContrast = Color(0xFF24282E)
    val surfaceContainerHighDarkMediumContrast = Color(0xFF2F3339)
    val surfaceContainerHighestDarkMediumContrast = Color(0xFF3A3E44)

    val primaryDarkHighContrast = Color(0xFFE8F0FF)
    val onPrimaryDarkHighContrast = Color(0xFF000000)
    val primaryContainerDarkHighContrast = Color(0xFF97C6FF)
    val onPrimaryContainerDarkHighContrast = Color(0xFF000C1B)
    val secondaryDarkHighContrast = Color(0xFFECEFFF)
    val onSecondaryDarkHighContrast = Color(0xFF000000)
    val secondaryContainerDarkHighContrast = Color(0xFFA7C2FF)
    val onSecondaryContainerDarkHighContrast = Color(0xFF000A22)
    val tertiaryDarkHighContrast = Color(0xFFE5F1FF)
    val onTertiaryDarkHighContrast = Color(0xFF000000)
    val tertiaryContainerDarkHighContrast = Color(0xFF83CAFF)
    val onTertiaryContainerDarkHighContrast = Color(0xFF000D17)
    val errorDarkHighContrast = Color(0xFFFFECE9)
    val onErrorDarkHighContrast = Color(0xFF000000)
    val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
    val onErrorContainerDarkHighContrast = Color(0xFF220001)
    val backgroundDarkHighContrast = Color(0xFF0F1419)
    val onBackgroundDarkHighContrast = Color(0xFFDFE2EA)
    val surfaceDarkHighContrast = Color(0xFF0F1419)
    val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
    val surfaceVariantDarkHighContrast = Color(0xFF404752)
    val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
    val outlineDarkHighContrast = Color(0xFFE9F0FE)
    val outlineVariantDarkHighContrast = Color(0xFFBBC3D0)
    val scrimDarkHighContrast = Color(0xFF000000)
    val inverseSurfaceDarkHighContrast = Color(0xFFDFE2EA)
    val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
    val inversePrimaryDarkHighContrast = Color(0xFF004A7F)
    val surfaceDimDarkHighContrast = Color(0xFF0F1419)
    val surfaceBrightDarkHighContrast = Color(0xFF4C5057)
    val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
    val surfaceContainerLowDarkHighContrast = Color(0xFF1C2026)
    val surfaceContainerDarkHighContrast = Color(0xFF2D3137)
    val surfaceContainerHighDarkHighContrast = Color(0xFF383C42)
    val surfaceContainerHighestDarkHighContrast = Color(0xFF43474D)
    internal val lightScheme = lightColorScheme(
        primary = primaryLight,
        onPrimary = onPrimaryLight,
        primaryContainer = primaryContainerLight,
        onPrimaryContainer = onPrimaryContainerLight,
        secondary = secondaryLight,
        onSecondary = onSecondaryLight,
        secondaryContainer = secondaryContainerLight,
        onSecondaryContainer = onSecondaryContainerLight,
        tertiary = tertiaryLight,
        onTertiary = onTertiaryLight,
        tertiaryContainer = tertiaryContainerLight,
        onTertiaryContainer = onTertiaryContainerLight,
        error = errorLight,
        onError = onErrorLight,
        errorContainer = errorContainerLight,
        onErrorContainer = onErrorContainerLight,
        background = backgroundLight,
        onBackground = onBackgroundLight,
        surface = surfaceLight,
        onSurface = onSurfaceLight,
        surfaceVariant = surfaceVariantLight,
        onSurfaceVariant = onSurfaceVariantLight,
        outline = outlineLight,
        outlineVariant = outlineVariantLight,
        scrim = scrimLight,
        inverseSurface = inverseSurfaceLight,
        inverseOnSurface = inverseOnSurfaceLight,
        inversePrimary = inversePrimaryLight,
        surfaceDim = surfaceDimLight,
        surfaceBright = surfaceBrightLight,
        surfaceContainerLowest = surfaceContainerLowestLight,
        surfaceContainerLow = surfaceContainerLowLight,
        surfaceContainer = surfaceContainerLight,
        surfaceContainerHigh = surfaceContainerHighLight,
        surfaceContainerHighest = surfaceContainerHighestLight,
    )

    internal val darkScheme = darkColorScheme(
        primary = primaryDark,
        onPrimary = onPrimaryDark,
        primaryContainer = primaryContainerDark,
        onPrimaryContainer = onPrimaryContainerDark,
        secondary = secondaryDark,
        onSecondary = onSecondaryDark,
        secondaryContainer = secondaryContainerDark,
        onSecondaryContainer = onSecondaryContainerDark,
        tertiary = tertiaryDark,
        onTertiary = onTertiaryDark,
        tertiaryContainer = tertiaryContainerDark,
        onTertiaryContainer = onTertiaryContainerDark,
        error = errorDark,
        onError = onErrorDark,
        errorContainer = errorContainerDark,
        onErrorContainer = onErrorContainerDark,
        background = backgroundDark,
        onBackground = onBackgroundDark,
        surface = surfaceDark,
        onSurface = onSurfaceDark,
        surfaceVariant = surfaceVariantDark,
        onSurfaceVariant = onSurfaceVariantDark,
        outline = outlineDark,
        outlineVariant = outlineVariantDark,
        scrim = scrimDark,
        inverseSurface = inverseSurfaceDark,
        inverseOnSurface = inverseOnSurfaceDark,
        inversePrimary = inversePrimaryDark,
        surfaceDim = surfaceDimDark,
        surfaceBright = surfaceBrightDark,
        surfaceContainerLowest = surfaceContainerLowestDark,
        surfaceContainerLow = surfaceContainerLowDark,
        surfaceContainer = surfaceContainerDark,
        surfaceContainerHigh = surfaceContainerHighDark,
        surfaceContainerHighest = surfaceContainerHighestDark,
    )

    private val mediumContrastLightColorScheme = lightColorScheme(
        primary = primaryLightMediumContrast,
        onPrimary = onPrimaryLightMediumContrast,
        primaryContainer = primaryContainerLightMediumContrast,
        onPrimaryContainer = onPrimaryContainerLightMediumContrast,
        secondary = secondaryLightMediumContrast,
        onSecondary = onSecondaryLightMediumContrast,
        secondaryContainer = secondaryContainerLightMediumContrast,
        onSecondaryContainer = onSecondaryContainerLightMediumContrast,
        tertiary = tertiaryLightMediumContrast,
        onTertiary = onTertiaryLightMediumContrast,
        tertiaryContainer = tertiaryContainerLightMediumContrast,
        onTertiaryContainer = onTertiaryContainerLightMediumContrast,
        error = errorLightMediumContrast,
        onError = onErrorLightMediumContrast,
        errorContainer = errorContainerLightMediumContrast,
        onErrorContainer = onErrorContainerLightMediumContrast,
        background = backgroundLightMediumContrast,
        onBackground = onBackgroundLightMediumContrast,
        surface = surfaceLightMediumContrast,
        onSurface = onSurfaceLightMediumContrast,
        surfaceVariant = surfaceVariantLightMediumContrast,
        onSurfaceVariant = onSurfaceVariantLightMediumContrast,
        outline = outlineLightMediumContrast,
        outlineVariant = outlineVariantLightMediumContrast,
        scrim = scrimLightMediumContrast,
        inverseSurface = inverseSurfaceLightMediumContrast,
        inverseOnSurface = inverseOnSurfaceLightMediumContrast,
        inversePrimary = inversePrimaryLightMediumContrast,
        surfaceDim = surfaceDimLightMediumContrast,
        surfaceBright = surfaceBrightLightMediumContrast,
        surfaceContainerLowest = surfaceContainerLowestLightMediumContrast,
        surfaceContainerLow = surfaceContainerLowLightMediumContrast,
        surfaceContainer = surfaceContainerLightMediumContrast,
        surfaceContainerHigh = surfaceContainerHighLightMediumContrast,
        surfaceContainerHighest = surfaceContainerHighestLightMediumContrast,
    )

    private val highContrastLightColorScheme = lightColorScheme(
        primary = primaryLightHighContrast,
        onPrimary = onPrimaryLightHighContrast,
        primaryContainer = primaryContainerLightHighContrast,
        onPrimaryContainer = onPrimaryContainerLightHighContrast,
        secondary = secondaryLightHighContrast,
        onSecondary = onSecondaryLightHighContrast,
        secondaryContainer = secondaryContainerLightHighContrast,
        onSecondaryContainer = onSecondaryContainerLightHighContrast,
        tertiary = tertiaryLightHighContrast,
        onTertiary = onTertiaryLightHighContrast,
        tertiaryContainer = tertiaryContainerLightHighContrast,
        onTertiaryContainer = onTertiaryContainerLightHighContrast,
        error = errorLightHighContrast,
        onError = onErrorLightHighContrast,
        errorContainer = errorContainerLightHighContrast,
        onErrorContainer = onErrorContainerLightHighContrast,
        background = backgroundLightHighContrast,
        onBackground = onBackgroundLightHighContrast,
        surface = surfaceLightHighContrast,
        onSurface = onSurfaceLightHighContrast,
        surfaceVariant = surfaceVariantLightHighContrast,
        onSurfaceVariant = onSurfaceVariantLightHighContrast,
        outline = outlineLightHighContrast,
        outlineVariant = outlineVariantLightHighContrast,
        scrim = scrimLightHighContrast,
        inverseSurface = inverseSurfaceLightHighContrast,
        inverseOnSurface = inverseOnSurfaceLightHighContrast,
        inversePrimary = inversePrimaryLightHighContrast,
        surfaceDim = surfaceDimLightHighContrast,
        surfaceBright = surfaceBrightLightHighContrast,
        surfaceContainerLowest = surfaceContainerLowestLightHighContrast,
        surfaceContainerLow = surfaceContainerLowLightHighContrast,
        surfaceContainer = surfaceContainerLightHighContrast,
        surfaceContainerHigh = surfaceContainerHighLightHighContrast,
        surfaceContainerHighest = surfaceContainerHighestLightHighContrast,
    )

    private val mediumContrastDarkColorScheme = darkColorScheme(
        primary = primaryDarkMediumContrast,
        onPrimary = onPrimaryDarkMediumContrast,
        primaryContainer = primaryContainerDarkMediumContrast,
        onPrimaryContainer = onPrimaryContainerDarkMediumContrast,
        secondary = secondaryDarkMediumContrast,
        onSecondary = onSecondaryDarkMediumContrast,
        secondaryContainer = secondaryContainerDarkMediumContrast,
        onSecondaryContainer = onSecondaryContainerDarkMediumContrast,
        tertiary = tertiaryDarkMediumContrast,
        onTertiary = onTertiaryDarkMediumContrast,
        tertiaryContainer = tertiaryContainerDarkMediumContrast,
        onTertiaryContainer = onTertiaryContainerDarkMediumContrast,
        error = errorDarkMediumContrast,
        onError = onErrorDarkMediumContrast,
        errorContainer = errorContainerDarkMediumContrast,
        onErrorContainer = onErrorContainerDarkMediumContrast,
        background = backgroundDarkMediumContrast,
        onBackground = onBackgroundDarkMediumContrast,
        surface = surfaceDarkMediumContrast,
        onSurface = onSurfaceDarkMediumContrast,
        surfaceVariant = surfaceVariantDarkMediumContrast,
        onSurfaceVariant = onSurfaceVariantDarkMediumContrast,
        outline = outlineDarkMediumContrast,
        outlineVariant = outlineVariantDarkMediumContrast,
        scrim = scrimDarkMediumContrast,
        inverseSurface = inverseSurfaceDarkMediumContrast,
        inverseOnSurface = inverseOnSurfaceDarkMediumContrast,
        inversePrimary = inversePrimaryDarkMediumContrast,
        surfaceDim = surfaceDimDarkMediumContrast,
        surfaceBright = surfaceBrightDarkMediumContrast,
        surfaceContainerLowest = surfaceContainerLowestDarkMediumContrast,
        surfaceContainerLow = surfaceContainerLowDarkMediumContrast,
        surfaceContainer = surfaceContainerDarkMediumContrast,
        surfaceContainerHigh = surfaceContainerHighDarkMediumContrast,
        surfaceContainerHighest = surfaceContainerHighestDarkMediumContrast,
    )

    private val highContrastDarkColorScheme = darkColorScheme(
        primary = primaryDarkHighContrast,
        onPrimary = onPrimaryDarkHighContrast,
        primaryContainer = primaryContainerDarkHighContrast,
        onPrimaryContainer = onPrimaryContainerDarkHighContrast,
        secondary = secondaryDarkHighContrast,
        onSecondary = onSecondaryDarkHighContrast,
        secondaryContainer = secondaryContainerDarkHighContrast,
        onSecondaryContainer = onSecondaryContainerDarkHighContrast,
        tertiary = tertiaryDarkHighContrast,
        onTertiary = onTertiaryDarkHighContrast,
        tertiaryContainer = tertiaryContainerDarkHighContrast,
        onTertiaryContainer = onTertiaryContainerDarkHighContrast,
        error = errorDarkHighContrast,
        onError = onErrorDarkHighContrast,
        errorContainer = errorContainerDarkHighContrast,
        onErrorContainer = onErrorContainerDarkHighContrast,
        background = backgroundDarkHighContrast,
        onBackground = onBackgroundDarkHighContrast,
        surface = surfaceDarkHighContrast,
        onSurface = onSurfaceDarkHighContrast,
        surfaceVariant = surfaceVariantDarkHighContrast,
        onSurfaceVariant = onSurfaceVariantDarkHighContrast,
        outline = outlineDarkHighContrast,
        outlineVariant = outlineVariantDarkHighContrast,
        scrim = scrimDarkHighContrast,
        inverseSurface = inverseSurfaceDarkHighContrast,
        inverseOnSurface = inverseOnSurfaceDarkHighContrast,
        inversePrimary = inversePrimaryDarkHighContrast,
        surfaceDim = surfaceDimDarkHighContrast,
        surfaceBright = surfaceBrightDarkHighContrast,
        surfaceContainerLowest = surfaceContainerLowestDarkHighContrast,
        surfaceContainerLow = surfaceContainerLowDarkHighContrast,
        surfaceContainer = surfaceContainerDarkHighContrast,
        surfaceContainerHigh = surfaceContainerHighDarkHighContrast,
        surfaceContainerHighest = surfaceContainerHighestDarkHighContrast,
    )

    val unspecified_scheme = ColorFamily(
        Color.Unspecified, Color.Unspecified, Color.Unspecified, Color.Unspecified
    )

}