package io.nekohasekai.sagernet.compose.theme

import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color

/** 镜揉蓝浅 */
object LightBlue {
    val primaryLight = Color(0xFF006493)
    val onPrimaryLight = Color(0xFFFFFFFF)
    val primaryContainerLight = Color(0xFF03A9F4)
    val onPrimaryContainerLight = Color(0xFF003A58)
    val secondaryLight = Color(0xFF00668A)
    val onSecondaryLight = Color(0xFFFFFFFF)
    val secondaryContainerLight = Color(0xFF40C4FF)
    val onSecondaryContainerLight = Color(0xFF004E6B)
    val tertiaryLight = Color(0xFF006876)
    val onTertiaryLight = Color(0xFFFFFFFF)
    val tertiaryContainerLight = Color(0xFF00BCD4)
    val onTertiaryContainerLight = Color(0xFF004650)
    val errorLight = Color(0xFFBA1A1A)
    val onErrorLight = Color(0xFFFFFFFF)
    val errorContainerLight = Color(0xFFFFDAD6)
    val onErrorContainerLight = Color(0xFF93000A)
    val backgroundLight = Color(0xFFF6F9FF)
    val onBackgroundLight = Color(0xFF171C21)
    val surfaceLight = Color(0xFFF6F9FF)
    val onSurfaceLight = Color(0xFF171C21)
    val surfaceVariantLight = Color(0xFFDAE4EF)
    val onSurfaceVariantLight = Color(0xFF3E4851)
    val outlineLight = Color(0xFF6E7882)
    val outlineVariantLight = Color(0xFFBEC8D2)
    val scrimLight = Color(0xFF000000)
    val inverseSurfaceLight = Color(0xFF2C3136)
    val inverseOnSurfaceLight = Color(0xFFEDF1F8)
    val inversePrimaryLight = Color(0xFF8DCDFF)
    val surfaceDimLight = Color(0xFFD6DAE1)
    val surfaceBrightLight = Color(0xFFF6F9FF)
    val surfaceContainerLowestLight = Color(0xFFFFFFFF)
    val surfaceContainerLowLight = Color(0xFFF0F4FA)
    val surfaceContainerLight = Color(0xFFEAEEF5)
    val surfaceContainerHighLight = Color(0xFFE4E8EF)
    val surfaceContainerHighestLight = Color(0xFFDEE3E9)

    val primaryLightMediumContrast = Color(0xFF003A57)
    val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
    val primaryContainerLightMediumContrast = Color(0xFF0074A9)
    val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
    val secondaryLightMediumContrast = Color(0xFF003B51)
    val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
    val secondaryContainerLightMediumContrast = Color(0xFF00759E)
    val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
    val tertiaryLightMediumContrast = Color(0xFF003C45)
    val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
    val tertiaryContainerLightMediumContrast = Color(0xFF007888)
    val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
    val errorLightMediumContrast = Color(0xFF740006)
    val onErrorLightMediumContrast = Color(0xFFFFFFFF)
    val errorContainerLightMediumContrast = Color(0xFFCF2C27)
    val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
    val backgroundLightMediumContrast = Color(0xFFF6F9FF)
    val onBackgroundLightMediumContrast = Color(0xFF171C21)
    val surfaceLightMediumContrast = Color(0xFFF6F9FF)
    val onSurfaceLightMediumContrast = Color(0xFF0D1216)
    val surfaceVariantLightMediumContrast = Color(0xFFDAE4EF)
    val onSurfaceVariantLightMediumContrast = Color(0xFF2E3740)
    val outlineLightMediumContrast = Color(0xFF4A545D)
    val outlineVariantLightMediumContrast = Color(0xFF646E78)
    val scrimLightMediumContrast = Color(0xFF000000)
    val inverseSurfaceLightMediumContrast = Color(0xFF2C3136)
    val inverseOnSurfaceLightMediumContrast = Color(0xFFEDF1F8)
    val inversePrimaryLightMediumContrast = Color(0xFF8DCDFF)
    val surfaceDimLightMediumContrast = Color(0xFFC2C7CD)
    val surfaceBrightLightMediumContrast = Color(0xFFF6F9FF)
    val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
    val surfaceContainerLowLightMediumContrast = Color(0xFFF0F4FA)
    val surfaceContainerLightMediumContrast = Color(0xFFE4E8EF)
    val surfaceContainerHighLightMediumContrast = Color(0xFFD9DDE4)
    val surfaceContainerHighestLightMediumContrast = Color(0xFFCDD2D8)

    val primaryLightHighContrast = Color(0xFF002F48)
    val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
    val primaryContainerLightHighContrast = Color(0xFF004E73)
    val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
    val secondaryLightHighContrast = Color(0xFF003043)
    val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
    val secondaryContainerLightHighContrast = Color(0xFF004F6C)
    val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
    val tertiaryLightHighContrast = Color(0xFF003139)
    val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
    val tertiaryContainerLightHighContrast = Color(0xFF00515C)
    val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
    val errorLightHighContrast = Color(0xFF600004)
    val onErrorLightHighContrast = Color(0xFFFFFFFF)
    val errorContainerLightHighContrast = Color(0xFF98000A)
    val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
    val backgroundLightHighContrast = Color(0xFFF6F9FF)
    val onBackgroundLightHighContrast = Color(0xFF171C21)
    val surfaceLightHighContrast = Color(0xFFF6F9FF)
    val onSurfaceLightHighContrast = Color(0xFF000000)
    val surfaceVariantLightHighContrast = Color(0xFFDAE4EF)
    val onSurfaceVariantLightHighContrast = Color(0xFF000000)
    val outlineLightHighContrast = Color(0xFF242D35)
    val outlineVariantLightHighContrast = Color(0xFF404A53)
    val scrimLightHighContrast = Color(0xFF000000)
    val inverseSurfaceLightHighContrast = Color(0xFF2C3136)
    val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
    val inversePrimaryLightHighContrast = Color(0xFF8DCDFF)
    val surfaceDimLightHighContrast = Color(0xFFB4B9BF)
    val surfaceBrightLightHighContrast = Color(0xFFF6F9FF)
    val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
    val surfaceContainerLowLightHighContrast = Color(0xFFEDF1F8)
    val surfaceContainerLightHighContrast = Color(0xFFDEE3E9)
    val surfaceContainerHighLightHighContrast = Color(0xFFD0D5DB)
    val surfaceContainerHighestLightHighContrast = Color(0xFFC2C7CD)

    val primaryDark = Color(0xFF8DCDFF)
    val onPrimaryDark = Color(0xFF00344F)
    val primaryContainerDark = Color(0xFF03A9F4)
    val onPrimaryContainerDark = Color(0xFF003A58)
    val secondaryDark = Color(0xFF9FDBFF)
    val onSecondaryDark = Color(0xFF003549)
    val secondaryContainerDark = Color(0xFF40C4FF)
    val onSecondaryContainerDark = Color(0xFF004E6B)
    val tertiaryDark = Color(0xFF44D8F1)
    val onTertiaryDark = Color(0xFF00363E)
    val tertiaryContainerDark = Color(0xFF00BCD4)
    val onTertiaryContainerDark = Color(0xFF004650)
    val errorDark = Color(0xFFFFB4AB)
    val onErrorDark = Color(0xFF690005)
    val errorContainerDark = Color(0xFF93000A)
    val onErrorContainerDark = Color(0xFFFFDAD6)
    val backgroundDark = Color(0xFF0F1418)
    val onBackgroundDark = Color(0xFFDEE3E9)
    val surfaceDark = Color(0xFF0F1418)
    val onSurfaceDark = Color(0xFFDEE3E9)
    val surfaceVariantDark = Color(0xFF3E4851)
    val onSurfaceVariantDark = Color(0xFFBEC8D2)
    val outlineDark = Color(0xFF88929C)
    val outlineVariantDark = Color(0xFF3E4851)
    val scrimDark = Color(0xFF000000)
    val inverseSurfaceDark = Color(0xFFDEE3E9)
    val inverseOnSurfaceDark = Color(0xFF2C3136)
    val inversePrimaryDark = Color(0xFF006493)
    val surfaceDimDark = Color(0xFF0F1418)
    val surfaceBrightDark = Color(0xFF353A3F)
    val surfaceContainerLowestDark = Color(0xFF0A0F13)
    val surfaceContainerLowDark = Color(0xFF171C21)
    val surfaceContainerDark = Color(0xFF1B2025)
    val surfaceContainerHighDark = Color(0xFF252B2F)
    val surfaceContainerHighestDark = Color(0xFF30353A)

    val primaryDarkMediumContrast = Color(0xFFBDE1FF)
    val onPrimaryDarkMediumContrast = Color(0xFF00283F)
    val primaryContainerDarkMediumContrast = Color(0xFF03A9F4)
    val onPrimaryContainerDarkMediumContrast = Color(0xFF001523)
    val secondaryDarkMediumContrast = Color(0xFFB5E2FF)
    val onSecondaryDarkMediumContrast = Color(0xFF00293A)
    val secondaryContainerDarkMediumContrast = Color(0xFF40C4FF)
    val onSecondaryContainerDarkMediumContrast = Color(0xFF002F42)
    val tertiaryDarkMediumContrast = Color(0xFF86EBFF)
    val onTertiaryDarkMediumContrast = Color(0xFF002A31)
    val tertiaryContainerDarkMediumContrast = Color(0xFF00BCD4)
    val onTertiaryContainerDarkMediumContrast = Color(0xFF00252B)
    val errorDarkMediumContrast = Color(0xFFFFD2CC)
    val onErrorDarkMediumContrast = Color(0xFF540003)
    val errorContainerDarkMediumContrast = Color(0xFFFF5449)
    val onErrorContainerDarkMediumContrast = Color(0xFF000000)
    val backgroundDarkMediumContrast = Color(0xFF0F1418)
    val onBackgroundDarkMediumContrast = Color(0xFFDEE3E9)
    val surfaceDarkMediumContrast = Color(0xFF0F1418)
    val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
    val surfaceVariantDarkMediumContrast = Color(0xFF3E4851)
    val onSurfaceVariantDarkMediumContrast = Color(0xFFD3DDE8)
    val outlineDarkMediumContrast = Color(0xFFA9B3BD)
    val outlineVariantDarkMediumContrast = Color(0xFF87919B)
    val scrimDarkMediumContrast = Color(0xFF000000)
    val inverseSurfaceDarkMediumContrast = Color(0xFFDEE3E9)
    val inverseOnSurfaceDarkMediumContrast = Color(0xFF252B2F)
    val inversePrimaryDarkMediumContrast = Color(0xFF004D72)
    val surfaceDimDarkMediumContrast = Color(0xFF0F1418)
    val surfaceBrightDarkMediumContrast = Color(0xFF40454A)
    val surfaceContainerLowestDarkMediumContrast = Color(0xFF04080C)
    val surfaceContainerLowDarkMediumContrast = Color(0xFF191E23)
    val surfaceContainerDarkMediumContrast = Color(0xFF23282D)
    val surfaceContainerHighDarkMediumContrast = Color(0xFF2E3338)
    val surfaceContainerHighestDarkMediumContrast = Color(0xFF393E43)

    val primaryDarkHighContrast = Color(0xFFE5F1FF)
    val onPrimaryDarkHighContrast = Color(0xFF000000)
    val primaryContainerDarkHighContrast = Color(0xFF83CAFF)
    val onPrimaryContainerDarkHighContrast = Color(0xFF000D17)
    val secondaryDarkHighContrast = Color(0xFFE1F2FF)
    val onSecondaryDarkHighContrast = Color(0xFF000000)
    val secondaryContainerDarkHighContrast = Color(0xFF6ECDFF)
    val onSecondaryContainerDarkHighContrast = Color(0xFF000D15)
    val tertiaryDarkHighContrast = Color(0xFFD1F6FF)
    val onTertiaryDarkHighContrast = Color(0xFF000000)
    val tertiaryContainerDarkHighContrast = Color(0xFF3ED4ED)
    val onTertiaryContainerDarkHighContrast = Color(0xFF000D11)
    val errorDarkHighContrast = Color(0xFFFFECE9)
    val onErrorDarkHighContrast = Color(0xFF000000)
    val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
    val onErrorContainerDarkHighContrast = Color(0xFF220001)
    val backgroundDarkHighContrast = Color(0xFF0F1418)
    val onBackgroundDarkHighContrast = Color(0xFFDEE3E9)
    val surfaceDarkHighContrast = Color(0xFF0F1418)
    val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
    val surfaceVariantDarkHighContrast = Color(0xFF3E4851)
    val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
    val outlineDarkHighContrast = Color(0xFFE7F1FC)
    val outlineVariantDarkHighContrast = Color(0xFFBAC4CE)
    val scrimDarkHighContrast = Color(0xFF000000)
    val inverseSurfaceDarkHighContrast = Color(0xFFDEE3E9)
    val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
    val inversePrimaryDarkHighContrast = Color(0xFF004D72)
    val surfaceDimDarkHighContrast = Color(0xFF0F1418)
    val surfaceBrightDarkHighContrast = Color(0xFF4B5156)
    val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
    val surfaceContainerLowDarkHighContrast = Color(0xFF1B2025)
    val surfaceContainerDarkHighContrast = Color(0xFF2C3136)
    val surfaceContainerHighDarkHighContrast = Color(0xFF373C41)
    val surfaceContainerHighestDarkHighContrast = Color(0xFF42474D)
    internal val lightScheme = lightColorScheme(
        primary = primaryLight,
        onPrimary = onPrimaryLight,
        primaryContainer = primaryContainerLight,
        onPrimaryContainer = onPrimaryContainerLight,
        secondary = secondaryLight,
        onSecondary = onSecondaryLight,
        secondaryContainer = secondaryContainerLight,
        onSecondaryContainer = onSecondaryContainerLight,
        tertiary = tertiaryLight,
        onTertiary = onTertiaryLight,
        tertiaryContainer = tertiaryContainerLight,
        onTertiaryContainer = onTertiaryContainerLight,
        error = errorLight,
        onError = onErrorLight,
        errorContainer = errorContainerLight,
        onErrorContainer = onErrorContainerLight,
        background = backgroundLight,
        onBackground = onBackgroundLight,
        surface = surfaceLight,
        onSurface = onSurfaceLight,
        surfaceVariant = surfaceVariantLight,
        onSurfaceVariant = onSurfaceVariantLight,
        outline = outlineLight,
        outlineVariant = outlineVariantLight,
        scrim = scrimLight,
        inverseSurface = inverseSurfaceLight,
        inverseOnSurface = inverseOnSurfaceLight,
        inversePrimary = inversePrimaryLight,
        surfaceDim = surfaceDimLight,
        surfaceBright = surfaceBrightLight,
        surfaceContainerLowest = surfaceContainerLowestLight,
        surfaceContainerLow = surfaceContainerLowLight,
        surfaceContainer = surfaceContainerLight,
        surfaceContainerHigh = surfaceContainerHighLight,
        surfaceContainerHighest = surfaceContainerHighestLight,
    )

    internal val darkScheme = darkColorScheme(
        primary = primaryDark,
        onPrimary = onPrimaryDark,
        primaryContainer = primaryContainerDark,
        onPrimaryContainer = onPrimaryContainerDark,
        secondary = secondaryDark,
        onSecondary = onSecondaryDark,
        secondaryContainer = secondaryContainerDark,
        onSecondaryContainer = onSecondaryContainerDark,
        tertiary = tertiaryDark,
        onTertiary = onTertiaryDark,
        tertiaryContainer = tertiaryContainerDark,
        onTertiaryContainer = onTertiaryContainerDark,
        error = errorDark,
        onError = onErrorDark,
        errorContainer = errorContainerDark,
        onErrorContainer = onErrorContainerDark,
        background = backgroundDark,
        onBackground = onBackgroundDark,
        surface = surfaceDark,
        onSurface = onSurfaceDark,
        surfaceVariant = surfaceVariantDark,
        onSurfaceVariant = onSurfaceVariantDark,
        outline = outlineDark,
        outlineVariant = outlineVariantDark,
        scrim = scrimDark,
        inverseSurface = inverseSurfaceDark,
        inverseOnSurface = inverseOnSurfaceDark,
        inversePrimary = inversePrimaryDark,
        surfaceDim = surfaceDimDark,
        surfaceBright = surfaceBrightDark,
        surfaceContainerLowest = surfaceContainerLowestDark,
        surfaceContainerLow = surfaceContainerLowDark,
        surfaceContainer = surfaceContainerDark,
        surfaceContainerHigh = surfaceContainerHighDark,
        surfaceContainerHighest = surfaceContainerHighestDark,
    )

    private val mediumContrastLightColorScheme = lightColorScheme(
        primary = primaryLightMediumContrast,
        onPrimary = onPrimaryLightMediumContrast,
        primaryContainer = primaryContainerLightMediumContrast,
        onPrimaryContainer = onPrimaryContainerLightMediumContrast,
        secondary = secondaryLightMediumContrast,
        onSecondary = onSecondaryLightMediumContrast,
        secondaryContainer = secondaryContainerLightMediumContrast,
        onSecondaryContainer = onSecondaryContainerLightMediumContrast,
        tertiary = tertiaryLightMediumContrast,
        onTertiary = onTertiaryLightMediumContrast,
        tertiaryContainer = tertiaryContainerLightMediumContrast,
        onTertiaryContainer = onTertiaryContainerLightMediumContrast,
        error = errorLightMediumContrast,
        onError = onErrorLightMediumContrast,
        errorContainer = errorContainerLightMediumContrast,
        onErrorContainer = onErrorContainerLightMediumContrast,
        background = backgroundLightMediumContrast,
        onBackground = onBackgroundLightMediumContrast,
        surface = surfaceLightMediumContrast,
        onSurface = onSurfaceLightMediumContrast,
        surfaceVariant = surfaceVariantLightMediumContrast,
        onSurfaceVariant = onSurfaceVariantLightMediumContrast,
        outline = outlineLightMediumContrast,
        outlineVariant = outlineVariantLightMediumContrast,
        scrim = scrimLightMediumContrast,
        inverseSurface = inverseSurfaceLightMediumContrast,
        inverseOnSurface = inverseOnSurfaceLightMediumContrast,
        inversePrimary = inversePrimaryLightMediumContrast,
        surfaceDim = surfaceDimLightMediumContrast,
        surfaceBright = surfaceBrightLightMediumContrast,
        surfaceContainerLowest = surfaceContainerLowestLightMediumContrast,
        surfaceContainerLow = surfaceContainerLowLightMediumContrast,
        surfaceContainer = surfaceContainerLightMediumContrast,
        surfaceContainerHigh = surfaceContainerHighLightMediumContrast,
        surfaceContainerHighest = surfaceContainerHighestLightMediumContrast,
    )

    private val highContrastLightColorScheme = lightColorScheme(
        primary = primaryLightHighContrast,
        onPrimary = onPrimaryLightHighContrast,
        primaryContainer = primaryContainerLightHighContrast,
        onPrimaryContainer = onPrimaryContainerLightHighContrast,
        secondary = secondaryLightHighContrast,
        onSecondary = onSecondaryLightHighContrast,
        secondaryContainer = secondaryContainerLightHighContrast,
        onSecondaryContainer = onSecondaryContainerLightHighContrast,
        tertiary = tertiaryLightHighContrast,
        onTertiary = onTertiaryLightHighContrast,
        tertiaryContainer = tertiaryContainerLightHighContrast,
        onTertiaryContainer = onTertiaryContainerLightHighContrast,
        error = errorLightHighContrast,
        onError = onErrorLightHighContrast,
        errorContainer = errorContainerLightHighContrast,
        onErrorContainer = onErrorContainerLightHighContrast,
        background = backgroundLightHighContrast,
        onBackground = onBackgroundLightHighContrast,
        surface = surfaceLightHighContrast,
        onSurface = onSurfaceLightHighContrast,
        surfaceVariant = surfaceVariantLightHighContrast,
        onSurfaceVariant = onSurfaceVariantLightHighContrast,
        outline = outlineLightHighContrast,
        outlineVariant = outlineVariantLightHighContrast,
        scrim = scrimLightHighContrast,
        inverseSurface = inverseSurfaceLightHighContrast,
        inverseOnSurface = inverseOnSurfaceLightHighContrast,
        inversePrimary = inversePrimaryLightHighContrast,
        surfaceDim = surfaceDimLightHighContrast,
        surfaceBright = surfaceBrightLightHighContrast,
        surfaceContainerLowest = surfaceContainerLowestLightHighContrast,
        surfaceContainerLow = surfaceContainerLowLightHighContrast,
        surfaceContainer = surfaceContainerLightHighContrast,
        surfaceContainerHigh = surfaceContainerHighLightHighContrast,
        surfaceContainerHighest = surfaceContainerHighestLightHighContrast,
    )

    private val mediumContrastDarkColorScheme = darkColorScheme(
        primary = primaryDarkMediumContrast,
        onPrimary = onPrimaryDarkMediumContrast,
        primaryContainer = primaryContainerDarkMediumContrast,
        onPrimaryContainer = onPrimaryContainerDarkMediumContrast,
        secondary = secondaryDarkMediumContrast,
        onSecondary = onSecondaryDarkMediumContrast,
        secondaryContainer = secondaryContainerDarkMediumContrast,
        onSecondaryContainer = onSecondaryContainerDarkMediumContrast,
        tertiary = tertiaryDarkMediumContrast,
        onTertiary = onTertiaryDarkMediumContrast,
        tertiaryContainer = tertiaryContainerDarkMediumContrast,
        onTertiaryContainer = onTertiaryContainerDarkMediumContrast,
        error = errorDarkMediumContrast,
        onError = onErrorDarkMediumContrast,
        errorContainer = errorContainerDarkMediumContrast,
        onErrorContainer = onErrorContainerDarkMediumContrast,
        background = backgroundDarkMediumContrast,
        onBackground = onBackgroundDarkMediumContrast,
        surface = surfaceDarkMediumContrast,
        onSurface = onSurfaceDarkMediumContrast,
        surfaceVariant = surfaceVariantDarkMediumContrast,
        onSurfaceVariant = onSurfaceVariantDarkMediumContrast,
        outline = outlineDarkMediumContrast,
        outlineVariant = outlineVariantDarkMediumContrast,
        scrim = scrimDarkMediumContrast,
        inverseSurface = inverseSurfaceDarkMediumContrast,
        inverseOnSurface = inverseOnSurfaceDarkMediumContrast,
        inversePrimary = inversePrimaryDarkMediumContrast,
        surfaceDim = surfaceDimDarkMediumContrast,
        surfaceBright = surfaceBrightDarkMediumContrast,
        surfaceContainerLowest = surfaceContainerLowestDarkMediumContrast,
        surfaceContainerLow = surfaceContainerLowDarkMediumContrast,
        surfaceContainer = surfaceContainerDarkMediumContrast,
        surfaceContainerHigh = surfaceContainerHighDarkMediumContrast,
        surfaceContainerHighest = surfaceContainerHighestDarkMediumContrast,
    )

    private val highContrastDarkColorScheme = darkColorScheme(
        primary = primaryDarkHighContrast,
        onPrimary = onPrimaryDarkHighContrast,
        primaryContainer = primaryContainerDarkHighContrast,
        onPrimaryContainer = onPrimaryContainerDarkHighContrast,
        secondary = secondaryDarkHighContrast,
        onSecondary = onSecondaryDarkHighContrast,
        secondaryContainer = secondaryContainerDarkHighContrast,
        onSecondaryContainer = onSecondaryContainerDarkHighContrast,
        tertiary = tertiaryDarkHighContrast,
        onTertiary = onTertiaryDarkHighContrast,
        tertiaryContainer = tertiaryContainerDarkHighContrast,
        onTertiaryContainer = onTertiaryContainerDarkHighContrast,
        error = errorDarkHighContrast,
        onError = onErrorDarkHighContrast,
        errorContainer = errorContainerDarkHighContrast,
        onErrorContainer = onErrorContainerDarkHighContrast,
        background = backgroundDarkHighContrast,
        onBackground = onBackgroundDarkHighContrast,
        surface = surfaceDarkHighContrast,
        onSurface = onSurfaceDarkHighContrast,
        surfaceVariant = surfaceVariantDarkHighContrast,
        onSurfaceVariant = onSurfaceVariantDarkHighContrast,
        outline = outlineDarkHighContrast,
        outlineVariant = outlineVariantDarkHighContrast,
        scrim = scrimDarkHighContrast,
        inverseSurface = inverseSurfaceDarkHighContrast,
        inverseOnSurface = inverseOnSurfaceDarkHighContrast,
        inversePrimary = inversePrimaryDarkHighContrast,
        surfaceDim = surfaceDimDarkHighContrast,
        surfaceBright = surfaceBrightDarkHighContrast,
        surfaceContainerLowest = surfaceContainerLowestDarkHighContrast,
        surfaceContainerLow = surfaceContainerLowDarkHighContrast,
        surfaceContainer = surfaceContainerDarkHighContrast,
        surfaceContainerHigh = surfaceContainerHighDarkHighContrast,
        surfaceContainerHighest = surfaceContainerHighestDarkHighContrast,
    )

    val unspecified_scheme = ColorFamily(
        Color.Unspecified, Color.Unspecified, Color.Unspecified, Color.Unspecified
    )

}