package io.nekohasekai.sagernet.compose.theme

import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color

/** 酸柠舒畅 */
object Lime {
    val primaryLight = Color(0xFF5B6300)
    val onPrimaryLight = Color(0xFFFFFFFF)
    val primaryContainerLight = Color(0xFFCDDC39)
    val onPrimaryContainerLight = Color(0xFF575F00)
    val secondaryLight = Color(0xFF5B6300)
    val onSecondaryLight = Color(0xFFFFFFFF)
    val secondaryContainerLight = Color(0xFFEEFF41)
    val onSecondaryContainerLight = Color(0xFF6C7500)
    val tertiaryLight = Color(0xFF695F00)
    val onTertiaryLight = Color(0xFFFFFFFF)
    val tertiaryContainerLight = Color(0xFFFFEB3B)
    val onTertiaryContainerLight = Color(0xFF746900)
    val errorLight = Color(0xFFBA1A1A)
    val onErrorLight = Color(0xFFFFFFFF)
    val errorContainerLight = Color(0xFFFFDAD6)
    val onErrorContainerLight = Color(0xFF93000A)
    val backgroundLight = Color(0xFFFCFAE8)
    val onBackgroundLight = Color(0xFF1B1C12)
    val surfaceLight = Color(0xFFFCFAE8)
    val onSurfaceLight = Color(0xFF1B1C12)
    val surfaceVariantLight = Color(0xFFE4E4CA)
    val onSurfaceVariantLight = Color(0xFF474835)
    val outlineLight = Color(0xFF787963)
    val outlineVariantLight = Color(0xFFC8C8AF)
    val scrimLight = Color(0xFF000000)
    val inverseSurfaceLight = Color(0xFF313126)
    val inverseOnSurfaceLight = Color(0xFFF3F1E0)
    val inversePrimaryLight = Color(0xFFC1D02C)
    val surfaceDimLight = Color(0xFFDCDBCA)
    val surfaceBrightLight = Color(0xFFFCFAE8)
    val surfaceContainerLowestLight = Color(0xFFFFFFFF)
    val surfaceContainerLowLight = Color(0xFFF6F4E3)
    val surfaceContainerLight = Color(0xFFF0EFDD)
    val surfaceContainerHighLight = Color(0xFFEAE9D8)
    val surfaceContainerHighestLight = Color(0xFFE5E3D2)

    val primaryLightMediumContrast = Color(0xFF343900)
    val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
    val primaryContainerLightMediumContrast = Color(0xFF6A7300)
    val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
    val secondaryLightMediumContrast = Color(0xFF343900)
    val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
    val secondaryContainerLightMediumContrast = Color(0xFF6A7300)
    val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
    val tertiaryLightMediumContrast = Color(0xFF3D3700)
    val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
    val tertiaryContainerLightMediumContrast = Color(0xFF796E00)
    val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
    val errorLightMediumContrast = Color(0xFF740006)
    val onErrorLightMediumContrast = Color(0xFFFFFFFF)
    val errorContainerLightMediumContrast = Color(0xFFCF2C27)
    val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
    val backgroundLightMediumContrast = Color(0xFFFCFAE8)
    val onBackgroundLightMediumContrast = Color(0xFF1B1C12)
    val surfaceLightMediumContrast = Color(0xFFFCFAE8)
    val onSurfaceLightMediumContrast = Color(0xFF111208)
    val surfaceVariantLightMediumContrast = Color(0xFFE4E4CA)
    val onSurfaceVariantLightMediumContrast = Color(0xFF363725)
    val outlineLightMediumContrast = Color(0xFF535440)
    val outlineVariantLightMediumContrast = Color(0xFF6D6F59)
    val scrimLightMediumContrast = Color(0xFF000000)
    val inverseSurfaceLightMediumContrast = Color(0xFF313126)
    val inverseOnSurfaceLightMediumContrast = Color(0xFFF3F1E0)
    val inversePrimaryLightMediumContrast = Color(0xFFC1D02C)
    val surfaceDimLightMediumContrast = Color(0xFFC8C7B7)
    val surfaceBrightLightMediumContrast = Color(0xFFFCFAE8)
    val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
    val surfaceContainerLowLightMediumContrast = Color(0xFFF6F4E3)
    val surfaceContainerLightMediumContrast = Color(0xFFEAE9D8)
    val surfaceContainerHighLightMediumContrast = Color(0xFFDFDECD)
    val surfaceContainerHighestLightMediumContrast = Color(0xFFD4D2C2)

    val primaryLightHighContrast = Color(0xFF2A2F00)
    val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
    val primaryContainerLightHighContrast = Color(0xFF474D00)
    val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
    val secondaryLightHighContrast = Color(0xFF2B2F00)
    val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
    val secondaryContainerLightHighContrast = Color(0xFF474D00)
    val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
    val tertiaryLightHighContrast = Color(0xFF322D00)
    val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
    val tertiaryContainerLightHighContrast = Color(0xFF524A00)
    val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
    val errorLightHighContrast = Color(0xFF600004)
    val onErrorLightHighContrast = Color(0xFFFFFFFF)
    val errorContainerLightHighContrast = Color(0xFF98000A)
    val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
    val backgroundLightHighContrast = Color(0xFFFCFAE8)
    val onBackgroundLightHighContrast = Color(0xFF1B1C12)
    val surfaceLightHighContrast = Color(0xFFFCFAE8)
    val onSurfaceLightHighContrast = Color(0xFF000000)
    val surfaceVariantLightHighContrast = Color(0xFFE4E4CA)
    val onSurfaceVariantLightHighContrast = Color(0xFF000000)
    val outlineLightHighContrast = Color(0xFF2C2D1C)
    val outlineVariantLightHighContrast = Color(0xFF494B37)
    val scrimLightHighContrast = Color(0xFF000000)
    val inverseSurfaceLightHighContrast = Color(0xFF313126)
    val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
    val inversePrimaryLightHighContrast = Color(0xFFC1D02C)
    val surfaceDimLightHighContrast = Color(0xFFBABAA9)
    val surfaceBrightLightHighContrast = Color(0xFFFCFAE8)
    val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
    val surfaceContainerLowLightHighContrast = Color(0xFFF3F1E0)
    val surfaceContainerLightHighContrast = Color(0xFFE5E3D2)
    val surfaceContainerHighLightHighContrast = Color(0xFFD6D5C4)
    val surfaceContainerHighestLightHighContrast = Color(0xFFC8C7B7)

    val primaryDark = Color(0xFFE9F954)
    val onPrimaryDark = Color(0xFF2F3300)
    val primaryContainerDark = Color(0xFFCDDC39)
    val onPrimaryContainerDark = Color(0xFF575F00)
    val secondaryDark = Color(0xFFFFFFFF)
    val onSecondaryDark = Color(0xFF2F3300)
    val secondaryContainerDark = Color(0xFFDDED2E)
    val onSecondaryContainerDark = Color(0xFF616A00)
    val tertiaryDark = Color(0xFFFFFFFF)
    val onTertiaryDark = Color(0xFF363100)
    val tertiaryContainerDark = Color(0xFFF9E534)
    val onTertiaryContainerDark = Color(0xFF706500)
    val errorDark = Color(0xFFFFB4AB)
    val onErrorDark = Color(0xFF690005)
    val errorContainerDark = Color(0xFF93000A)
    val onErrorContainerDark = Color(0xFFFFDAD6)
    val backgroundDark = Color(0xFF13140A)
    val onBackgroundDark = Color(0xFFE5E3D2)
    val surfaceDark = Color(0xFF13140A)
    val onSurfaceDark = Color(0xFFE5E3D2)
    val surfaceVariantDark = Color(0xFF474835)
    val onSurfaceVariantDark = Color(0xFFC8C8AF)
    val outlineDark = Color(0xFF91927B)
    val outlineVariantDark = Color(0xFF474835)
    val scrimDark = Color(0xFF000000)
    val inverseSurfaceDark = Color(0xFFE5E3D2)
    val inverseOnSurfaceDark = Color(0xFF313126)
    val inversePrimaryDark = Color(0xFF5B6300)
    val surfaceDimDark = Color(0xFF13140A)
    val surfaceBrightDark = Color(0xFF393A2E)
    val surfaceContainerLowestDark = Color(0xFF0E0F06)
    val surfaceContainerLowDark = Color(0xFF1B1C12)
    val surfaceContainerDark = Color(0xFF202016)
    val surfaceContainerHighDark = Color(0xFF2A2B20)
    val surfaceContainerHighestDark = Color(0xFF35362A)

    val primaryDarkMediumContrast = Color(0xFFE9F954)
    val onPrimaryDarkMediumContrast = Color(0xFF2F3300)
    val primaryContainerDarkMediumContrast = Color(0xFFCDDC39)
    val onPrimaryContainerDarkMediumContrast = Color(0xFF3C4100)
    val secondaryDarkMediumContrast = Color(0xFFFFFFFF)
    val onSecondaryDarkMediumContrast = Color(0xFF2F3300)
    val secondaryContainerDarkMediumContrast = Color(0xFFDDED2E)
    val onSecondaryContainerDarkMediumContrast = Color(0xFF464C00)
    val tertiaryDarkMediumContrast = Color(0xFFFFFFFF)
    val onTertiaryDarkMediumContrast = Color(0xFF363100)
    val tertiaryContainerDarkMediumContrast = Color(0xFFF9E534)
    val onTertiaryContainerDarkMediumContrast = Color(0xFF504900)
    val errorDarkMediumContrast = Color(0xFFFFD2CC)
    val onErrorDarkMediumContrast = Color(0xFF540003)
    val errorContainerDarkMediumContrast = Color(0xFFFF5449)
    val onErrorContainerDarkMediumContrast = Color(0xFF000000)
    val backgroundDarkMediumContrast = Color(0xFF13140A)
    val onBackgroundDarkMediumContrast = Color(0xFFE5E3D2)
    val surfaceDarkMediumContrast = Color(0xFF13140A)
    val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
    val surfaceVariantDarkMediumContrast = Color(0xFF474835)
    val onSurfaceVariantDarkMediumContrast = Color(0xFFDEDEC4)
    val outlineDarkMediumContrast = Color(0xFFB3B39B)
    val outlineVariantDarkMediumContrast = Color(0xFF91927B)
    val scrimDarkMediumContrast = Color(0xFF000000)
    val inverseSurfaceDarkMediumContrast = Color(0xFFE5E3D2)
    val inverseOnSurfaceDarkMediumContrast = Color(0xFF2A2B20)
    val inversePrimaryDarkMediumContrast = Color(0xFF464C00)
    val surfaceDimDarkMediumContrast = Color(0xFF13140A)
    val surfaceBrightDarkMediumContrast = Color(0xFF454539)
    val surfaceContainerLowestDarkMediumContrast = Color(0xFF070802)
    val surfaceContainerLowDarkMediumContrast = Color(0xFF1E1E14)
    val surfaceContainerDarkMediumContrast = Color(0xFF28291E)
    val surfaceContainerHighDarkMediumContrast = Color(0xFF333328)
    val surfaceContainerHighestDarkMediumContrast = Color(0xFF3E3E32)

    val primaryDarkHighContrast = Color(0xFFEBFB56)
    val onPrimaryDarkHighContrast = Color(0xFF000000)
    val primaryContainerDarkHighContrast = Color(0xFFCDDC39)
    val onPrimaryContainerDarkHighContrast = Color(0xFF1C2000)
    val secondaryDarkHighContrast = Color(0xFFFFFFFF)
    val onSecondaryDarkHighContrast = Color(0xFF000000)
    val secondaryContainerDarkHighContrast = Color(0xFFDDED2E)
    val onSecondaryContainerDarkHighContrast = Color(0xFF282D00)
    val tertiaryDarkHighContrast = Color(0xFFFFFFFF)
    val onTertiaryDarkHighContrast = Color(0xFF000000)
    val tertiaryContainerDarkHighContrast = Color(0xFFF9E534)
    val onTertiaryContainerDarkHighContrast = Color(0xFF2F2B00)
    val errorDarkHighContrast = Color(0xFFFFECE9)
    val onErrorDarkHighContrast = Color(0xFF000000)
    val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
    val onErrorContainerDarkHighContrast = Color(0xFF220001)
    val backgroundDarkHighContrast = Color(0xFF13140A)
    val onBackgroundDarkHighContrast = Color(0xFFE5E3D2)
    val surfaceDarkHighContrast = Color(0xFF13140A)
    val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
    val surfaceVariantDarkHighContrast = Color(0xFF474835)
    val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
    val outlineDarkHighContrast = Color(0xFFF2F2D7)
    val outlineVariantDarkHighContrast = Color(0xFFC4C4AB)
    val scrimDarkHighContrast = Color(0xFF000000)
    val inverseSurfaceDarkHighContrast = Color(0xFFE5E3D2)
    val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
    val inversePrimaryDarkHighContrast = Color(0xFF464C00)
    val surfaceDimDarkHighContrast = Color(0xFF13140A)
    val surfaceBrightDarkHighContrast = Color(0xFF505144)
    val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
    val surfaceContainerLowDarkHighContrast = Color(0xFF202016)
    val surfaceContainerDarkHighContrast = Color(0xFF313126)
    val surfaceContainerHighDarkHighContrast = Color(0xFF3C3C30)
    val surfaceContainerHighestDarkHighContrast = Color(0xFF47483B)

    internal val lightScheme = lightColorScheme(
        primary = primaryLight,
        onPrimary = onPrimaryLight,
        primaryContainer = primaryContainerLight,
        onPrimaryContainer = onPrimaryContainerLight,
        secondary = secondaryLight,
        onSecondary = onSecondaryLight,
        secondaryContainer = secondaryContainerLight,
        onSecondaryContainer = onSecondaryContainerLight,
        tertiary = tertiaryLight,
        onTertiary = onTertiaryLight,
        tertiaryContainer = tertiaryContainerLight,
        onTertiaryContainer = onTertiaryContainerLight,
        error = errorLight,
        onError = onErrorLight,
        errorContainer = errorContainerLight,
        onErrorContainer = onErrorContainerLight,
        background = backgroundLight,
        onBackground = onBackgroundLight,
        surface = surfaceLight,
        onSurface = onSurfaceLight,
        surfaceVariant = surfaceVariantLight,
        onSurfaceVariant = onSurfaceVariantLight,
        outline = outlineLight,
        outlineVariant = outlineVariantLight,
        scrim = scrimLight,
        inverseSurface = inverseSurfaceLight,
        inverseOnSurface = inverseOnSurfaceLight,
        inversePrimary = inversePrimaryLight,
        surfaceDim = surfaceDimLight,
        surfaceBright = surfaceBrightLight,
        surfaceContainerLowest = surfaceContainerLowestLight,
        surfaceContainerLow = surfaceContainerLowLight,
        surfaceContainer = surfaceContainerLight,
        surfaceContainerHigh = surfaceContainerHighLight,
        surfaceContainerHighest = surfaceContainerHighestLight,
    )

    internal val darkScheme = darkColorScheme(
        primary = primaryDark,
        onPrimary = onPrimaryDark,
        primaryContainer = primaryContainerDark,
        onPrimaryContainer = onPrimaryContainerDark,
        secondary = secondaryDark,
        onSecondary = onSecondaryDark,
        secondaryContainer = secondaryContainerDark,
        onSecondaryContainer = onSecondaryContainerDark,
        tertiary = tertiaryDark,
        onTertiary = onTertiaryDark,
        tertiaryContainer = tertiaryContainerDark,
        onTertiaryContainer = onTertiaryContainerDark,
        error = errorDark,
        onError = onErrorDark,
        errorContainer = errorContainerDark,
        onErrorContainer = onErrorContainerDark,
        background = backgroundDark,
        onBackground = onBackgroundDark,
        surface = surfaceDark,
        onSurface = onSurfaceDark,
        surfaceVariant = surfaceVariantDark,
        onSurfaceVariant = onSurfaceVariantDark,
        outline = outlineDark,
        outlineVariant = outlineVariantDark,
        scrim = scrimDark,
        inverseSurface = inverseSurfaceDark,
        inverseOnSurface = inverseOnSurfaceDark,
        inversePrimary = inversePrimaryDark,
        surfaceDim = surfaceDimDark,
        surfaceBright = surfaceBrightDark,
        surfaceContainerLowest = surfaceContainerLowestDark,
        surfaceContainerLow = surfaceContainerLowDark,
        surfaceContainer = surfaceContainerDark,
        surfaceContainerHigh = surfaceContainerHighDark,
        surfaceContainerHighest = surfaceContainerHighestDark,
    )

    private val mediumContrastLightColorScheme = lightColorScheme(
        primary = primaryLightMediumContrast,
        onPrimary = onPrimaryLightMediumContrast,
        primaryContainer = primaryContainerLightMediumContrast,
        onPrimaryContainer = onPrimaryContainerLightMediumContrast,
        secondary = secondaryLightMediumContrast,
        onSecondary = onSecondaryLightMediumContrast,
        secondaryContainer = secondaryContainerLightMediumContrast,
        onSecondaryContainer = onSecondaryContainerLightMediumContrast,
        tertiary = tertiaryLightMediumContrast,
        onTertiary = onTertiaryLightMediumContrast,
        tertiaryContainer = tertiaryContainerLightMediumContrast,
        onTertiaryContainer = onTertiaryContainerLightMediumContrast,
        error = errorLightMediumContrast,
        onError = onErrorLightMediumContrast,
        errorContainer = errorContainerLightMediumContrast,
        onErrorContainer = onErrorContainerLightMediumContrast,
        background = backgroundLightMediumContrast,
        onBackground = onBackgroundLightMediumContrast,
        surface = surfaceLightMediumContrast,
        onSurface = onSurfaceLightMediumContrast,
        surfaceVariant = surfaceVariantLightMediumContrast,
        onSurfaceVariant = onSurfaceVariantLightMediumContrast,
        outline = outlineLightMediumContrast,
        outlineVariant = outlineVariantLightMediumContrast,
        scrim = scrimLightMediumContrast,
        inverseSurface = inverseSurfaceLightMediumContrast,
        inverseOnSurface = inverseOnSurfaceLightMediumContrast,
        inversePrimary = inversePrimaryLightMediumContrast,
        surfaceDim = surfaceDimLightMediumContrast,
        surfaceBright = surfaceBrightLightMediumContrast,
        surfaceContainerLowest = surfaceContainerLowestLightMediumContrast,
        surfaceContainerLow = surfaceContainerLowLightMediumContrast,
        surfaceContainer = surfaceContainerLightMediumContrast,
        surfaceContainerHigh = surfaceContainerHighLightMediumContrast,
        surfaceContainerHighest = surfaceContainerHighestLightMediumContrast,
    )

    private val highContrastLightColorScheme = lightColorScheme(
        primary = primaryLightHighContrast,
        onPrimary = onPrimaryLightHighContrast,
        primaryContainer = primaryContainerLightHighContrast,
        onPrimaryContainer = onPrimaryContainerLightHighContrast,
        secondary = secondaryLightHighContrast,
        onSecondary = onSecondaryLightHighContrast,
        secondaryContainer = secondaryContainerLightHighContrast,
        onSecondaryContainer = onSecondaryContainerLightHighContrast,
        tertiary = tertiaryLightHighContrast,
        onTertiary = onTertiaryLightHighContrast,
        tertiaryContainer = tertiaryContainerLightHighContrast,
        onTertiaryContainer = onTertiaryContainerLightHighContrast,
        error = errorLightHighContrast,
        onError = onErrorLightHighContrast,
        errorContainer = errorContainerLightHighContrast,
        onErrorContainer = onErrorContainerLightHighContrast,
        background = backgroundLightHighContrast,
        onBackground = onBackgroundLightHighContrast,
        surface = surfaceLightHighContrast,
        onSurface = onSurfaceLightHighContrast,
        surfaceVariant = surfaceVariantLightHighContrast,
        onSurfaceVariant = onSurfaceVariantLightHighContrast,
        outline = outlineLightHighContrast,
        outlineVariant = outlineVariantLightHighContrast,
        scrim = scrimLightHighContrast,
        inverseSurface = inverseSurfaceLightHighContrast,
        inverseOnSurface = inverseOnSurfaceLightHighContrast,
        inversePrimary = inversePrimaryLightHighContrast,
        surfaceDim = surfaceDimLightHighContrast,
        surfaceBright = surfaceBrightLightHighContrast,
        surfaceContainerLowest = surfaceContainerLowestLightHighContrast,
        surfaceContainerLow = surfaceContainerLowLightHighContrast,
        surfaceContainer = surfaceContainerLightHighContrast,
        surfaceContainerHigh = surfaceContainerHighLightHighContrast,
        surfaceContainerHighest = surfaceContainerHighestLightHighContrast,
    )

    private val mediumContrastDarkColorScheme = darkColorScheme(
        primary = primaryDarkMediumContrast,
        onPrimary = onPrimaryDarkMediumContrast,
        primaryContainer = primaryContainerDarkMediumContrast,
        onPrimaryContainer = onPrimaryContainerDarkMediumContrast,
        secondary = secondaryDarkMediumContrast,
        onSecondary = onSecondaryDarkMediumContrast,
        secondaryContainer = secondaryContainerDarkMediumContrast,
        onSecondaryContainer = onSecondaryContainerDarkMediumContrast,
        tertiary = tertiaryDarkMediumContrast,
        onTertiary = onTertiaryDarkMediumContrast,
        tertiaryContainer = tertiaryContainerDarkMediumContrast,
        onTertiaryContainer = onTertiaryContainerDarkMediumContrast,
        error = errorDarkMediumContrast,
        onError = onErrorDarkMediumContrast,
        errorContainer = errorContainerDarkMediumContrast,
        onErrorContainer = onErrorContainerDarkMediumContrast,
        background = backgroundDarkMediumContrast,
        onBackground = onBackgroundDarkMediumContrast,
        surface = surfaceDarkMediumContrast,
        onSurface = onSurfaceDarkMediumContrast,
        surfaceVariant = surfaceVariantDarkMediumContrast,
        onSurfaceVariant = onSurfaceVariantDarkMediumContrast,
        outline = outlineDarkMediumContrast,
        outlineVariant = outlineVariantDarkMediumContrast,
        scrim = scrimDarkMediumContrast,
        inverseSurface = inverseSurfaceDarkMediumContrast,
        inverseOnSurface = inverseOnSurfaceDarkMediumContrast,
        inversePrimary = inversePrimaryDarkMediumContrast,
        surfaceDim = surfaceDimDarkMediumContrast,
        surfaceBright = surfaceBrightDarkMediumContrast,
        surfaceContainerLowest = surfaceContainerLowestDarkMediumContrast,
        surfaceContainerLow = surfaceContainerLowDarkMediumContrast,
        surfaceContainer = surfaceContainerDarkMediumContrast,
        surfaceContainerHigh = surfaceContainerHighDarkMediumContrast,
        surfaceContainerHighest = surfaceContainerHighestDarkMediumContrast,
    )

    private val highContrastDarkColorScheme = darkColorScheme(
        primary = primaryDarkHighContrast,
        onPrimary = onPrimaryDarkHighContrast,
        primaryContainer = primaryContainerDarkHighContrast,
        onPrimaryContainer = onPrimaryContainerDarkHighContrast,
        secondary = secondaryDarkHighContrast,
        onSecondary = onSecondaryDarkHighContrast,
        secondaryContainer = secondaryContainerDarkHighContrast,
        onSecondaryContainer = onSecondaryContainerDarkHighContrast,
        tertiary = tertiaryDarkHighContrast,
        onTertiary = onTertiaryDarkHighContrast,
        tertiaryContainer = tertiaryContainerDarkHighContrast,
        onTertiaryContainer = onTertiaryContainerDarkHighContrast,
        error = errorDarkHighContrast,
        onError = onErrorDarkHighContrast,
        errorContainer = errorContainerDarkHighContrast,
        onErrorContainer = onErrorContainerDarkHighContrast,
        background = backgroundDarkHighContrast,
        onBackground = onBackgroundDarkHighContrast,
        surface = surfaceDarkHighContrast,
        onSurface = onSurfaceDarkHighContrast,
        surfaceVariant = surfaceVariantDarkHighContrast,
        onSurfaceVariant = onSurfaceVariantDarkHighContrast,
        outline = outlineDarkHighContrast,
        outlineVariant = outlineVariantDarkHighContrast,
        scrim = scrimDarkHighContrast,
        inverseSurface = inverseSurfaceDarkHighContrast,
        inverseOnSurface = inverseOnSurfaceDarkHighContrast,
        inversePrimary = inversePrimaryDarkHighContrast,
        surfaceDim = surfaceDimDarkHighContrast,
        surfaceBright = surfaceBrightDarkHighContrast,
        surfaceContainerLowest = surfaceContainerLowestDarkHighContrast,
        surfaceContainerLow = surfaceContainerLowDarkHighContrast,
        surfaceContainer = surfaceContainerDarkHighContrast,
        surfaceContainerHigh = surfaceContainerHighDarkHighContrast,
        surfaceContainerHighest = surfaceContainerHighestDarkHighContrast,
    )

    val unspecified_scheme = ColorFamily(
        Color.Unspecified, Color.Unspecified, Color.Unspecified, Color.Unspecified
    )

}