package io.nekohasekai.sagernet.compose.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

/** 铁血丹心 */
object Red {
    val primaryLight = Color(0xFFB81311)
    val onPrimaryLight = Color(0xFFFFFFFF)
    val primaryContainerLight = Color(0xFFDC3128)
    val onPrimaryContainerLight = Color(0xFFFFFBFF)
    val secondaryLight = Color(0xFFB51925)
    val onSecondaryLight = Color(0xFFFFFFFF)
    val secondaryContainerLight = Color(0xFFD8363A)
    val onSecondaryContainerLight = Color(0xFFFFFBFF)
    val tertiaryLight = Color(0xFFB80049)
    val onTertiaryLight = Color(0xFFFFFFFF)
    val tertiaryContainerLight = Color(0xFFE2165F)
    val onTertiaryContainerLight = Color(0xFFFFFBFF)
    val errorLight = Color(0xFFBA1A1A)
    val onErrorLight = Color(0xFFFFFFFF)
    val errorContainerLight = Color(0xFFFFDAD6)
    val onErrorContainerLight = Color(0xFF93000A)
    val backgroundLight = Color(0xFFFFF8F7)
    val onBackgroundLight = Color(0xFF281715)
    val surfaceLight = Color(0xFFFFF8F7)
    val onSurfaceLight = Color(0xFF281715)
    val surfaceVariantLight = Color(0xFFFFDAD5)
    val onSurfaceVariantLight = Color(0xFF5C403C)
    val outlineLight = Color(0xFF906F6B)
    val outlineVariantLight = Color(0xFFE5BDB8)
    val scrimLight = Color(0xFF000000)
    val inverseSurfaceLight = Color(0xFF3E2C29)
    val inverseOnSurfaceLight = Color(0xFFFFEDEA)
    val inversePrimaryLight = Color(0xFFFFB4A9)
    val surfaceDimLight = Color(0xFFF2D3CF)
    val surfaceBrightLight = Color(0xFFFFF8F7)
    val surfaceContainerLowestLight = Color(0xFFFFFFFF)
    val surfaceContainerLowLight = Color(0xFFFFF0EE)
    val surfaceContainerLight = Color(0xFFFFE9E6)
    val surfaceContainerHighLight = Color(0xFFFFE2DD)
    val surfaceContainerHighestLight = Color(0xFFFADCD7)

    val primaryLightMediumContrast = Color(0xFF740003)
    val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
    val primaryContainerLightMediumContrast = Color(0xFFD12921)
    val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
    val secondaryLightMediumContrast = Color(0xFF73000E)
    val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
    val secondaryContainerLightMediumContrast = Color(0xFFCE2E33)
    val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
    val tertiaryLightMediumContrast = Color(0xFF71002A)
    val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
    val tertiaryContainerLightMediumContrast = Color(0xFFD70357)
    val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
    val errorLightMediumContrast = Color(0xFF740006)
    val onErrorLightMediumContrast = Color(0xFFFFFFFF)
    val errorContainerLightMediumContrast = Color(0xFFCF2C27)
    val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
    val backgroundLightMediumContrast = Color(0xFFFFF8F7)
    val onBackgroundLightMediumContrast = Color(0xFF281715)
    val surfaceLightMediumContrast = Color(0xFFFFF8F7)
    val onSurfaceLightMediumContrast = Color(0xFF1C0D0B)
    val surfaceVariantLightMediumContrast = Color(0xFFFFDAD5)
    val onSurfaceVariantLightMediumContrast = Color(0xFF49302C)
    val outlineLightMediumContrast = Color(0xFF694B47)
    val outlineVariantLightMediumContrast = Color(0xFF856561)
    val scrimLightMediumContrast = Color(0xFF000000)
    val inverseSurfaceLightMediumContrast = Color(0xFF3E2C29)
    val inverseOnSurfaceLightMediumContrast = Color(0xFFFFEDEA)
    val inversePrimaryLightMediumContrast = Color(0xFFFFB4A9)
    val surfaceDimLightMediumContrast = Color(0xFFDDC0BC)
    val surfaceBrightLightMediumContrast = Color(0xFFFFF8F7)
    val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
    val surfaceContainerLowLightMediumContrast = Color(0xFFFFF0EE)
    val surfaceContainerLightMediumContrast = Color(0xFFFFE2DD)
    val surfaceContainerHighLightMediumContrast = Color(0xFFF4D6D2)
    val surfaceContainerHighestLightMediumContrast = Color(0xFFE9CBC7)

    val primaryLightHighContrast = Color(0xFF610002)
    val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
    val primaryContainerLightHighContrast = Color(0xFF980006)
    val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
    val secondaryLightHighContrast = Color(0xFF60000A)
    val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
    val secondaryContainerLightHighContrast = Color(0xFF970016)
    val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
    val tertiaryLightHighContrast = Color(0xFF5F0022)
    val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
    val tertiaryContainerLightHighContrast = Color(0xFF95003A)
    val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
    val errorLightHighContrast = Color(0xFF600004)
    val onErrorLightHighContrast = Color(0xFFFFFFFF)
    val errorContainerLightHighContrast = Color(0xFF98000A)
    val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
    val backgroundLightHighContrast = Color(0xFFFFF8F7)
    val onBackgroundLightHighContrast = Color(0xFF281715)
    val surfaceLightHighContrast = Color(0xFFFFF8F7)
    val onSurfaceLightHighContrast = Color(0xFF000000)
    val surfaceVariantLightHighContrast = Color(0xFFFFDAD5)
    val onSurfaceVariantLightHighContrast = Color(0xFF000000)
    val outlineLightHighContrast = Color(0xFF3E2623)
    val outlineVariantLightHighContrast = Color(0xFF5E423E)
    val scrimLightHighContrast = Color(0xFF000000)
    val inverseSurfaceLightHighContrast = Color(0xFF3E2C29)
    val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
    val inversePrimaryLightHighContrast = Color(0xFFFFB4A9)
    val surfaceDimLightHighContrast = Color(0xFFCFB2AE)
    val surfaceBrightLightHighContrast = Color(0xFFFFF8F7)
    val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
    val surfaceContainerLowLightHighContrast = Color(0xFFFFEDEA)
    val surfaceContainerLightHighContrast = Color(0xFFFADCD7)
    val surfaceContainerHighLightHighContrast = Color(0xFFECCEC9)
    val surfaceContainerHighestLightHighContrast = Color(0xFFDDC0BC)

    val primaryDark = Color(0xFFFFB4A9)
    val onPrimaryDark = Color(0xFF690002)
    val primaryContainerDark = Color(0xFFFF5545)
    val onPrimaryContainerDark = Color(0xFF450001)
    val secondaryDark = Color(0xFFFFB3AE)
    val onSecondaryDark = Color(0xFF68000C)
    val secondaryContainerDark = Color(0xFFFF5353)
    val onSecondaryContainerDark = Color(0xFF5B0009)
    val tertiaryDark = Color(0xFFFFB2BE)
    val onTertiaryDark = Color(0xFF660025)
    val tertiaryContainerDark = Color(0xFFFF4E7C)
    val onTertiaryContainerDark = Color(0xFF200007)
    val errorDark = Color(0xFFFFB4AB)
    val onErrorDark = Color(0xFF690005)
    val errorContainerDark = Color(0xFF93000A)
    val onErrorContainerDark = Color(0xFFFFDAD6)
    val backgroundDark = Color(0xFF1E0F0D)
    val onBackgroundDark = Color(0xFFFADCD7)
    val surfaceDark = Color(0xFF1E0F0D)
    val onSurfaceDark = Color(0xFFFADCD7)
    val surfaceVariantDark = Color(0xFF5C403C)
    val onSurfaceVariantDark = Color(0xFFE5BDB8)
    val outlineDark = Color(0xFFAC8884)
    val outlineVariantDark = Color(0xFF5C403C)
    val scrimDark = Color(0xFF000000)
    val inverseSurfaceDark = Color(0xFFFADCD7)
    val inverseOnSurfaceDark = Color(0xFF3E2C29)
    val inversePrimaryDark = Color(0xFFBB1614)
    val surfaceDimDark = Color(0xFF1E0F0D)
    val surfaceBrightDark = Color(0xFF483432)
    val surfaceContainerLowestDark = Color(0xFF190A08)
    val surfaceContainerLowDark = Color(0xFF281715)
    val surfaceContainerDark = Color(0xFF2C1B19)
    val surfaceContainerHighDark = Color(0xFF372623)
    val surfaceContainerHighestDark = Color(0xFF43302D)

    val primaryDarkMediumContrast = Color(0xFFFFD2CC)
    val onPrimaryDarkMediumContrast = Color(0xFF540002)
    val primaryContainerDarkMediumContrast = Color(0xFFFF5545)
    val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
    val secondaryDarkMediumContrast = Color(0xFFFFD2CE)
    val onSecondaryDarkMediumContrast = Color(0xFF540008)
    val secondaryContainerDarkMediumContrast = Color(0xFFFF5353)
    val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
    val tertiaryDarkMediumContrast = Color(0xFFFFD1D7)
    val onTertiaryDarkMediumContrast = Color(0xFF52001C)
    val tertiaryContainerDarkMediumContrast = Color(0xFFFF4E7C)
    val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
    val errorDarkMediumContrast = Color(0xFFFFD2CC)
    val onErrorDarkMediumContrast = Color(0xFF540003)
    val errorContainerDarkMediumContrast = Color(0xFFFF5449)
    val onErrorContainerDarkMediumContrast = Color(0xFF000000)
    val backgroundDarkMediumContrast = Color(0xFF1E0F0D)
    val onBackgroundDarkMediumContrast = Color(0xFFFADCD7)
    val surfaceDarkMediumContrast = Color(0xFF1E0F0D)
    val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
    val surfaceVariantDarkMediumContrast = Color(0xFF5C403C)
    val onSurfaceVariantDarkMediumContrast = Color(0xFFFCD3CD)
    val outlineDarkMediumContrast = Color(0xFFCFA9A4)
    val outlineVariantDarkMediumContrast = Color(0xFFAB8883)
    val scrimDarkMediumContrast = Color(0xFF000000)
    val inverseSurfaceDarkMediumContrast = Color(0xFFFADCD7)
    val inverseOnSurfaceDarkMediumContrast = Color(0xFF382623)
    val inversePrimaryDarkMediumContrast = Color(0xFF950005)
    val surfaceDimDarkMediumContrast = Color(0xFF1E0F0D)
    val surfaceBrightDarkMediumContrast = Color(0xFF54403D)
    val surfaceContainerLowestDarkMediumContrast = Color(0xFF100504)
    val surfaceContainerLowDarkMediumContrast = Color(0xFF2A1917)
    val surfaceContainerDarkMediumContrast = Color(0xFF352321)
    val surfaceContainerHighDarkMediumContrast = Color(0xFF412E2B)
    val surfaceContainerHighestDarkMediumContrast = Color(0xFF4D3936)

    val primaryDarkHighContrast = Color(0xFFFFECE9)
    val onPrimaryDarkHighContrast = Color(0xFF000000)
    val primaryContainerDarkHighContrast = Color(0xFFFFAEA3)
    val onPrimaryContainerDarkHighContrast = Color(0xFF220000)
    val secondaryDarkHighContrast = Color(0xFFFFECEA)
    val onSecondaryDarkHighContrast = Color(0xFF000000)
    val secondaryContainerDarkHighContrast = Color(0xFFFFAEA8)
    val onSecondaryContainerDarkHighContrast = Color(0xFF220001)
    val tertiaryDarkHighContrast = Color(0xFFFFEBED)
    val onTertiaryDarkHighContrast = Color(0xFF000000)
    val tertiaryContainerDarkHighContrast = Color(0xFFFFACB9)
    val onTertiaryContainerDarkHighContrast = Color(0xFF200007)
    val errorDarkHighContrast = Color(0xFFFFECE9)
    val onErrorDarkHighContrast = Color(0xFF000000)
    val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
    val onErrorContainerDarkHighContrast = Color(0xFF220001)
    val backgroundDarkHighContrast = Color(0xFF1E0F0D)
    val onBackgroundDarkHighContrast = Color(0xFFFADCD7)
    val surfaceDarkHighContrast = Color(0xFF1E0F0D)
    val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
    val surfaceVariantDarkHighContrast = Color(0xFF5C403C)
    val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
    val outlineDarkHighContrast = Color(0xFFFFECE9)
    val outlineVariantDarkHighContrast = Color(0xFFE1BAB4)
    val scrimDarkHighContrast = Color(0xFF000000)
    val inverseSurfaceDarkHighContrast = Color(0xFFFADCD7)
    val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
    val inversePrimaryDarkHighContrast = Color(0xFF950005)
    val surfaceDimDarkHighContrast = Color(0xFF1E0F0D)
    val surfaceBrightDarkHighContrast = Color(0xFF604B48)
    val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
    val surfaceContainerLowDarkHighContrast = Color(0xFF2C1B19)
    val surfaceContainerDarkHighContrast = Color(0xFF3E2C29)
    val surfaceContainerHighDarkHighContrast = Color(0xFF4A3734)
    val surfaceContainerHighestDarkHighContrast = Color(0xFF57423F)

    internal val lightScheme = lightColorScheme(
        primary = primaryLight,
        onPrimary = onPrimaryLight,
        primaryContainer = primaryContainerLight,
        onPrimaryContainer = onPrimaryContainerLight,
        secondary = secondaryLight,
        onSecondary = onSecondaryLight,
        secondaryContainer = secondaryContainerLight,
        onSecondaryContainer = onSecondaryContainerLight,
        tertiary = tertiaryLight,
        onTertiary = onTertiaryLight,
        tertiaryContainer = tertiaryContainerLight,
        onTertiaryContainer = onTertiaryContainerLight,
        error = errorLight,
        onError = onErrorLight,
        errorContainer = errorContainerLight,
        onErrorContainer = onErrorContainerLight,
        background = backgroundLight,
        onBackground = onBackgroundLight,
        surface = surfaceLight,
        onSurface = onSurfaceLight,
        surfaceVariant = surfaceVariantLight,
        onSurfaceVariant = onSurfaceVariantLight,
        outline = outlineLight,
        outlineVariant = outlineVariantLight,
        scrim = scrimLight,
        inverseSurface = inverseSurfaceLight,
        inverseOnSurface = inverseOnSurfaceLight,
        inversePrimary = inversePrimaryLight,
        surfaceDim = surfaceDimLight,
        surfaceBright = surfaceBrightLight,
        surfaceContainerLowest = surfaceContainerLowestLight,
        surfaceContainerLow = surfaceContainerLowLight,
        surfaceContainer = surfaceContainerLight,
        surfaceContainerHigh = surfaceContainerHighLight,
        surfaceContainerHighest = surfaceContainerHighestLight,
    )

    internal val darkScheme = darkColorScheme(
        primary = primaryDark,
        onPrimary = onPrimaryDark,
        primaryContainer = primaryContainerDark,
        onPrimaryContainer = onPrimaryContainerDark,
        secondary = secondaryDark,
        onSecondary = onSecondaryDark,
        secondaryContainer = secondaryContainerDark,
        onSecondaryContainer = onSecondaryContainerDark,
        tertiary = tertiaryDark,
        onTertiary = onTertiaryDark,
        tertiaryContainer = tertiaryContainerDark,
        onTertiaryContainer = onTertiaryContainerDark,
        error = errorDark,
        onError = onErrorDark,
        errorContainer = errorContainerDark,
        onErrorContainer = onErrorContainerDark,
        background = backgroundDark,
        onBackground = onBackgroundDark,
        surface = surfaceDark,
        onSurface = onSurfaceDark,
        surfaceVariant = surfaceVariantDark,
        onSurfaceVariant = onSurfaceVariantDark,
        outline = outlineDark,
        outlineVariant = outlineVariantDark,
        scrim = scrimDark,
        inverseSurface = inverseSurfaceDark,
        inverseOnSurface = inverseOnSurfaceDark,
        inversePrimary = inversePrimaryDark,
        surfaceDim = surfaceDimDark,
        surfaceBright = surfaceBrightDark,
        surfaceContainerLowest = surfaceContainerLowestDark,
        surfaceContainerLow = surfaceContainerLowDark,
        surfaceContainer = surfaceContainerDark,
        surfaceContainerHigh = surfaceContainerHighDark,
        surfaceContainerHighest = surfaceContainerHighestDark,
    )

    private val mediumContrastLightColorScheme = lightColorScheme(
        primary = primaryLightMediumContrast,
        onPrimary = onPrimaryLightMediumContrast,
        primaryContainer = primaryContainerLightMediumContrast,
        onPrimaryContainer = onPrimaryContainerLightMediumContrast,
        secondary = secondaryLightMediumContrast,
        onSecondary = onSecondaryLightMediumContrast,
        secondaryContainer = secondaryContainerLightMediumContrast,
        onSecondaryContainer = onSecondaryContainerLightMediumContrast,
        tertiary = tertiaryLightMediumContrast,
        onTertiary = onTertiaryLightMediumContrast,
        tertiaryContainer = tertiaryContainerLightMediumContrast,
        onTertiaryContainer = onTertiaryContainerLightMediumContrast,
        error = errorLightMediumContrast,
        onError = onErrorLightMediumContrast,
        errorContainer = errorContainerLightMediumContrast,
        onErrorContainer = onErrorContainerLightMediumContrast,
        background = backgroundLightMediumContrast,
        onBackground = onBackgroundLightMediumContrast,
        surface = surfaceLightMediumContrast,
        onSurface = onSurfaceLightMediumContrast,
        surfaceVariant = surfaceVariantLightMediumContrast,
        onSurfaceVariant = onSurfaceVariantLightMediumContrast,
        outline = outlineLightMediumContrast,
        outlineVariant = outlineVariantLightMediumContrast,
        scrim = scrimLightMediumContrast,
        inverseSurface = inverseSurfaceLightMediumContrast,
        inverseOnSurface = inverseOnSurfaceLightMediumContrast,
        inversePrimary = inversePrimaryLightMediumContrast,
        surfaceDim = surfaceDimLightMediumContrast,
        surfaceBright = surfaceBrightLightMediumContrast,
        surfaceContainerLowest = surfaceContainerLowestLightMediumContrast,
        surfaceContainerLow = surfaceContainerLowLightMediumContrast,
        surfaceContainer = surfaceContainerLightMediumContrast,
        surfaceContainerHigh = surfaceContainerHighLightMediumContrast,
        surfaceContainerHighest = surfaceContainerHighestLightMediumContrast,
    )

    private val highContrastLightColorScheme = lightColorScheme(
        primary = primaryLightHighContrast,
        onPrimary = onPrimaryLightHighContrast,
        primaryContainer = primaryContainerLightHighContrast,
        onPrimaryContainer = onPrimaryContainerLightHighContrast,
        secondary = secondaryLightHighContrast,
        onSecondary = onSecondaryLightHighContrast,
        secondaryContainer = secondaryContainerLightHighContrast,
        onSecondaryContainer = onSecondaryContainerLightHighContrast,
        tertiary = tertiaryLightHighContrast,
        onTertiary = onTertiaryLightHighContrast,
        tertiaryContainer = tertiaryContainerLightHighContrast,
        onTertiaryContainer = onTertiaryContainerLightHighContrast,
        error = errorLightHighContrast,
        onError = onErrorLightHighContrast,
        errorContainer = errorContainerLightHighContrast,
        onErrorContainer = onErrorContainerLightHighContrast,
        background = backgroundLightHighContrast,
        onBackground = onBackgroundLightHighContrast,
        surface = surfaceLightHighContrast,
        onSurface = onSurfaceLightHighContrast,
        surfaceVariant = surfaceVariantLightHighContrast,
        onSurfaceVariant = onSurfaceVariantLightHighContrast,
        outline = outlineLightHighContrast,
        outlineVariant = outlineVariantLightHighContrast,
        scrim = scrimLightHighContrast,
        inverseSurface = inverseSurfaceLightHighContrast,
        inverseOnSurface = inverseOnSurfaceLightHighContrast,
        inversePrimary = inversePrimaryLightHighContrast,
        surfaceDim = surfaceDimLightHighContrast,
        surfaceBright = surfaceBrightLightHighContrast,
        surfaceContainerLowest = surfaceContainerLowestLightHighContrast,
        surfaceContainerLow = surfaceContainerLowLightHighContrast,
        surfaceContainer = surfaceContainerLightHighContrast,
        surfaceContainerHigh = surfaceContainerHighLightHighContrast,
        surfaceContainerHighest = surfaceContainerHighestLightHighContrast,
    )

    private val mediumContrastDarkColorScheme = darkColorScheme(
        primary = primaryDarkMediumContrast,
        onPrimary = onPrimaryDarkMediumContrast,
        primaryContainer = primaryContainerDarkMediumContrast,
        onPrimaryContainer = onPrimaryContainerDarkMediumContrast,
        secondary = secondaryDarkMediumContrast,
        onSecondary = onSecondaryDarkMediumContrast,
        secondaryContainer = secondaryContainerDarkMediumContrast,
        onSecondaryContainer = onSecondaryContainerDarkMediumContrast,
        tertiary = tertiaryDarkMediumContrast,
        onTertiary = onTertiaryDarkMediumContrast,
        tertiaryContainer = tertiaryContainerDarkMediumContrast,
        onTertiaryContainer = onTertiaryContainerDarkMediumContrast,
        error = errorDarkMediumContrast,
        onError = onErrorDarkMediumContrast,
        errorContainer = errorContainerDarkMediumContrast,
        onErrorContainer = onErrorContainerDarkMediumContrast,
        background = backgroundDarkMediumContrast,
        onBackground = onBackgroundDarkMediumContrast,
        surface = surfaceDarkMediumContrast,
        onSurface = onSurfaceDarkMediumContrast,
        surfaceVariant = surfaceVariantDarkMediumContrast,
        onSurfaceVariant = onSurfaceVariantDarkMediumContrast,
        outline = outlineDarkMediumContrast,
        outlineVariant = outlineVariantDarkMediumContrast,
        scrim = scrimDarkMediumContrast,
        inverseSurface = inverseSurfaceDarkMediumContrast,
        inverseOnSurface = inverseOnSurfaceDarkMediumContrast,
        inversePrimary = inversePrimaryDarkMediumContrast,
        surfaceDim = surfaceDimDarkMediumContrast,
        surfaceBright = surfaceBrightDarkMediumContrast,
        surfaceContainerLowest = surfaceContainerLowestDarkMediumContrast,
        surfaceContainerLow = surfaceContainerLowDarkMediumContrast,
        surfaceContainer = surfaceContainerDarkMediumContrast,
        surfaceContainerHigh = surfaceContainerHighDarkMediumContrast,
        surfaceContainerHighest = surfaceContainerHighestDarkMediumContrast,
    )

    private val highContrastDarkColorScheme = darkColorScheme(
        primary = primaryDarkHighContrast,
        onPrimary = onPrimaryDarkHighContrast,
        primaryContainer = primaryContainerDarkHighContrast,
        onPrimaryContainer = onPrimaryContainerDarkHighContrast,
        secondary = secondaryDarkHighContrast,
        onSecondary = onSecondaryDarkHighContrast,
        secondaryContainer = secondaryContainerDarkHighContrast,
        onSecondaryContainer = onSecondaryContainerDarkHighContrast,
        tertiary = tertiaryDarkHighContrast,
        onTertiary = onTertiaryDarkHighContrast,
        tertiaryContainer = tertiaryContainerDarkHighContrast,
        onTertiaryContainer = onTertiaryContainerDarkHighContrast,
        error = errorDarkHighContrast,
        onError = onErrorDarkHighContrast,
        errorContainer = errorContainerDarkHighContrast,
        onErrorContainer = onErrorContainerDarkHighContrast,
        background = backgroundDarkHighContrast,
        onBackground = onBackgroundDarkHighContrast,
        surface = surfaceDarkHighContrast,
        onSurface = onSurfaceDarkHighContrast,
        surfaceVariant = surfaceVariantDarkHighContrast,
        onSurfaceVariant = onSurfaceVariantDarkHighContrast,
        outline = outlineDarkHighContrast,
        outlineVariant = outlineVariantDarkHighContrast,
        scrim = scrimDarkHighContrast,
        inverseSurface = inverseSurfaceDarkHighContrast,
        inverseOnSurface = inverseOnSurfaceDarkHighContrast,
        inversePrimary = inversePrimaryDarkHighContrast,
        surfaceDim = surfaceDimDarkHighContrast,
        surfaceBright = surfaceBrightDarkHighContrast,
        surfaceContainerLowest = surfaceContainerLowestDarkHighContrast,
        surfaceContainerLow = surfaceContainerLowDarkHighContrast,
        surfaceContainer = surfaceContainerDarkHighContrast,
        surfaceContainerHigh = surfaceContainerHighDarkHighContrast,
        surfaceContainerHighest = surfaceContainerHighestDarkHighContrast,
    )

    val unspecified_scheme = ColorFamily(
        Color.Unspecified, Color.Unspecified, Color.Unspecified, Color.Unspecified
    )

}