# One JVM option per line.
# Example:
# -Xmx1G
# -Duser.language=zh
# Fix DPI scaling.
-Dcompose.application.configure.swing.globals=true
# Fix Chinese mojibake in the Windows tray. https://youtrack.jetbrains.com/issue/CMP-4486
-Dfile.encoding=GBK
