// Copyright (C) 2024  mieru authors
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Copied from mieru/pkg/appctl/proto/base.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: traffic_pattern.proto

package mieruproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NonceType int32

const (
	// Do not make change to the original random nonce.
	NonceType_NONCE_TYPE_RANDOM NonceType = 0
	// Use printable ASCII characters from 0x20 to 0x7E.
	NonceType_NONCE_TYPE_PRINTABLE NonceType = 1
	// Use a pre-defined subset of printable ASCII characters.
	NonceType_NONCE_TYPE_PRINTABLE_SUBSET NonceType = 2
	// Use a customized nonce prefix.
	// If field customHexStrings is not set in NoncePattern,
	// the behavior is the same as NONCE_TYPE_RANDOM.
	NonceType_NONCE_TYPE_FIXED NonceType = 3
)

// Enum value maps for NonceType.
var (
	NonceType_name = map[int32]string{
		0: "NONCE_TYPE_RANDOM",
		1: "NONCE_TYPE_PRINTABLE",
		2: "NONCE_TYPE_PRINTABLE_SUBSET",
		3: "NONCE_TYPE_FIXED",
	}
	NonceType_value = map[string]int32{
		"NONCE_TYPE_RANDOM":           0,
		"NONCE_TYPE_PRINTABLE":        1,
		"NONCE_TYPE_PRINTABLE_SUBSET": 2,
		"NONCE_TYPE_FIXED":            3,
	}
)

func (x NonceType) Enum() *NonceType {
	p := new(NonceType)
	*p = x
	return p
}

func (x NonceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NonceType) Descriptor() protoreflect.EnumDescriptor {
	return file_traffic_pattern_proto_enumTypes[0].Descriptor()
}

func (NonceType) Type() protoreflect.EnumType {
	return &file_traffic_pattern_proto_enumTypes[0]
}

func (x NonceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NonceType.Descriptor instead.
func (NonceType) EnumDescriptor() ([]byte, []int) {
	return file_traffic_pattern_proto_rawDescGZIP(), []int{0}
}

type LowEntropyMode int32

const (
	// Low entropy is disabled.
	LowEntropyMode_LOW_ENTROPY_MODE_OFF LowEntropyMode = 0
	// 32 bits of data is encoded into 64 bits chunk.
	// 32 bits padding is added.
	LowEntropyMode_LOW_ENTROPY_MODE_32 LowEntropyMode = 1
	// 40 bits of data is encoded into 64 bits chunk.
	// 24 bits padding is added.
	LowEntropyMode_LOW_ENTROPY_MODE_40 LowEntropyMode = 2
	// 48 bits of data is encoded into 64 bits chunk.
	// 16 bits padding is added.
	LowEntropyMode_LOW_ENTROPY_MODE_48 LowEntropyMode = 3
	// 56 bits of data is encoded into 64 bits chunk.
	// 8 bits padding is added.
	LowEntropyMode_LOW_ENTROPY_MODE_56 LowEntropyMode = 4
)

// Enum value maps for LowEntropyMode.
var (
	LowEntropyMode_name = map[int32]string{
		0: "LOW_ENTROPY_MODE_OFF",
		1: "LOW_ENTROPY_MODE_32",
		2: "LOW_ENTROPY_MODE_40",
		3: "LOW_ENTROPY_MODE_48",
		4: "LOW_ENTROPY_MODE_56",
	}
	LowEntropyMode_value = map[string]int32{
		"LOW_ENTROPY_MODE_OFF": 0,
		"LOW_ENTROPY_MODE_32":  1,
		"LOW_ENTROPY_MODE_40":  2,
		"LOW_ENTROPY_MODE_48":  3,
		"LOW_ENTROPY_MODE_56":  4,
	}
)

func (x LowEntropyMode) Enum() *LowEntropyMode {
	p := new(LowEntropyMode)
	*p = x
	return p
}

func (x LowEntropyMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LowEntropyMode) Descriptor() protoreflect.EnumDescriptor {
	return file_traffic_pattern_proto_enumTypes[1].Descriptor()
}

func (LowEntropyMode) Type() protoreflect.EnumType {
	return &file_traffic_pattern_proto_enumTypes[1]
}

func (x LowEntropyMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LowEntropyMode.Descriptor instead.
func (LowEntropyMode) EnumDescriptor() ([]byte, []int) {
	return file_traffic_pattern_proto_rawDescGZIP(), []int{1}
}

type LowEntropyMaskRotation int32

const (
	// Mask doesn't change for each 64 bits chunk.
	LowEntropyMaskRotation_LOW_ENTROPY_MASK_NO_ROTATION LowEntropyMaskRotation = 0
	// The 4 least significant bits determine how many bits to rotate right
	// for each 64 bits chunk.
	LowEntropyMaskRotation_LOW_ENTROPY_MASK_ROTATE_RIGHT_1  LowEntropyMaskRotation = 1
	LowEntropyMaskRotation_LOW_ENTROPY_MASK_ROTATE_RIGHT_2  LowEntropyMaskRotation = 2
	LowEntropyMaskRotation_LOW_ENTROPY_MASK_ROTATE_RIGHT_3  LowEntropyMaskRotation = 3
	LowEntropyMaskRotation_LOW_ENTROPY_MASK_ROTATE_RIGHT_4  LowEntropyMaskRotation = 4
	LowEntropyMaskRotation_LOW_ENTROPY_MASK_ROTATE_RIGHT_5  LowEntropyMaskRotation = 5
	LowEntropyMaskRotation_LOW_ENTROPY_MASK_ROTATE_RIGHT_6  LowEntropyMaskRotation = 6
	LowEntropyMaskRotation_LOW_ENTROPY_MASK_ROTATE_RIGHT_7  LowEntropyMaskRotation = 7
	LowEntropyMaskRotation_LOW_ENTROPY_MASK_ROTATE_RIGHT_8  LowEntropyMaskRotation = 8
	LowEntropyMaskRotation_LOW_ENTROPY_MASK_ROTATE_RIGHT_9  LowEntropyMaskRotation = 9
	LowEntropyMaskRotation_LOW_ENTROPY_MASK_ROTATE_RIGHT_10 LowEntropyMaskRotation = 10
	LowEntropyMaskRotation_LOW_ENTROPY_MASK_ROTATE_RIGHT_11 LowEntropyMaskRotation = 11
	LowEntropyMaskRotation_LOW_ENTROPY_MASK_ROTATE_RIGHT_12 LowEntropyMaskRotation = 12
	LowEntropyMaskRotation_LOW_ENTROPY_MASK_ROTATE_RIGHT_13 LowEntropyMaskRotation = 13
	LowEntropyMaskRotation_LOW_ENTROPY_MASK_ROTATE_RIGHT_14 LowEntropyMaskRotation = 14
	LowEntropyMaskRotation_LOW_ENTROPY_MASK_ROTATE_RIGHT_15 LowEntropyMaskRotation = 15
	// The 4 most significant bits determine how many bits to rotate left
	// for each 64 bits chunk.
	LowEntropyMaskRotation_LOW_ENTROPY_MASK_ROTATE_LEFT_1  LowEntropyMaskRotation = 16
	LowEntropyMaskRotation_LOW_ENTROPY_MASK_ROTATE_LEFT_2  LowEntropyMaskRotation = 32
	LowEntropyMaskRotation_LOW_ENTROPY_MASK_ROTATE_LEFT_3  LowEntropyMaskRotation = 48
	LowEntropyMaskRotation_LOW_ENTROPY_MASK_ROTATE_LEFT_4  LowEntropyMaskRotation = 64
	LowEntropyMaskRotation_LOW_ENTROPY_MASK_ROTATE_LEFT_5  LowEntropyMaskRotation = 80
	LowEntropyMaskRotation_LOW_ENTROPY_MASK_ROTATE_LEFT_6  LowEntropyMaskRotation = 96
	LowEntropyMaskRotation_LOW_ENTROPY_MASK_ROTATE_LEFT_7  LowEntropyMaskRotation = 112
	LowEntropyMaskRotation_LOW_ENTROPY_MASK_ROTATE_LEFT_8  LowEntropyMaskRotation = 128
	LowEntropyMaskRotation_LOW_ENTROPY_MASK_ROTATE_LEFT_9  LowEntropyMaskRotation = 144
	LowEntropyMaskRotation_LOW_ENTROPY_MASK_ROTATE_LEFT_10 LowEntropyMaskRotation = 160
	LowEntropyMaskRotation_LOW_ENTROPY_MASK_ROTATE_LEFT_11 LowEntropyMaskRotation = 176
	LowEntropyMaskRotation_LOW_ENTROPY_MASK_ROTATE_LEFT_12 LowEntropyMaskRotation = 192
	LowEntropyMaskRotation_LOW_ENTROPY_MASK_ROTATE_LEFT_13 LowEntropyMaskRotation = 208
	LowEntropyMaskRotation_LOW_ENTROPY_MASK_ROTATE_LEFT_14 LowEntropyMaskRotation = 224
	LowEntropyMaskRotation_LOW_ENTROPY_MASK_ROTATE_LEFT_15 LowEntropyMaskRotation = 240
)

// Enum value maps for LowEntropyMaskRotation.
var (
	LowEntropyMaskRotation_name = map[int32]string{
		0:   "LOW_ENTROPY_MASK_NO_ROTATION",
		1:   "LOW_ENTROPY_MASK_ROTATE_RIGHT_1",
		2:   "LOW_ENTROPY_MASK_ROTATE_RIGHT_2",
		3:   "LOW_ENTROPY_MASK_ROTATE_RIGHT_3",
		4:   "LOW_ENTROPY_MASK_ROTATE_RIGHT_4",
		5:   "LOW_ENTROPY_MASK_ROTATE_RIGHT_5",
		6:   "LOW_ENTROPY_MASK_ROTATE_RIGHT_6",
		7:   "LOW_ENTROPY_MASK_ROTATE_RIGHT_7",
		8:   "LOW_ENTROPY_MASK_ROTATE_RIGHT_8",
		9:   "LOW_ENTROPY_MASK_ROTATE_RIGHT_9",
		10:  "LOW_ENTROPY_MASK_ROTATE_RIGHT_10",
		11:  "LOW_ENTROPY_MASK_ROTATE_RIGHT_11",
		12:  "LOW_ENTROPY_MASK_ROTATE_RIGHT_12",
		13:  "LOW_ENTROPY_MASK_ROTATE_RIGHT_13",
		14:  "LOW_ENTROPY_MASK_ROTATE_RIGHT_14",
		15:  "LOW_ENTROPY_MASK_ROTATE_RIGHT_15",
		16:  "LOW_ENTROPY_MASK_ROTATE_LEFT_1",
		32:  "LOW_ENTROPY_MASK_ROTATE_LEFT_2",
		48:  "LOW_ENTROPY_MASK_ROTATE_LEFT_3",
		64:  "LOW_ENTROPY_MASK_ROTATE_LEFT_4",
		80:  "LOW_ENTROPY_MASK_ROTATE_LEFT_5",
		96:  "LOW_ENTROPY_MASK_ROTATE_LEFT_6",
		112: "LOW_ENTROPY_MASK_ROTATE_LEFT_7",
		128: "LOW_ENTROPY_MASK_ROTATE_LEFT_8",
		144: "LOW_ENTROPY_MASK_ROTATE_LEFT_9",
		160: "LOW_ENTROPY_MASK_ROTATE_LEFT_10",
		176: "LOW_ENTROPY_MASK_ROTATE_LEFT_11",
		192: "LOW_ENTROPY_MASK_ROTATE_LEFT_12",
		208: "LOW_ENTROPY_MASK_ROTATE_LEFT_13",
		224: "LOW_ENTROPY_MASK_ROTATE_LEFT_14",
		240: "LOW_ENTROPY_MASK_ROTATE_LEFT_15",
	}
	LowEntropyMaskRotation_value = map[string]int32{
		"LOW_ENTROPY_MASK_NO_ROTATION":     0,
		"LOW_ENTROPY_MASK_ROTATE_RIGHT_1":  1,
		"LOW_ENTROPY_MASK_ROTATE_RIGHT_2":  2,
		"LOW_ENTROPY_MASK_ROTATE_RIGHT_3":  3,
		"LOW_ENTROPY_MASK_ROTATE_RIGHT_4":  4,
		"LOW_ENTROPY_MASK_ROTATE_RIGHT_5":  5,
		"LOW_ENTROPY_MASK_ROTATE_RIGHT_6":  6,
		"LOW_ENTROPY_MASK_ROTATE_RIGHT_7":  7,
		"LOW_ENTROPY_MASK_ROTATE_RIGHT_8":  8,
		"LOW_ENTROPY_MASK_ROTATE_RIGHT_9":  9,
		"LOW_ENTROPY_MASK_ROTATE_RIGHT_10": 10,
		"LOW_ENTROPY_MASK_ROTATE_RIGHT_11": 11,
		"LOW_ENTROPY_MASK_ROTATE_RIGHT_12": 12,
		"LOW_ENTROPY_MASK_ROTATE_RIGHT_13": 13,
		"LOW_ENTROPY_MASK_ROTATE_RIGHT_14": 14,
		"LOW_ENTROPY_MASK_ROTATE_RIGHT_15": 15,
		"LOW_ENTROPY_MASK_ROTATE_LEFT_1":   16,
		"LOW_ENTROPY_MASK_ROTATE_LEFT_2":   32,
		"LOW_ENTROPY_MASK_ROTATE_LEFT_3":   48,
		"LOW_ENTROPY_MASK_ROTATE_LEFT_4":   64,
		"LOW_ENTROPY_MASK_ROTATE_LEFT_5":   80,
		"LOW_ENTROPY_MASK_ROTATE_LEFT_6":   96,
		"LOW_ENTROPY_MASK_ROTATE_LEFT_7":   112,
		"LOW_ENTROPY_MASK_ROTATE_LEFT_8":   128,
		"LOW_ENTROPY_MASK_ROTATE_LEFT_9":   144,
		"LOW_ENTROPY_MASK_ROTATE_LEFT_10":  160,
		"LOW_ENTROPY_MASK_ROTATE_LEFT_11":  176,
		"LOW_ENTROPY_MASK_ROTATE_LEFT_12":  192,
		"LOW_ENTROPY_MASK_ROTATE_LEFT_13":  208,
		"LOW_ENTROPY_MASK_ROTATE_LEFT_14":  224,
		"LOW_ENTROPY_MASK_ROTATE_LEFT_15":  240,
	}
)

func (x LowEntropyMaskRotation) Enum() *LowEntropyMaskRotation {
	p := new(LowEntropyMaskRotation)
	*p = x
	return p
}

func (x LowEntropyMaskRotation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LowEntropyMaskRotation) Descriptor() protoreflect.EnumDescriptor {
	return file_traffic_pattern_proto_enumTypes[2].Descriptor()
}

func (LowEntropyMaskRotation) Type() protoreflect.EnumType {
	return &file_traffic_pattern_proto_enumTypes[2]
}

func (x LowEntropyMaskRotation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LowEntropyMaskRotation.Descriptor instead.
func (LowEntropyMaskRotation) EnumDescriptor() ([]byte, []int) {
	return file_traffic_pattern_proto_rawDescGZIP(), []int{2}
}

type TrafficPattern struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Generate stable implicit traffic patterns that are not explictly set.
	// Generated traffic patterns are also influenced by "unlockAll" below.
	Seed *int32 `protobuf:"varint,1,opt,name=seed,proto3,oneof" json:"seed,omitempty"`
	// If true, implicit traffic patterns can use all possible options,
	// which may not be desired. Otherwise, implicit traffic patterns
	// only use limited options.
	// All explicitly set traffic patterns are available regardless of this.
	UnlockAll *bool `protobuf:"varint,2,opt,name=unlockAll,proto3,oneof" json:"unlockAll,omitempty"`
	// Split TCP packets by fragmentation.
	TcpFragment *TCPFragment `protobuf:"bytes,3,opt,name=tcpFragment,proto3,oneof" json:"tcpFragment,omitempty"`
	// Manipulate nonce prefix.
	Nonce *NoncePattern `protobuf:"bytes,4,opt,name=nonce,proto3,oneof" json:"nonce,omitempty"`
	// Define padding behavior.
	Padding *PaddingPattern `protobuf:"bytes,5,opt,name=padding,proto3,oneof" json:"padding,omitempty"`
	// Define low entropy traffic behavior.
	LowEntropy    *LowEntropyPattern `protobuf:"bytes,6,opt,name=lowEntropy,proto3,oneof" json:"lowEntropy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficPattern) Reset() {
	*x = TrafficPattern{}
	mi := &file_traffic_pattern_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficPattern) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficPattern) ProtoMessage() {}

func (x *TrafficPattern) ProtoReflect() protoreflect.Message {
	mi := &file_traffic_pattern_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficPattern.ProtoReflect.Descriptor instead.
func (*TrafficPattern) Descriptor() ([]byte, []int) {
	return file_traffic_pattern_proto_rawDescGZIP(), []int{0}
}

func (x *TrafficPattern) GetSeed() int32 {
	if x != nil && x.Seed != nil {
		return *x.Seed
	}
	return 0
}

func (x *TrafficPattern) GetUnlockAll() bool {
	if x != nil && x.UnlockAll != nil {
		return *x.UnlockAll
	}
	return false
}

func (x *TrafficPattern) GetTcpFragment() *TCPFragment {
	if x != nil {
		return x.TcpFragment
	}
	return nil
}

func (x *TrafficPattern) GetNonce() *NoncePattern {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *TrafficPattern) GetPadding() *PaddingPattern {
	if x != nil {
		return x.Padding
	}
	return nil
}

func (x *TrafficPattern) GetLowEntropy() *LowEntropyPattern {
	if x != nil {
		return x.LowEntropy
	}
	return nil
}

type TCPFragment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Enable additional TCP fragmentation.
	Enable *bool `protobuf:"varint,1,opt,name=enable,proto3,oneof" json:"enable,omitempty"`
	// Max sleep time in milliseconds between sending two fragments.
	// This value can't exceed 100.
	// If not set, a reasonable default value is used.
	MaxSleepMs    *int32 `protobuf:"varint,2,opt,name=maxSleepMs,proto3,oneof" json:"maxSleepMs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TCPFragment) Reset() {
	*x = TCPFragment{}
	mi := &file_traffic_pattern_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TCPFragment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TCPFragment) ProtoMessage() {}

func (x *TCPFragment) ProtoReflect() protoreflect.Message {
	mi := &file_traffic_pattern_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TCPFragment.ProtoReflect.Descriptor instead.
func (*TCPFragment) Descriptor() ([]byte, []int) {
	return file_traffic_pattern_proto_rawDescGZIP(), []int{1}
}

func (x *TCPFragment) GetEnable() bool {
	if x != nil && x.Enable != nil {
		return *x.Enable
	}
	return false
}

func (x *TCPFragment) GetMaxSleepMs() int32 {
	if x != nil && x.MaxSleepMs != nil {
		return *x.MaxSleepMs
	}
	return 0
}

type NoncePattern struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Strategy to manipulate nonce.
	Type *NonceType `protobuf:"varint,1,opt,name=type,proto3,enum=mieruproto.NonceType,oneof" json:"type,omitempty"`
	// If the pattern applies to each UDP packet,
	// or only applies to the first UDP packet.
	ApplyToAllUDPPacket *bool `protobuf:"varint,2,opt,name=applyToAllUDPPacket,proto3,oneof" json:"applyToAllUDPPacket,omitempty"`
	// Minimum number of bytes to manipulate.
	// It is ignored when NonceType is NONCE_TYPE_RANDOM or NONCE_TYPE_FIXED.
	MinLen *int32 `protobuf:"varint,3,opt,name=minLen,proto3,oneof" json:"minLen,omitempty"`
	// Maximum number of bytes to manipulate.
	// This value can't exceed 12.
	// It is ignored when NonceType is NONCE_TYPE_RANDOM or NONCE_TYPE_FIXED.
	MaxLen *int32 `protobuf:"varint,4,opt,name=maxLen,proto3,oneof" json:"maxLen,omitempty"`
	// A list of hex string (without 0x) that represent customized
	// nonce prefix to use. For example, string "00010203"
	// represent a 4 bytes nonce prefix [0, 1, 2, 3].
	//
	// Each nonce prefix can't exceed 12 bytes.
	//
	// When multiple strings are provided, a random one is used each time.
	//
	// It has no effect when NonceType is not NONCE_TYPE_FIXED.
	CustomHexStrings []string `protobuf:"bytes,5,rep,name=customHexStrings,proto3" json:"customHexStrings,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NoncePattern) Reset() {
	*x = NoncePattern{}
	mi := &file_traffic_pattern_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoncePattern) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoncePattern) ProtoMessage() {}

func (x *NoncePattern) ProtoReflect() protoreflect.Message {
	mi := &file_traffic_pattern_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoncePattern.ProtoReflect.Descriptor instead.
func (*NoncePattern) Descriptor() ([]byte, []int) {
	return file_traffic_pattern_proto_rawDescGZIP(), []int{2}
}

func (x *NoncePattern) GetType() NonceType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return NonceType_NONCE_TYPE_RANDOM
}

func (x *NoncePattern) GetApplyToAllUDPPacket() bool {
	if x != nil && x.ApplyToAllUDPPacket != nil {
		return *x.ApplyToAllUDPPacket
	}
	return false
}

func (x *NoncePattern) GetMinLen() int32 {
	if x != nil && x.MinLen != nil {
		return *x.MinLen
	}
	return 0
}

func (x *NoncePattern) GetMaxLen() int32 {
	if x != nil && x.MaxLen != nil {
		return *x.MaxLen
	}
	return 0
}

func (x *NoncePattern) GetCustomHexStrings() []string {
	if x != nil {
		return x.CustomHexStrings
	}
	return nil
}

type PaddingPattern struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum number of padding bytes in the middle of a network segment.
	// The valid range is [0, 255].
	// Set it to 0 to disable middle padding.
	// It not set, an internal value is used.
	MaxMiddlePaddingLen *int32 `protobuf:"varint,1,opt,name=maxMiddlePaddingLen,proto3,oneof" json:"maxMiddlePaddingLen,omitempty"`
	// Maximum number of padding bytes at the end of a network segment.
	// The valid range is [0, 255].
	// Set it to 0 to disable end padding.
	// It not set, an internal value is used.
	MaxEndPaddingLen *int32 `protobuf:"varint,2,opt,name=maxEndPaddingLen,proto3,oneof" json:"maxEndPaddingLen,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PaddingPattern) Reset() {
	*x = PaddingPattern{}
	mi := &file_traffic_pattern_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaddingPattern) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaddingPattern) ProtoMessage() {}

func (x *PaddingPattern) ProtoReflect() protoreflect.Message {
	mi := &file_traffic_pattern_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaddingPattern.ProtoReflect.Descriptor instead.
func (*PaddingPattern) Descriptor() ([]byte, []int) {
	return file_traffic_pattern_proto_rawDescGZIP(), []int{3}
}

func (x *PaddingPattern) GetMaxMiddlePaddingLen() int32 {
	if x != nil && x.MaxMiddlePaddingLen != nil {
		return *x.MaxMiddlePaddingLen
	}
	return 0
}

func (x *PaddingPattern) GetMaxEndPaddingLen() int32 {
	if x != nil && x.MaxEndPaddingLen != nil {
		return *x.MaxEndPaddingLen
	}
	return 0
}

type LowEntropyPattern struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If low entropy is enabled, and how much entropy is reduced.
	Mode *LowEntropyMode `protobuf:"varint,1,opt,name=mode,proto3,enum=mieruproto.LowEntropyMode,oneof" json:"mode,omitempty"`
	// Low entropy uses a 64-bit long mask to determine the position of padding bits.
	// This determines how to rotate the mask between two adjacent chunks.
	// It has no effect if low entropy mode is disabled.
	MaskRotation  *LowEntropyMaskRotation `protobuf:"varint,2,opt,name=maskRotation,proto3,enum=mieruproto.LowEntropyMaskRotation,oneof" json:"maskRotation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LowEntropyPattern) Reset() {
	*x = LowEntropyPattern{}
	mi := &file_traffic_pattern_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LowEntropyPattern) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LowEntropyPattern) ProtoMessage() {}

func (x *LowEntropyPattern) ProtoReflect() protoreflect.Message {
	mi := &file_traffic_pattern_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LowEntropyPattern.ProtoReflect.Descriptor instead.
func (*LowEntropyPattern) Descriptor() ([]byte, []int) {
	return file_traffic_pattern_proto_rawDescGZIP(), []int{4}
}

func (x *LowEntropyPattern) GetMode() LowEntropyMode {
	if x != nil && x.Mode != nil {
		return *x.Mode
	}
	return LowEntropyMode_LOW_ENTROPY_MODE_OFF
}

func (x *LowEntropyPattern) GetMaskRotation() LowEntropyMaskRotation {
	if x != nil && x.MaskRotation != nil {
		return *x.MaskRotation
	}
	return LowEntropyMaskRotation_LOW_ENTROPY_MASK_NO_ROTATION
}

var File_traffic_pattern_proto protoreflect.FileDescriptor

const file_traffic_pattern_proto_rawDesc = "" +
	"\n" +
	"\x15traffic_pattern.proto\x12\n" +
	"mieruproto\"\x8c\x03\n" +
	"\x0eTrafficPattern\x12\x17\n" +
	"\x04seed\x18\x01 \x01(\x05H\x00R\x04seed\x88\x01\x01\x12!\n" +
	"\tunlockAll\x18\x02 \x01(\bH\x01R\tunlockAll\x88\x01\x01\x12>\n" +
	"\vtcpFragment\x18\x03 \x01(\v2\x17.mieruproto.TCPFragmentH\x02R\vtcpFragment\x88\x01\x01\x123\n" +
	"\x05nonce\x18\x04 \x01(\v2\x18.mieruproto.NoncePatternH\x03R\x05nonce\x88\x01\x01\x129\n" +
	"\apadding\x18\x05 \x01(\v2\x1a.mieruproto.PaddingPatternH\x04R\apadding\x88\x01\x01\x12B\n" +
	"\n" +
	"lowEntropy\x18\x06 \x01(\v2\x1d.mieruproto.LowEntropyPatternH\x05R\n" +
	"lowEntropy\x88\x01\x01B\a\n" +
	"\x05_seedB\f\n" +
	"\n" +
	"_unlockAllB\x0e\n" +
	"\f_tcpFragmentB\b\n" +
	"\x06_nonceB\n" +
	"\n" +
	"\b_paddingB\r\n" +
	"\v_lowEntropy\"i\n" +
	"\vTCPFragment\x12\x1b\n" +
	"\x06enable\x18\x01 \x01(\bH\x00R\x06enable\x88\x01\x01\x12#\n" +
	"\n" +
	"maxSleepMs\x18\x02 \x01(\x05H\x01R\n" +
	"maxSleepMs\x88\x01\x01B\t\n" +
	"\a_enableB\r\n" +
	"\v_maxSleepMs\"\x92\x02\n" +
	"\fNoncePattern\x12.\n" +
	"\x04type\x18\x01 \x01(\x0e2\x15.mieruproto.NonceTypeH\x00R\x04type\x88\x01\x01\x125\n" +
	"\x13applyToAllUDPPacket\x18\x02 \x01(\bH\x01R\x13applyToAllUDPPacket\x88\x01\x01\x12\x1b\n" +
	"\x06minLen\x18\x03 \x01(\x05H\x02R\x06minLen\x88\x01\x01\x12\x1b\n" +
	"\x06maxLen\x18\x04 \x01(\x05H\x03R\x06maxLen\x88\x01\x01\x12*\n" +
	"\x10customHexStrings\x18\x05 \x03(\tR\x10customHexStringsB\a\n" +
	"\x05_typeB\x16\n" +
	"\x14_applyToAllUDPPacketB\t\n" +
	"\a_minLenB\t\n" +
	"\a_maxLen\"\xa5\x01\n" +
	"\x0ePaddingPattern\x125\n" +
	"\x13maxMiddlePaddingLen\x18\x01 \x01(\x05H\x00R\x13maxMiddlePaddingLen\x88\x01\x01\x12/\n" +
	"\x10maxEndPaddingLen\x18\x02 \x01(\x05H\x01R\x10maxEndPaddingLen\x88\x01\x01B\x16\n" +
	"\x14_maxMiddlePaddingLenB\x13\n" +
	"\x11_maxEndPaddingLen\"\xaf\x01\n" +
	"\x11LowEntropyPattern\x123\n" +
	"\x04mode\x18\x01 \x01(\x0e2\x1a.mieruproto.LowEntropyModeH\x00R\x04mode\x88\x01\x01\x12K\n" +
	"\fmaskRotation\x18\x02 \x01(\x0e2\".mieruproto.LowEntropyMaskRotationH\x01R\fmaskRotation\x88\x01\x01B\a\n" +
	"\x05_modeB\x0f\n" +
	"\r_maskRotation*s\n" +
	"\tNonceType\x12\x15\n" +
	"\x11NONCE_TYPE_RANDOM\x10\x00\x12\x18\n" +
	"\x14NONCE_TYPE_PRINTABLE\x10\x01\x12\x1f\n" +
	"\x1bNONCE_TYPE_PRINTABLE_SUBSET\x10\x02\x12\x14\n" +
	"\x10NONCE_TYPE_FIXED\x10\x03*\x8e\x01\n" +
	"\x0eLowEntropyMode\x12\x18\n" +
	"\x14LOW_ENTROPY_MODE_OFF\x10\x00\x12\x17\n" +
	"\x13LOW_ENTROPY_MODE_32\x10\x01\x12\x17\n" +
	"\x13LOW_ENTROPY_MODE_40\x10\x02\x12\x17\n" +
	"\x13LOW_ENTROPY_MODE_48\x10\x03\x12\x17\n" +
	"\x13LOW_ENTROPY_MODE_56\x10\x04*\x95\t\n" +
	"\x16LowEntropyMaskRotation\x12 \n" +
	"\x1cLOW_ENTROPY_MASK_NO_ROTATION\x10\x00\x12#\n" +
	"\x1fLOW_ENTROPY_MASK_ROTATE_RIGHT_1\x10\x01\x12#\n" +
	"\x1fLOW_ENTROPY_MASK_ROTATE_RIGHT_2\x10\x02\x12#\n" +
	"\x1fLOW_ENTROPY_MASK_ROTATE_RIGHT_3\x10\x03\x12#\n" +
	"\x1fLOW_ENTROPY_MASK_ROTATE_RIGHT_4\x10\x04\x12#\n" +
	"\x1fLOW_ENTROPY_MASK_ROTATE_RIGHT_5\x10\x05\x12#\n" +
	"\x1fLOW_ENTROPY_MASK_ROTATE_RIGHT_6\x10\x06\x12#\n" +
	"\x1fLOW_ENTROPY_MASK_ROTATE_RIGHT_7\x10\a\x12#\n" +
	"\x1fLOW_ENTROPY_MASK_ROTATE_RIGHT_8\x10\b\x12#\n" +
	"\x1fLOW_ENTROPY_MASK_ROTATE_RIGHT_9\x10\t\x12$\n" +
	" LOW_ENTROPY_MASK_ROTATE_RIGHT_10\x10\n" +
	"\x12$\n" +
	" LOW_ENTROPY_MASK_ROTATE_RIGHT_11\x10\v\x12$\n" +
	" LOW_ENTROPY_MASK_ROTATE_RIGHT_12\x10\f\x12$\n" +
	" LOW_ENTROPY_MASK_ROTATE_RIGHT_13\x10\r\x12$\n" +
	" LOW_ENTROPY_MASK_ROTATE_RIGHT_14\x10\x0e\x12$\n" +
	" LOW_ENTROPY_MASK_ROTATE_RIGHT_15\x10\x0f\x12\"\n" +
	"\x1eLOW_ENTROPY_MASK_ROTATE_LEFT_1\x10\x10\x12\"\n" +
	"\x1eLOW_ENTROPY_MASK_ROTATE_LEFT_2\x10 \x12\"\n" +
	"\x1eLOW_ENTROPY_MASK_ROTATE_LEFT_3\x100\x12\"\n" +
	"\x1eLOW_ENTROPY_MASK_ROTATE_LEFT_4\x10@\x12\"\n" +
	"\x1eLOW_ENTROPY_MASK_ROTATE_LEFT_5\x10P\x12\"\n" +
	"\x1eLOW_ENTROPY_MASK_ROTATE_LEFT_6\x10`\x12\"\n" +
	"\x1eLOW_ENTROPY_MASK_ROTATE_LEFT_7\x10p\x12#\n" +
	"\x1eLOW_ENTROPY_MASK_ROTATE_LEFT_8\x10\x80\x01\x12#\n" +
	"\x1eLOW_ENTROPY_MASK_ROTATE_LEFT_9\x10\x90\x01\x12$\n" +
	"\x1fLOW_ENTROPY_MASK_ROTATE_LEFT_10\x10\xa0\x01\x12$\n" +
	"\x1fLOW_ENTROPY_MASK_ROTATE_LEFT_11\x10\xb0\x01\x12$\n" +
	"\x1fLOW_ENTROPY_MASK_ROTATE_LEFT_12\x10\xc0\x01\x12$\n" +
	"\x1fLOW_ENTROPY_MASK_ROTATE_LEFT_13\x10\xd0\x01\x12$\n" +
	"\x1fLOW_ENTROPY_MASK_ROTATE_LEFT_14\x10\xe0\x01\x12$\n" +
	"\x1fLOW_ENTROPY_MASK_ROTATE_LEFT_15\x10\xf0\x01B&Z$libcore/plugin/mieruproto;mieruprotob\x06proto3"

var (
	file_traffic_pattern_proto_rawDescOnce sync.Once
	file_traffic_pattern_proto_rawDescData []byte
)

func file_traffic_pattern_proto_rawDescGZIP() []byte {
	file_traffic_pattern_proto_rawDescOnce.Do(func() {
		file_traffic_pattern_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_traffic_pattern_proto_rawDesc), len(file_traffic_pattern_proto_rawDesc)))
	})
	return file_traffic_pattern_proto_rawDescData
}

var file_traffic_pattern_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_traffic_pattern_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_traffic_pattern_proto_goTypes = []any{
	(NonceType)(0),              // 0: mieruproto.NonceType
	(LowEntropyMode)(0),         // 1: mieruproto.LowEntropyMode
	(LowEntropyMaskRotation)(0), // 2: mieruproto.LowEntropyMaskRotation
	(*TrafficPattern)(nil),      // 3: mieruproto.TrafficPattern
	(*TCPFragment)(nil),         // 4: mieruproto.TCPFragment
	(*NoncePattern)(nil),        // 5: mieruproto.NoncePattern
	(*PaddingPattern)(nil),      // 6: mieruproto.PaddingPattern
	(*LowEntropyPattern)(nil),   // 7: mieruproto.LowEntropyPattern
}
var file_traffic_pattern_proto_depIdxs = []int32{
	4, // 0: mieruproto.TrafficPattern.tcpFragment:type_name -> mieruproto.TCPFragment
	5, // 1: mieruproto.TrafficPattern.nonce:type_name -> mieruproto.NoncePattern
	6, // 2: mieruproto.TrafficPattern.padding:type_name -> mieruproto.PaddingPattern
	7, // 3: mieruproto.TrafficPattern.lowEntropy:type_name -> mieruproto.LowEntropyPattern
	0, // 4: mieruproto.NoncePattern.type:type_name -> mieruproto.NonceType
	1, // 5: mieruproto.LowEntropyPattern.mode:type_name -> mieruproto.LowEntropyMode
	2, // 6: mieruproto.LowEntropyPattern.maskRotation:type_name -> mieruproto.LowEntropyMaskRotation
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_traffic_pattern_proto_init() }
func file_traffic_pattern_proto_init() {
	if File_traffic_pattern_proto != nil {
		return
	}
	file_traffic_pattern_proto_msgTypes[0].OneofWrappers = []any{}
	file_traffic_pattern_proto_msgTypes[1].OneofWrappers = []any{}
	file_traffic_pattern_proto_msgTypes[2].OneofWrappers = []any{}
	file_traffic_pattern_proto_msgTypes[3].OneofWrappers = []any{}
	file_traffic_pattern_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_traffic_pattern_proto_rawDesc), len(file_traffic_pattern_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_traffic_pattern_proto_goTypes,
		DependencyIndexes: file_traffic_pattern_proto_depIdxs,
		EnumInfos:         file_traffic_pattern_proto_enumTypes,
		MessageInfos:      file_traffic_pattern_proto_msgTypes,
	}.Build()
	File_traffic_pattern_proto = out.File
	file_traffic_pattern_proto_goTypes = nil
	file_traffic_pattern_proto_depIdxs = nil
}
