// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: husi/v1/app.proto

package husiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShowWindowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowWindowRequest) Reset() {
	*x = ShowWindowRequest{}
	mi := &file_husi_v1_app_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowWindowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowWindowRequest) ProtoMessage() {}

func (x *ShowWindowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_app_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowWindowRequest.ProtoReflect.Descriptor instead.
func (*ShowWindowRequest) Descriptor() ([]byte, []int) {
	return file_husi_v1_app_proto_rawDescGZIP(), []int{0}
}

type ShowWindowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowWindowResponse) Reset() {
	*x = ShowWindowResponse{}
	mi := &file_husi_v1_app_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowWindowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowWindowResponse) ProtoMessage() {}

func (x *ShowWindowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_app_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowWindowResponse.ProtoReflect.Descriptor instead.
func (*ShowWindowResponse) Descriptor() ([]byte, []int) {
	return file_husi_v1_app_proto_rawDescGZIP(), []int{1}
}

type DispatchDeepLinksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Links         []string               `protobuf:"bytes,1,rep,name=links,proto3" json:"links,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchDeepLinksRequest) Reset() {
	*x = DispatchDeepLinksRequest{}
	mi := &file_husi_v1_app_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchDeepLinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchDeepLinksRequest) ProtoMessage() {}

func (x *DispatchDeepLinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_app_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchDeepLinksRequest.ProtoReflect.Descriptor instead.
func (*DispatchDeepLinksRequest) Descriptor() ([]byte, []int) {
	return file_husi_v1_app_proto_rawDescGZIP(), []int{2}
}

func (x *DispatchDeepLinksRequest) GetLinks() []string {
	if x != nil {
		return x.Links
	}
	return nil
}

type DispatchDeepLinksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchDeepLinksResponse) Reset() {
	*x = DispatchDeepLinksResponse{}
	mi := &file_husi_v1_app_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchDeepLinksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchDeepLinksResponse) ProtoMessage() {}

func (x *DispatchDeepLinksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_app_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchDeepLinksResponse.ProtoReflect.Descriptor instead.
func (*DispatchDeepLinksResponse) Descriptor() ([]byte, []int) {
	return file_husi_v1_app_proto_rawDescGZIP(), []int{3}
}

type RunTaskRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier registered in DesktopTaskRegistry, such as a subscription or
	// route asset update.
	TaskId        string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunTaskRequest) Reset() {
	*x = RunTaskRequest{}
	mi := &file_husi_v1_app_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunTaskRequest) ProtoMessage() {}

func (x *RunTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_app_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunTaskRequest.ProtoReflect.Descriptor instead.
func (*RunTaskRequest) Descriptor() ([]byte, []int) {
	return file_husi_v1_app_proto_rawDescGZIP(), []int{4}
}

func (x *RunTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type RunTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunTaskResponse) Reset() {
	*x = RunTaskResponse{}
	mi := &file_husi_v1_app_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunTaskResponse) ProtoMessage() {}

func (x *RunTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_app_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunTaskResponse.ProtoReflect.Descriptor instead.
func (*RunTaskResponse) Descriptor() ([]byte, []int) {
	return file_husi_v1_app_proto_rawDescGZIP(), []int{5}
}

var File_husi_v1_app_proto protoreflect.FileDescriptor

const file_husi_v1_app_proto_rawDesc = "" +
	"\n" +
	"\x11husi/v1/app.proto\x12\ahusi.v1\"\x13\n" +
	"\x11ShowWindowRequest\"\x14\n" +
	"\x12ShowWindowResponse\"0\n" +
	"\x18DispatchDeepLinksRequest\x12\x14\n" +
	"\x05links\x18\x01 \x03(\tR\x05links\"\x1b\n" +
	"\x19DispatchDeepLinksResponse\")\n" +
	"\x0eRunTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"\x11\n" +
	"\x0fRunTaskResponse2\xed\x01\n" +
	"\n" +
	"AppService\x12E\n" +
	"\n" +
	"ShowWindow\x12\x1a.husi.v1.ShowWindowRequest\x1a\x1b.husi.v1.ShowWindowResponse\x12Z\n" +
	"\x11DispatchDeepLinks\x12!.husi.v1.DispatchDeepLinksRequest\x1a\".husi.v1.DispatchDeepLinksResponse\x12<\n" +
	"\aRunTask\x12\x17.husi.v1.RunTaskRequest\x1a\x18.husi.v1.RunTaskResponseB9\n" +
	"\x10fr.husi.proto.v1B\bAppProtoP\x01Z\x19libcore/pb/husi/v1;husiv1b\x06proto3"

var (
	file_husi_v1_app_proto_rawDescOnce sync.Once
	file_husi_v1_app_proto_rawDescData []byte
)

func file_husi_v1_app_proto_rawDescGZIP() []byte {
	file_husi_v1_app_proto_rawDescOnce.Do(func() {
		file_husi_v1_app_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_husi_v1_app_proto_rawDesc), len(file_husi_v1_app_proto_rawDesc)))
	})
	return file_husi_v1_app_proto_rawDescData
}

var file_husi_v1_app_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_husi_v1_app_proto_goTypes = []any{
	(*ShowWindowRequest)(nil),         // 0: husi.v1.ShowWindowRequest
	(*ShowWindowResponse)(nil),        // 1: husi.v1.ShowWindowResponse
	(*DispatchDeepLinksRequest)(nil),  // 2: husi.v1.DispatchDeepLinksRequest
	(*DispatchDeepLinksResponse)(nil), // 3: husi.v1.DispatchDeepLinksResponse
	(*RunTaskRequest)(nil),            // 4: husi.v1.RunTaskRequest
	(*RunTaskResponse)(nil),           // 5: husi.v1.RunTaskResponse
}
var file_husi_v1_app_proto_depIdxs = []int32{
	0, // 0: husi.v1.AppService.ShowWindow:input_type -> husi.v1.ShowWindowRequest
	2, // 1: husi.v1.AppService.DispatchDeepLinks:input_type -> husi.v1.DispatchDeepLinksRequest
	4, // 2: husi.v1.AppService.RunTask:input_type -> husi.v1.RunTaskRequest
	1, // 3: husi.v1.AppService.ShowWindow:output_type -> husi.v1.ShowWindowResponse
	3, // 4: husi.v1.AppService.DispatchDeepLinks:output_type -> husi.v1.DispatchDeepLinksResponse
	5, // 5: husi.v1.AppService.RunTask:output_type -> husi.v1.RunTaskResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_husi_v1_app_proto_init() }
func file_husi_v1_app_proto_init() {
	if File_husi_v1_app_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_husi_v1_app_proto_rawDesc), len(file_husi_v1_app_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_husi_v1_app_proto_goTypes,
		DependencyIndexes: file_husi_v1_app_proto_depIdxs,
		MessageInfos:      file_husi_v1_app_proto_msgTypes,
	}.Build()
	File_husi_v1_app_proto = out.File
	file_husi_v1_app_proto_goTypes = nil
	file_husi_v1_app_proto_depIdxs = nil
}
