// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: husi/v1/app.proto

package husiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AppService_ShowWindow_FullMethodName        = "/husi.v1.AppService/ShowWindow"
	AppService_DispatchDeepLinks_FullMethodName = "/husi.v1.AppService/DispatchDeepLinks"
	AppService_RunTask_FullMethodName           = "/husi.v1.AppService/RunTask"
)

// AppServiceClient is the client API for AppService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AppService is served by the UI process itself, on a per-user socket, and is
// what replaces the platform callbacks the core used to make through the FFI.
// A second launch of husi reaches the first one through it, instead of the
// single-instance channel it used before.
type AppServiceClient interface {
	ShowWindow(ctx context.Context, in *ShowWindowRequest, opts ...grpc.CallOption) (*ShowWindowResponse, error)
	DispatchDeepLinks(ctx context.Context, in *DispatchDeepLinksRequest, opts ...grpc.CallOption) (*DispatchDeepLinksResponse, error)
	RunTask(ctx context.Context, in *RunTaskRequest, opts ...grpc.CallOption) (*RunTaskResponse, error)
}

type appServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAppServiceClient(cc grpc.ClientConnInterface) AppServiceClient {
	return &appServiceClient{cc}
}

func (c *appServiceClient) ShowWindow(ctx context.Context, in *ShowWindowRequest, opts ...grpc.CallOption) (*ShowWindowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShowWindowResponse)
	err := c.cc.Invoke(ctx, AppService_ShowWindow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) DispatchDeepLinks(ctx context.Context, in *DispatchDeepLinksRequest, opts ...grpc.CallOption) (*DispatchDeepLinksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DispatchDeepLinksResponse)
	err := c.cc.Invoke(ctx, AppService_DispatchDeepLinks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) RunTask(ctx context.Context, in *RunTaskRequest, opts ...grpc.CallOption) (*RunTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunTaskResponse)
	err := c.cc.Invoke(ctx, AppService_RunTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppServiceServer is the server API for AppService service.
// All implementations must embed UnimplementedAppServiceServer
// for forward compatibility.
//
// AppService is served by the UI process itself, on a per-user socket, and is
// what replaces the platform callbacks the core used to make through the FFI.
// A second launch of husi reaches the first one through it, instead of the
// single-instance channel it used before.
type AppServiceServer interface {
	ShowWindow(context.Context, *ShowWindowRequest) (*ShowWindowResponse, error)
	DispatchDeepLinks(context.Context, *DispatchDeepLinksRequest) (*DispatchDeepLinksResponse, error)
	RunTask(context.Context, *RunTaskRequest) (*RunTaskResponse, error)
	mustEmbedUnimplementedAppServiceServer()
}

// UnimplementedAppServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAppServiceServer struct{}

func (UnimplementedAppServiceServer) ShowWindow(context.Context, *ShowWindowRequest) (*ShowWindowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ShowWindow not implemented")
}
func (UnimplementedAppServiceServer) DispatchDeepLinks(context.Context, *DispatchDeepLinksRequest) (*DispatchDeepLinksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DispatchDeepLinks not implemented")
}
func (UnimplementedAppServiceServer) RunTask(context.Context, *RunTaskRequest) (*RunTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunTask not implemented")
}
func (UnimplementedAppServiceServer) mustEmbedUnimplementedAppServiceServer() {}
func (UnimplementedAppServiceServer) testEmbeddedByValue()                    {}

// UnsafeAppServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AppServiceServer will
// result in compilation errors.
type UnsafeAppServiceServer interface {
	mustEmbedUnimplementedAppServiceServer()
}

func RegisterAppServiceServer(s grpc.ServiceRegistrar, srv AppServiceServer) {
	// If the following call panics, it indicates UnimplementedAppServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AppService_ServiceDesc, srv)
}

func _AppService_ShowWindow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShowWindowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).ShowWindow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppService_ShowWindow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).ShowWindow(ctx, req.(*ShowWindowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_DispatchDeepLinks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DispatchDeepLinksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).DispatchDeepLinks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppService_DispatchDeepLinks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).DispatchDeepLinks(ctx, req.(*DispatchDeepLinksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_RunTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).RunTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppService_RunTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).RunTask(ctx, req.(*RunTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AppService_ServiceDesc is the grpc.ServiceDesc for AppService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AppService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "husi.v1.AppService",
	HandlerType: (*AppServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ShowWindow",
			Handler:    _AppService_ShowWindow_Handler,
		},
		{
			MethodName: "DispatchDeepLinks",
			Handler:    _AppService_DispatchDeepLinks_Handler,
		},
		{
			MethodName: "RunTask",
			Handler:    _AppService_RunTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "husi/v1/app.proto",
}
