// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: husi/v1/application.proto

package husiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SchemaKind int32

const (
	SchemaKind_SCHEMA_KIND_UNSPECIFIED SchemaKind = 0
	SchemaKind_SCHEMA_KIND_CONFIG      SchemaKind = 1
	SchemaKind_SCHEMA_KIND_OUTBOUND    SchemaKind = 2
	SchemaKind_SCHEMA_KIND_DNS_RULE    SchemaKind = 3
)

// Enum value maps for SchemaKind.
var (
	SchemaKind_name = map[int32]string{
		0: "SCHEMA_KIND_UNSPECIFIED",
		1: "SCHEMA_KIND_CONFIG",
		2: "SCHEMA_KIND_OUTBOUND",
		3: "SCHEMA_KIND_DNS_RULE",
	}
	SchemaKind_value = map[string]int32{
		"SCHEMA_KIND_UNSPECIFIED": 0,
		"SCHEMA_KIND_CONFIG":      1,
		"SCHEMA_KIND_OUTBOUND":    2,
		"SCHEMA_KIND_DNS_RULE":    3,
	}
)

func (x SchemaKind) Enum() *SchemaKind {
	p := new(SchemaKind)
	*p = x
	return p
}

func (x SchemaKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SchemaKind) Descriptor() protoreflect.EnumDescriptor {
	return file_husi_v1_application_proto_enumTypes[0].Descriptor()
}

func (SchemaKind) Type() protoreflect.EnumType {
	return &file_husi_v1_application_proto_enumTypes[0]
}

func (x SchemaKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SchemaKind.Descriptor instead.
func (SchemaKind) EnumDescriptor() ([]byte, []int) {
	return file_husi_v1_application_proto_rawDescGZIP(), []int{0}
}

// Mode for GetCert: TLS via HTTPS or QUIC.
type GetCertMode int32

const (
	GetCertMode_GET_CERT_MODE_UNSPECIFIED GetCertMode = 0
	GetCertMode_GET_CERT_MODE_HTTPS       GetCertMode = 1
	GetCertMode_GET_CERT_MODE_QUIC        GetCertMode = 2
)

// Enum value maps for GetCertMode.
var (
	GetCertMode_name = map[int32]string{
		0: "GET_CERT_MODE_UNSPECIFIED",
		1: "GET_CERT_MODE_HTTPS",
		2: "GET_CERT_MODE_QUIC",
	}
	GetCertMode_value = map[string]int32{
		"GET_CERT_MODE_UNSPECIFIED": 0,
		"GET_CERT_MODE_HTTPS":       1,
		"GET_CERT_MODE_QUIC":        2,
	}
)

func (x GetCertMode) Enum() *GetCertMode {
	p := new(GetCertMode)
	*p = x
	return p
}

func (x GetCertMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetCertMode) Descriptor() protoreflect.EnumDescriptor {
	return file_husi_v1_application_proto_enumTypes[1].Descriptor()
}

func (GetCertMode) Type() protoreflect.EnumType {
	return &file_husi_v1_application_proto_enumTypes[1]
}

func (x GetCertMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetCertMode.Descriptor instead.
func (GetCertMode) EnumDescriptor() ([]byte, []int) {
	return file_husi_v1_application_proto_rawDescGZIP(), []int{1}
}

// NAT mapping behaviour from a STUN test. Values mirror sing-box stun.NATMapping
// (0 unknown, 2 endpoint-independent, 3 address-dependent, 4 address-and-port).
type NATMapping int32

const (
	NATMapping_NAT_MAPPING_UNSPECIFIED                NATMapping = 0
	NATMapping_NAT_MAPPING_UNKNOWN                    NATMapping = 1
	NATMapping_NAT_MAPPING_ENDPOINT_INDEPENDENT       NATMapping = 2
	NATMapping_NAT_MAPPING_ADDRESS_DEPENDENT          NATMapping = 3
	NATMapping_NAT_MAPPING_ADDRESS_AND_PORT_DEPENDENT NATMapping = 4
)

// Enum value maps for NATMapping.
var (
	NATMapping_name = map[int32]string{
		0: "NAT_MAPPING_UNSPECIFIED",
		1: "NAT_MAPPING_UNKNOWN",
		2: "NAT_MAPPING_ENDPOINT_INDEPENDENT",
		3: "NAT_MAPPING_ADDRESS_DEPENDENT",
		4: "NAT_MAPPING_ADDRESS_AND_PORT_DEPENDENT",
	}
	NATMapping_value = map[string]int32{
		"NAT_MAPPING_UNSPECIFIED":                0,
		"NAT_MAPPING_UNKNOWN":                    1,
		"NAT_MAPPING_ENDPOINT_INDEPENDENT":       2,
		"NAT_MAPPING_ADDRESS_DEPENDENT":          3,
		"NAT_MAPPING_ADDRESS_AND_PORT_DEPENDENT": 4,
	}
)

func (x NATMapping) Enum() *NATMapping {
	p := new(NATMapping)
	*p = x
	return p
}

func (x NATMapping) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NATMapping) Descriptor() protoreflect.EnumDescriptor {
	return file_husi_v1_application_proto_enumTypes[2].Descriptor()
}

func (NATMapping) Type() protoreflect.EnumType {
	return &file_husi_v1_application_proto_enumTypes[2]
}

func (x NATMapping) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NATMapping.Descriptor instead.
func (NATMapping) EnumDescriptor() ([]byte, []int) {
	return file_husi_v1_application_proto_rawDescGZIP(), []int{2}
}

// NAT filtering behaviour from a STUN test. Values mirror sing-box
// stun.NATFiltering.
type NATFiltering int32

const (
	NATFiltering_NAT_FILTERING_UNSPECIFIED                NATFiltering = 0
	NATFiltering_NAT_FILTERING_UNKNOWN                    NATFiltering = 1
	NATFiltering_NAT_FILTERING_ENDPOINT_INDEPENDENT       NATFiltering = 2
	NATFiltering_NAT_FILTERING_ADDRESS_DEPENDENT          NATFiltering = 3
	NATFiltering_NAT_FILTERING_ADDRESS_AND_PORT_DEPENDENT NATFiltering = 4
)

// Enum value maps for NATFiltering.
var (
	NATFiltering_name = map[int32]string{
		0: "NAT_FILTERING_UNSPECIFIED",
		1: "NAT_FILTERING_UNKNOWN",
		2: "NAT_FILTERING_ENDPOINT_INDEPENDENT",
		3: "NAT_FILTERING_ADDRESS_DEPENDENT",
		4: "NAT_FILTERING_ADDRESS_AND_PORT_DEPENDENT",
	}
	NATFiltering_value = map[string]int32{
		"NAT_FILTERING_UNSPECIFIED":                0,
		"NAT_FILTERING_UNKNOWN":                    1,
		"NAT_FILTERING_ENDPOINT_INDEPENDENT":       2,
		"NAT_FILTERING_ADDRESS_DEPENDENT":          3,
		"NAT_FILTERING_ADDRESS_AND_PORT_DEPENDENT": 4,
	}
)

func (x NATFiltering) Enum() *NATFiltering {
	p := new(NATFiltering)
	*p = x
	return p
}

func (x NATFiltering) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NATFiltering) Descriptor() protoreflect.EnumDescriptor {
	return file_husi_v1_application_proto_enumTypes[3].Descriptor()
}

func (NATFiltering) Type() protoreflect.EnumType {
	return &file_husi_v1_application_proto_enumTypes[3]
}

func (x NATFiltering) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NATFiltering.Descriptor instead.
func (NATFiltering) EnumDescriptor() ([]byte, []int) {
	return file_husi_v1_application_proto_rawDescGZIP(), []int{3}
}

type SpeedTestMode int32

const (
	SpeedTestMode_SPEED_TEST_MODE_UNSPECIFIED SpeedTestMode = 0
	SpeedTestMode_SPEED_TEST_MODE_DOWNLOAD    SpeedTestMode = 1
	SpeedTestMode_SPEED_TEST_MODE_UPLOAD      SpeedTestMode = 2
)

// Enum value maps for SpeedTestMode.
var (
	SpeedTestMode_name = map[int32]string{
		0: "SPEED_TEST_MODE_UNSPECIFIED",
		1: "SPEED_TEST_MODE_DOWNLOAD",
		2: "SPEED_TEST_MODE_UPLOAD",
	}
	SpeedTestMode_value = map[string]int32{
		"SPEED_TEST_MODE_UNSPECIFIED": 0,
		"SPEED_TEST_MODE_DOWNLOAD":    1,
		"SPEED_TEST_MODE_UPLOAD":      2,
	}
)

func (x SpeedTestMode) Enum() *SpeedTestMode {
	p := new(SpeedTestMode)
	*p = x
	return p
}

func (x SpeedTestMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SpeedTestMode) Descriptor() protoreflect.EnumDescriptor {
	return file_husi_v1_application_proto_enumTypes[4].Descriptor()
}

func (SpeedTestMode) Type() protoreflect.EnumType {
	return &file_husi_v1_application_proto_enumTypes[4]
}

func (x SpeedTestMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SpeedTestMode.Descriptor instead.
func (SpeedTestMode) EnumDescriptor() ([]byte, []int) {
	return file_husi_v1_application_proto_rawDescGZIP(), []int{4}
}

type CheckConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        string                 `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckConfigRequest) Reset() {
	*x = CheckConfigRequest{}
	mi := &file_husi_v1_application_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckConfigRequest) ProtoMessage() {}

func (x *CheckConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_application_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckConfigRequest.ProtoReflect.Descriptor instead.
func (*CheckConfigRequest) Descriptor() ([]byte, []int) {
	return file_husi_v1_application_proto_rawDescGZIP(), []int{0}
}

func (x *CheckConfigRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

// An unusable config is reported as an INVALID_ARGUMENT error carrying the
// parser message, so a successful response has nothing left to say.
type CheckConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckConfigResponse) Reset() {
	*x = CheckConfigResponse{}
	mi := &file_husi_v1_application_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckConfigResponse) ProtoMessage() {}

func (x *CheckConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_application_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckConfigResponse.ProtoReflect.Descriptor instead.
func (*CheckConfigResponse) Descriptor() ([]byte, []int) {
	return file_husi_v1_application_proto_rawDescGZIP(), []int{1}
}

type GenerateSchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          SchemaKind             `protobuf:"varint,1,opt,name=kind,proto3,enum=husi.v1.SchemaKind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateSchemaRequest) Reset() {
	*x = GenerateSchemaRequest{}
	mi := &file_husi_v1_application_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateSchemaRequest) ProtoMessage() {}

func (x *GenerateSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_application_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateSchemaRequest.ProtoReflect.Descriptor instead.
func (*GenerateSchemaRequest) Descriptor() ([]byte, []int) {
	return file_husi_v1_application_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateSchemaRequest) GetKind() SchemaKind {
	if x != nil {
		return x.Kind
	}
	return SchemaKind_SCHEMA_KIND_UNSPECIFIED
}

type GenerateSchemaResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JSON Schema document.
	Schema        string `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateSchemaResponse) Reset() {
	*x = GenerateSchemaResponse{}
	mi := &file_husi_v1_application_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateSchemaResponse) ProtoMessage() {}

func (x *GenerateSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_application_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateSchemaResponse.ProtoReflect.Descriptor instead.
func (*GenerateSchemaResponse) Descriptor() ([]byte, []int) {
	return file_husi_v1_application_proto_rawDescGZIP(), []int{3}
}

func (x *GenerateSchemaResponse) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

// StandaloneURLTest starts a throwaway instance from config, tests through it
// and closes it, leaving any running service untouched.
type StandaloneURLTestRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Config string                 `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	// Empty selects the default outbound of the throwaway instance.
	OutboundTag string `protobuf:"bytes,2,opt,name=outbound_tag,json=outboundTag,proto3" json:"outbound_tag,omitempty"`
	// Empty selects the host default test URL.
	Link      string          `protobuf:"bytes,3,opt,name=link,proto3" json:"link,omitempty"`
	TimeoutMs int32           `protobuf:"varint,4,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	Options   *URLTestOptions `protobuf:"bytes,5,opt,name=options,proto3" json:"options,omitempty"`
	// Spawned by the host for the duration of the test, same rules and trust
	// model as StartServiceRequest.plugins.
	Plugins       []*PluginProcessSpec `protobuf:"bytes,6,rep,name=plugins,proto3" json:"plugins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StandaloneURLTestRequest) Reset() {
	*x = StandaloneURLTestRequest{}
	mi := &file_husi_v1_application_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StandaloneURLTestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StandaloneURLTestRequest) ProtoMessage() {}

func (x *StandaloneURLTestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_application_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StandaloneURLTestRequest.ProtoReflect.Descriptor instead.
func (*StandaloneURLTestRequest) Descriptor() ([]byte, []int) {
	return file_husi_v1_application_proto_rawDescGZIP(), []int{4}
}

func (x *StandaloneURLTestRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *StandaloneURLTestRequest) GetOutboundTag() string {
	if x != nil {
		return x.OutboundTag
	}
	return ""
}

func (x *StandaloneURLTestRequest) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *StandaloneURLTestRequest) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *StandaloneURLTestRequest) GetOptions() *URLTestOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *StandaloneURLTestRequest) GetPlugins() []*PluginProcessSpec {
	if x != nil {
		return x.Plugins
	}
	return nil
}

type StandaloneURLTestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LatencyMs     int32                  `protobuf:"varint,1,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StandaloneURLTestResponse) Reset() {
	*x = StandaloneURLTestResponse{}
	mi := &file_husi_v1_application_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StandaloneURLTestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StandaloneURLTestResponse) ProtoMessage() {}

func (x *StandaloneURLTestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_application_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StandaloneURLTestResponse.ProtoReflect.Descriptor instead.
func (*StandaloneURLTestResponse) Descriptor() ([]byte, []int) {
	return file_husi_v1_application_proto_rawDescGZIP(), []int{5}
}

func (x *StandaloneURLTestResponse) GetLatencyMs() int32 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

type GetCertRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// host:port of the peer; port defaults to 443 on the host when empty.
	Server string `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	// SNI; empty means the server address itself.
	ServerName string      `protobuf:"bytes,2,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	Mode       GetCertMode `protobuf:"varint,3,opt,name=mode,proto3,enum=husi.v1.GetCertMode" json:"mode,omitempty"`
	// Optional socks proxy URL (socks5://…); empty dials directly.
	SocksProxyUrl string `protobuf:"bytes,4,opt,name=socks_proxy_url,json=socksProxyUrl,proto3" json:"socks_proxy_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCertRequest) Reset() {
	*x = GetCertRequest{}
	mi := &file_husi_v1_application_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCertRequest) ProtoMessage() {}

func (x *GetCertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_application_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCertRequest.ProtoReflect.Descriptor instead.
func (*GetCertRequest) Descriptor() ([]byte, []int) {
	return file_husi_v1_application_proto_rawDescGZIP(), []int{6}
}

func (x *GetCertRequest) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *GetCertRequest) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *GetCertRequest) GetMode() GetCertMode {
	if x != nil {
		return x.Mode
	}
	return GetCertMode_GET_CERT_MODE_UNSPECIFIED
}

func (x *GetCertRequest) GetSocksProxyUrl() string {
	if x != nil {
		return x.SocksProxyUrl
	}
	return ""
}

type GetCertResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// PEM-encoded certificate chain.
	Pem           string `protobuf:"bytes,1,opt,name=pem,proto3" json:"pem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCertResponse) Reset() {
	*x = GetCertResponse{}
	mi := &file_husi_v1_application_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCertResponse) ProtoMessage() {}

func (x *GetCertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_application_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCertResponse.ProtoReflect.Descriptor instead.
func (*GetCertResponse) Descriptor() ([]byte, []int) {
	return file_husi_v1_application_proto_rawDescGZIP(), []int{7}
}

func (x *GetCertResponse) GetPem() string {
	if x != nil {
		return x.Pem
	}
	return ""
}

type STUNTestRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Server string                 `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	// Optional socks proxy URL; empty dials directly.
	SocksProxyUrl string `protobuf:"bytes,2,opt,name=socks_proxy_url,json=socksProxyUrl,proto3" json:"socks_proxy_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *STUNTestRequest) Reset() {
	*x = STUNTestRequest{}
	mi := &file_husi_v1_application_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *STUNTestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*STUNTestRequest) ProtoMessage() {}

func (x *STUNTestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_application_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use STUNTestRequest.ProtoReflect.Descriptor instead.
func (*STUNTestRequest) Descriptor() ([]byte, []int) {
	return file_husi_v1_application_proto_rawDescGZIP(), []int{8}
}

func (x *STUNTestRequest) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *STUNTestRequest) GetSocksProxyUrl() string {
	if x != nil {
		return x.SocksProxyUrl
	}
	return ""
}

// Progress and final result of a STUN test. The stream ends after a message
// with done=true, or with a gRPC error status.
type STUNTestResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ExternalAddress  string                 `protobuf:"bytes,1,opt,name=external_address,json=externalAddress,proto3" json:"external_address,omitempty"`
	LatencyMs        int32                  `protobuf:"varint,2,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	Mapping          NATMapping             `protobuf:"varint,3,opt,name=mapping,proto3,enum=husi.v1.NATMapping" json:"mapping,omitempty"`
	Filtering        NATFiltering           `protobuf:"varint,4,opt,name=filtering,proto3,enum=husi.v1.NATFiltering" json:"filtering,omitempty"`
	NatTypeSupported bool                   `protobuf:"varint,5,opt,name=nat_type_supported,json=natTypeSupported,proto3" json:"nat_type_supported,omitempty"`
	// Host-formatted display strings so the UI does not reimplement NAT labels.
	MappingDisplay   string `protobuf:"bytes,6,opt,name=mapping_display,json=mappingDisplay,proto3" json:"mapping_display,omitempty"`
	FilteringDisplay string `protobuf:"bytes,7,opt,name=filtering_display,json=filteringDisplay,proto3" json:"filtering_display,omitempty"`
	Done             bool   `protobuf:"varint,8,opt,name=done,proto3" json:"done,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *STUNTestResponse) Reset() {
	*x = STUNTestResponse{}
	mi := &file_husi_v1_application_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *STUNTestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*STUNTestResponse) ProtoMessage() {}

func (x *STUNTestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_application_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use STUNTestResponse.ProtoReflect.Descriptor instead.
func (*STUNTestResponse) Descriptor() ([]byte, []int) {
	return file_husi_v1_application_proto_rawDescGZIP(), []int{9}
}

func (x *STUNTestResponse) GetExternalAddress() string {
	if x != nil {
		return x.ExternalAddress
	}
	return ""
}

func (x *STUNTestResponse) GetLatencyMs() int32 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *STUNTestResponse) GetMapping() NATMapping {
	if x != nil {
		return x.Mapping
	}
	return NATMapping_NAT_MAPPING_UNSPECIFIED
}

func (x *STUNTestResponse) GetFiltering() NATFiltering {
	if x != nil {
		return x.Filtering
	}
	return NATFiltering_NAT_FILTERING_UNSPECIFIED
}

func (x *STUNTestResponse) GetNatTypeSupported() bool {
	if x != nil {
		return x.NatTypeSupported
	}
	return false
}

func (x *STUNTestResponse) GetMappingDisplay() string {
	if x != nil {
		return x.MappingDisplay
	}
	return ""
}

func (x *STUNTestResponse) GetFilteringDisplay() string {
	if x != nil {
		return x.FilteringDisplay
	}
	return ""
}

func (x *STUNTestResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

type SpeedTestRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Mode      SpeedTestMode          `protobuf:"varint,1,opt,name=mode,proto3,enum=husi.v1.SpeedTestMode" json:"mode,omitempty"`
	Url       string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	TimeoutMs int32                  `protobuf:"varint,3,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	// Body size for upload mode; ignored for download.
	UploadLengthBytes int64 `protobuf:"varint,4,opt,name=upload_length_bytes,json=uploadLengthBytes,proto3" json:"upload_length_bytes,omitempty"`
	// Optional socks proxy URL; empty dials directly.
	SocksProxyUrl string `protobuf:"bytes,5,opt,name=socks_proxy_url,json=socksProxyUrl,proto3" json:"socks_proxy_url,omitempty"`
	UserAgent     string `protobuf:"bytes,6,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpeedTestRequest) Reset() {
	*x = SpeedTestRequest{}
	mi := &file_husi_v1_application_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpeedTestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpeedTestRequest) ProtoMessage() {}

func (x *SpeedTestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_application_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpeedTestRequest.ProtoReflect.Descriptor instead.
func (*SpeedTestRequest) Descriptor() ([]byte, []int) {
	return file_husi_v1_application_proto_rawDescGZIP(), []int{10}
}

func (x *SpeedTestRequest) GetMode() SpeedTestMode {
	if x != nil {
		return x.Mode
	}
	return SpeedTestMode_SPEED_TEST_MODE_UNSPECIFIED
}

func (x *SpeedTestRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *SpeedTestRequest) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *SpeedTestRequest) GetUploadLengthBytes() int64 {
	if x != nil {
		return x.UploadLengthBytes
	}
	return 0
}

func (x *SpeedTestRequest) GetSocksProxyUrl() string {
	if x != nil {
		return x.SocksProxyUrl
	}
	return ""
}

func (x *SpeedTestRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

// Throttled (~10/s) progress for a speed test. The stream ends when the
// transfer completes or the client cancels.
type SpeedTestResponse struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	BytesPerSec int64                  `protobuf:"varint,1,opt,name=bytes_per_sec,json=bytesPerSec,proto3" json:"bytes_per_sec,omitempty"`
	// Fraction 0..1; negative means indeterminate (unknown content length).
	Progress         float64 `protobuf:"fixed64,2,opt,name=progress,proto3" json:"progress,omitempty"`
	BytesTransferred int64   `protobuf:"varint,3,opt,name=bytes_transferred,json=bytesTransferred,proto3" json:"bytes_transferred,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SpeedTestResponse) Reset() {
	*x = SpeedTestResponse{}
	mi := &file_husi_v1_application_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpeedTestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpeedTestResponse) ProtoMessage() {}

func (x *SpeedTestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_application_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpeedTestResponse.ProtoReflect.Descriptor instead.
func (*SpeedTestResponse) Descriptor() ([]byte, []int) {
	return file_husi_v1_application_proto_rawDescGZIP(), []int{11}
}

func (x *SpeedTestResponse) GetBytesPerSec() int64 {
	if x != nil {
		return x.BytesPerSec
	}
	return 0
}

func (x *SpeedTestResponse) GetProgress() float64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *SpeedTestResponse) GetBytesTransferred() int64 {
	if x != nil {
		return x.BytesTransferred
	}
	return 0
}

var File_husi_v1_application_proto protoreflect.FileDescriptor

const file_husi_v1_application_proto_rawDesc = "" +
	"\n" +
	"\x19husi/v1/application.proto\x12\ahusi.v1\x1a\x12husi/v1/core.proto\x1a\x14husi/v1/daemon.proto\",\n" +
	"\x12CheckConfigRequest\x12\x16\n" +
	"\x06config\x18\x01 \x01(\tR\x06config\"\x15\n" +
	"\x13CheckConfigResponse\"@\n" +
	"\x15GenerateSchemaRequest\x12'\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x13.husi.v1.SchemaKindR\x04kind\"0\n" +
	"\x16GenerateSchemaResponse\x12\x16\n" +
	"\x06schema\x18\x01 \x01(\tR\x06schema\"\xf1\x01\n" +
	"\x18StandaloneURLTestRequest\x12\x16\n" +
	"\x06config\x18\x01 \x01(\tR\x06config\x12!\n" +
	"\foutbound_tag\x18\x02 \x01(\tR\voutboundTag\x12\x12\n" +
	"\x04link\x18\x03 \x01(\tR\x04link\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x04 \x01(\x05R\ttimeoutMs\x121\n" +
	"\aoptions\x18\x05 \x01(\v2\x17.husi.v1.URLTestOptionsR\aoptions\x124\n" +
	"\aplugins\x18\x06 \x03(\v2\x1a.husi.v1.PluginProcessSpecR\aplugins\":\n" +
	"\x19StandaloneURLTestResponse\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x01 \x01(\x05R\tlatencyMs\"\x9b\x01\n" +
	"\x0eGetCertRequest\x12\x16\n" +
	"\x06server\x18\x01 \x01(\tR\x06server\x12\x1f\n" +
	"\vserver_name\x18\x02 \x01(\tR\n" +
	"serverName\x12(\n" +
	"\x04mode\x18\x03 \x01(\x0e2\x14.husi.v1.GetCertModeR\x04mode\x12&\n" +
	"\x0fsocks_proxy_url\x18\x04 \x01(\tR\rsocksProxyUrl\"#\n" +
	"\x0fGetCertResponse\x12\x10\n" +
	"\x03pem\x18\x01 \x01(\tR\x03pem\"Q\n" +
	"\x0fSTUNTestRequest\x12\x16\n" +
	"\x06server\x18\x01 \x01(\tR\x06server\x12&\n" +
	"\x0fsocks_proxy_url\x18\x02 \x01(\tR\rsocksProxyUrl\"\xd8\x02\n" +
	"\x10STUNTestResponse\x12)\n" +
	"\x10external_address\x18\x01 \x01(\tR\x0fexternalAddress\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x02 \x01(\x05R\tlatencyMs\x12-\n" +
	"\amapping\x18\x03 \x01(\x0e2\x13.husi.v1.NATMappingR\amapping\x123\n" +
	"\tfiltering\x18\x04 \x01(\x0e2\x15.husi.v1.NATFilteringR\tfiltering\x12,\n" +
	"\x12nat_type_supported\x18\x05 \x01(\bR\x10natTypeSupported\x12'\n" +
	"\x0fmapping_display\x18\x06 \x01(\tR\x0emappingDisplay\x12+\n" +
	"\x11filtering_display\x18\a \x01(\tR\x10filteringDisplay\x12\x12\n" +
	"\x04done\x18\b \x01(\bR\x04done\"\xe6\x01\n" +
	"\x10SpeedTestRequest\x12*\n" +
	"\x04mode\x18\x01 \x01(\x0e2\x16.husi.v1.SpeedTestModeR\x04mode\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x03 \x01(\x05R\ttimeoutMs\x12.\n" +
	"\x13upload_length_bytes\x18\x04 \x01(\x03R\x11uploadLengthBytes\x12&\n" +
	"\x0fsocks_proxy_url\x18\x05 \x01(\tR\rsocksProxyUrl\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x06 \x01(\tR\tuserAgent\"\x80\x01\n" +
	"\x11SpeedTestResponse\x12\"\n" +
	"\rbytes_per_sec\x18\x01 \x01(\x03R\vbytesPerSec\x12\x1a\n" +
	"\bprogress\x18\x02 \x01(\x01R\bprogress\x12+\n" +
	"\x11bytes_transferred\x18\x03 \x01(\x03R\x10bytesTransferred*u\n" +
	"\n" +
	"SchemaKind\x12\x1b\n" +
	"\x17SCHEMA_KIND_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12SCHEMA_KIND_CONFIG\x10\x01\x12\x18\n" +
	"\x14SCHEMA_KIND_OUTBOUND\x10\x02\x12\x18\n" +
	"\x14SCHEMA_KIND_DNS_RULE\x10\x03*]\n" +
	"\vGetCertMode\x12\x1d\n" +
	"\x19GET_CERT_MODE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13GET_CERT_MODE_HTTPS\x10\x01\x12\x16\n" +
	"\x12GET_CERT_MODE_QUIC\x10\x02*\xb7\x01\n" +
	"\n" +
	"NATMapping\x12\x1b\n" +
	"\x17NAT_MAPPING_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13NAT_MAPPING_UNKNOWN\x10\x01\x12$\n" +
	" NAT_MAPPING_ENDPOINT_INDEPENDENT\x10\x02\x12!\n" +
	"\x1dNAT_MAPPING_ADDRESS_DEPENDENT\x10\x03\x12*\n" +
	"&NAT_MAPPING_ADDRESS_AND_PORT_DEPENDENT\x10\x04*\xc3\x01\n" +
	"\fNATFiltering\x12\x1d\n" +
	"\x19NAT_FILTERING_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15NAT_FILTERING_UNKNOWN\x10\x01\x12&\n" +
	"\"NAT_FILTERING_ENDPOINT_INDEPENDENT\x10\x02\x12#\n" +
	"\x1fNAT_FILTERING_ADDRESS_DEPENDENT\x10\x03\x12,\n" +
	"(NAT_FILTERING_ADDRESS_AND_PORT_DEPENDENT\x10\x04*j\n" +
	"\rSpeedTestMode\x12\x1f\n" +
	"\x1bSPEED_TEST_MODE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18SPEED_TEST_MODE_DOWNLOAD\x10\x01\x12\x1a\n" +
	"\x16SPEED_TEST_MODE_UPLOAD\x10\x022\xd4\x03\n" +
	"\x12ApplicationService\x12H\n" +
	"\vCheckConfig\x12\x1b.husi.v1.CheckConfigRequest\x1a\x1c.husi.v1.CheckConfigResponse\x12Q\n" +
	"\x0eGenerateSchema\x12\x1e.husi.v1.GenerateSchemaRequest\x1a\x1f.husi.v1.GenerateSchemaResponse\x12Z\n" +
	"\x11StandaloneURLTest\x12!.husi.v1.StandaloneURLTestRequest\x1a\".husi.v1.StandaloneURLTestResponse\x12<\n" +
	"\aGetCert\x12\x17.husi.v1.GetCertRequest\x1a\x18.husi.v1.GetCertResponse\x12A\n" +
	"\bSTUNTest\x12\x18.husi.v1.STUNTestRequest\x1a\x19.husi.v1.STUNTestResponse0\x01\x12D\n" +
	"\tSpeedTest\x12\x19.husi.v1.SpeedTestRequest\x1a\x1a.husi.v1.SpeedTestResponse0\x01BA\n" +
	"\x10fr.husi.proto.v1B\x10ApplicationProtoP\x01Z\x19libcore/pb/husi/v1;husiv1b\x06proto3"

var (
	file_husi_v1_application_proto_rawDescOnce sync.Once
	file_husi_v1_application_proto_rawDescData []byte
)

func file_husi_v1_application_proto_rawDescGZIP() []byte {
	file_husi_v1_application_proto_rawDescOnce.Do(func() {
		file_husi_v1_application_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_husi_v1_application_proto_rawDesc), len(file_husi_v1_application_proto_rawDesc)))
	})
	return file_husi_v1_application_proto_rawDescData
}

var file_husi_v1_application_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_husi_v1_application_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_husi_v1_application_proto_goTypes = []any{
	(SchemaKind)(0),                   // 0: husi.v1.SchemaKind
	(GetCertMode)(0),                  // 1: husi.v1.GetCertMode
	(NATMapping)(0),                   // 2: husi.v1.NATMapping
	(NATFiltering)(0),                 // 3: husi.v1.NATFiltering
	(SpeedTestMode)(0),                // 4: husi.v1.SpeedTestMode
	(*CheckConfigRequest)(nil),        // 5: husi.v1.CheckConfigRequest
	(*CheckConfigResponse)(nil),       // 6: husi.v1.CheckConfigResponse
	(*GenerateSchemaRequest)(nil),     // 7: husi.v1.GenerateSchemaRequest
	(*GenerateSchemaResponse)(nil),    // 8: husi.v1.GenerateSchemaResponse
	(*StandaloneURLTestRequest)(nil),  // 9: husi.v1.StandaloneURLTestRequest
	(*StandaloneURLTestResponse)(nil), // 10: husi.v1.StandaloneURLTestResponse
	(*GetCertRequest)(nil),            // 11: husi.v1.GetCertRequest
	(*GetCertResponse)(nil),           // 12: husi.v1.GetCertResponse
	(*STUNTestRequest)(nil),           // 13: husi.v1.STUNTestRequest
	(*STUNTestResponse)(nil),          // 14: husi.v1.STUNTestResponse
	(*SpeedTestRequest)(nil),          // 15: husi.v1.SpeedTestRequest
	(*SpeedTestResponse)(nil),         // 16: husi.v1.SpeedTestResponse
	(*URLTestOptions)(nil),            // 17: husi.v1.URLTestOptions
	(*PluginProcessSpec)(nil),         // 18: husi.v1.PluginProcessSpec
}
var file_husi_v1_application_proto_depIdxs = []int32{
	0,  // 0: husi.v1.GenerateSchemaRequest.kind:type_name -> husi.v1.SchemaKind
	17, // 1: husi.v1.StandaloneURLTestRequest.options:type_name -> husi.v1.URLTestOptions
	18, // 2: husi.v1.StandaloneURLTestRequest.plugins:type_name -> husi.v1.PluginProcessSpec
	1,  // 3: husi.v1.GetCertRequest.mode:type_name -> husi.v1.GetCertMode
	2,  // 4: husi.v1.STUNTestResponse.mapping:type_name -> husi.v1.NATMapping
	3,  // 5: husi.v1.STUNTestResponse.filtering:type_name -> husi.v1.NATFiltering
	4,  // 6: husi.v1.SpeedTestRequest.mode:type_name -> husi.v1.SpeedTestMode
	5,  // 7: husi.v1.ApplicationService.CheckConfig:input_type -> husi.v1.CheckConfigRequest
	7,  // 8: husi.v1.ApplicationService.GenerateSchema:input_type -> husi.v1.GenerateSchemaRequest
	9,  // 9: husi.v1.ApplicationService.StandaloneURLTest:input_type -> husi.v1.StandaloneURLTestRequest
	11, // 10: husi.v1.ApplicationService.GetCert:input_type -> husi.v1.GetCertRequest
	13, // 11: husi.v1.ApplicationService.STUNTest:input_type -> husi.v1.STUNTestRequest
	15, // 12: husi.v1.ApplicationService.SpeedTest:input_type -> husi.v1.SpeedTestRequest
	6,  // 13: husi.v1.ApplicationService.CheckConfig:output_type -> husi.v1.CheckConfigResponse
	8,  // 14: husi.v1.ApplicationService.GenerateSchema:output_type -> husi.v1.GenerateSchemaResponse
	10, // 15: husi.v1.ApplicationService.StandaloneURLTest:output_type -> husi.v1.StandaloneURLTestResponse
	12, // 16: husi.v1.ApplicationService.GetCert:output_type -> husi.v1.GetCertResponse
	14, // 17: husi.v1.ApplicationService.STUNTest:output_type -> husi.v1.STUNTestResponse
	16, // 18: husi.v1.ApplicationService.SpeedTest:output_type -> husi.v1.SpeedTestResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_husi_v1_application_proto_init() }
func file_husi_v1_application_proto_init() {
	if File_husi_v1_application_proto != nil {
		return
	}
	file_husi_v1_core_proto_init()
	file_husi_v1_daemon_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_husi_v1_application_proto_rawDesc), len(file_husi_v1_application_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_husi_v1_application_proto_goTypes,
		DependencyIndexes: file_husi_v1_application_proto_depIdxs,
		EnumInfos:         file_husi_v1_application_proto_enumTypes,
		MessageInfos:      file_husi_v1_application_proto_msgTypes,
	}.Build()
	File_husi_v1_application_proto = out.File
	file_husi_v1_application_proto_goTypes = nil
	file_husi_v1_application_proto_depIdxs = nil
}
