// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: husi/v1/application.proto

package husiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ApplicationService_CheckConfig_FullMethodName       = "/husi.v1.ApplicationService/CheckConfig"
	ApplicationService_GenerateSchema_FullMethodName    = "/husi.v1.ApplicationService/GenerateSchema"
	ApplicationService_StandaloneURLTest_FullMethodName = "/husi.v1.ApplicationService/StandaloneURLTest"
	ApplicationService_GetCert_FullMethodName           = "/husi.v1.ApplicationService/GetCert"
	ApplicationService_STUNTest_FullMethodName          = "/husi.v1.ApplicationService/STUNTest"
	ApplicationService_SpeedTest_FullMethodName         = "/husi.v1.ApplicationService/SpeedTest"
)

// ApplicationServiceClient is the client API for ApplicationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ApplicationService covers work that needs no running instance but does need
// the protocol registry of the host that will run the config. Evaluating these
// inside the UI would answer for the UI's registry, which is deliberately
// slimmer than the core host's.
//
// sing-box's desktop.ApplicationService answers the same kind of question, but
// its generated Go lives in a main package that nothing can import, and husi's
// schema generation is driven by husi's own option codegen. So this one is
// husi's, unlike the core-scoped contract shared with sing-box verbatim.
//
// Network tools (GetCert, STUN, SpeedTest) execute in the core host so they
// share the host's protocol registry, socks path and cancellation model —
// same placement as StandaloneURLTest (D6).
type ApplicationServiceClient interface {
	CheckConfig(ctx context.Context, in *CheckConfigRequest, opts ...grpc.CallOption) (*CheckConfigResponse, error)
	GenerateSchema(ctx context.Context, in *GenerateSchemaRequest, opts ...grpc.CallOption) (*GenerateSchemaResponse, error)
	StandaloneURLTest(ctx context.Context, in *StandaloneURLTestRequest, opts ...grpc.CallOption) (*StandaloneURLTestResponse, error)
	GetCert(ctx context.Context, in *GetCertRequest, opts ...grpc.CallOption) (*GetCertResponse, error)
	STUNTest(ctx context.Context, in *STUNTestRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[STUNTestResponse], error)
	SpeedTest(ctx context.Context, in *SpeedTestRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SpeedTestResponse], error)
}

type applicationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewApplicationServiceClient(cc grpc.ClientConnInterface) ApplicationServiceClient {
	return &applicationServiceClient{cc}
}

func (c *applicationServiceClient) CheckConfig(ctx context.Context, in *CheckConfigRequest, opts ...grpc.CallOption) (*CheckConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckConfigResponse)
	err := c.cc.Invoke(ctx, ApplicationService_CheckConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServiceClient) GenerateSchema(ctx context.Context, in *GenerateSchemaRequest, opts ...grpc.CallOption) (*GenerateSchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateSchemaResponse)
	err := c.cc.Invoke(ctx, ApplicationService_GenerateSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServiceClient) StandaloneURLTest(ctx context.Context, in *StandaloneURLTestRequest, opts ...grpc.CallOption) (*StandaloneURLTestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StandaloneURLTestResponse)
	err := c.cc.Invoke(ctx, ApplicationService_StandaloneURLTest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServiceClient) GetCert(ctx context.Context, in *GetCertRequest, opts ...grpc.CallOption) (*GetCertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCertResponse)
	err := c.cc.Invoke(ctx, ApplicationService_GetCert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServiceClient) STUNTest(ctx context.Context, in *STUNTestRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[STUNTestResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ApplicationService_ServiceDesc.Streams[0], ApplicationService_STUNTest_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[STUNTestRequest, STUNTestResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ApplicationService_STUNTestClient = grpc.ServerStreamingClient[STUNTestResponse]

func (c *applicationServiceClient) SpeedTest(ctx context.Context, in *SpeedTestRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SpeedTestResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ApplicationService_ServiceDesc.Streams[1], ApplicationService_SpeedTest_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SpeedTestRequest, SpeedTestResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ApplicationService_SpeedTestClient = grpc.ServerStreamingClient[SpeedTestResponse]

// ApplicationServiceServer is the server API for ApplicationService service.
// All implementations must embed UnimplementedApplicationServiceServer
// for forward compatibility.
//
// ApplicationService covers work that needs no running instance but does need
// the protocol registry of the host that will run the config. Evaluating these
// inside the UI would answer for the UI's registry, which is deliberately
// slimmer than the core host's.
//
// sing-box's desktop.ApplicationService answers the same kind of question, but
// its generated Go lives in a main package that nothing can import, and husi's
// schema generation is driven by husi's own option codegen. So this one is
// husi's, unlike the core-scoped contract shared with sing-box verbatim.
//
// Network tools (GetCert, STUN, SpeedTest) execute in the core host so they
// share the host's protocol registry, socks path and cancellation model —
// same placement as StandaloneURLTest (D6).
type ApplicationServiceServer interface {
	CheckConfig(context.Context, *CheckConfigRequest) (*CheckConfigResponse, error)
	GenerateSchema(context.Context, *GenerateSchemaRequest) (*GenerateSchemaResponse, error)
	StandaloneURLTest(context.Context, *StandaloneURLTestRequest) (*StandaloneURLTestResponse, error)
	GetCert(context.Context, *GetCertRequest) (*GetCertResponse, error)
	STUNTest(*STUNTestRequest, grpc.ServerStreamingServer[STUNTestResponse]) error
	SpeedTest(*SpeedTestRequest, grpc.ServerStreamingServer[SpeedTestResponse]) error
	mustEmbedUnimplementedApplicationServiceServer()
}

// UnimplementedApplicationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedApplicationServiceServer struct{}

func (UnimplementedApplicationServiceServer) CheckConfig(context.Context, *CheckConfigRequest) (*CheckConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckConfig not implemented")
}
func (UnimplementedApplicationServiceServer) GenerateSchema(context.Context, *GenerateSchemaRequest) (*GenerateSchemaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateSchema not implemented")
}
func (UnimplementedApplicationServiceServer) StandaloneURLTest(context.Context, *StandaloneURLTestRequest) (*StandaloneURLTestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StandaloneURLTest not implemented")
}
func (UnimplementedApplicationServiceServer) GetCert(context.Context, *GetCertRequest) (*GetCertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCert not implemented")
}
func (UnimplementedApplicationServiceServer) STUNTest(*STUNTestRequest, grpc.ServerStreamingServer[STUNTestResponse]) error {
	return status.Error(codes.Unimplemented, "method STUNTest not implemented")
}
func (UnimplementedApplicationServiceServer) SpeedTest(*SpeedTestRequest, grpc.ServerStreamingServer[SpeedTestResponse]) error {
	return status.Error(codes.Unimplemented, "method SpeedTest not implemented")
}
func (UnimplementedApplicationServiceServer) mustEmbedUnimplementedApplicationServiceServer() {}
func (UnimplementedApplicationServiceServer) testEmbeddedByValue()                            {}

// UnsafeApplicationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApplicationServiceServer will
// result in compilation errors.
type UnsafeApplicationServiceServer interface {
	mustEmbedUnimplementedApplicationServiceServer()
}

func RegisterApplicationServiceServer(s grpc.ServiceRegistrar, srv ApplicationServiceServer) {
	// If the following call panics, it indicates UnimplementedApplicationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ApplicationService_ServiceDesc, srv)
}

func _ApplicationService_CheckConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).CheckConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationService_CheckConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).CheckConfig(ctx, req.(*CheckConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationService_GenerateSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).GenerateSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationService_GenerateSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).GenerateSchema(ctx, req.(*GenerateSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationService_StandaloneURLTest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StandaloneURLTestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).StandaloneURLTest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationService_StandaloneURLTest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).StandaloneURLTest(ctx, req.(*StandaloneURLTestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationService_GetCert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).GetCert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationService_GetCert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).GetCert(ctx, req.(*GetCertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationService_STUNTest_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(STUNTestRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ApplicationServiceServer).STUNTest(m, &grpc.GenericServerStream[STUNTestRequest, STUNTestResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ApplicationService_STUNTestServer = grpc.ServerStreamingServer[STUNTestResponse]

func _ApplicationService_SpeedTest_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SpeedTestRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ApplicationServiceServer).SpeedTest(m, &grpc.GenericServerStream[SpeedTestRequest, SpeedTestResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ApplicationService_SpeedTestServer = grpc.ServerStreamingServer[SpeedTestResponse]

// ApplicationService_ServiceDesc is the grpc.ServiceDesc for ApplicationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ApplicationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "husi.v1.ApplicationService",
	HandlerType: (*ApplicationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckConfig",
			Handler:    _ApplicationService_CheckConfig_Handler,
		},
		{
			MethodName: "GenerateSchema",
			Handler:    _ApplicationService_GenerateSchema_Handler,
		},
		{
			MethodName: "StandaloneURLTest",
			Handler:    _ApplicationService_StandaloneURLTest_Handler,
		},
		{
			MethodName: "GetCert",
			Handler:    _ApplicationService_GetCert_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "STUNTest",
			Handler:       _ApplicationService_STUNTest_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SpeedTest",
			Handler:       _ApplicationService_SpeedTest_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "husi/v1/application.proto",
}
