// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: husi/v1/application.proto

package husiv1

import (
	daemon "github.com/sagernet/sing-box/daemon"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SchemaKind int32

const (
	SchemaKind_SCHEMA_KIND_UNSPECIFIED SchemaKind = 0
	SchemaKind_SCHEMA_KIND_CONFIG      SchemaKind = 1
	SchemaKind_SCHEMA_KIND_OUTBOUND    SchemaKind = 2
	SchemaKind_SCHEMA_KIND_DNS_RULE    SchemaKind = 3
)

// Enum value maps for SchemaKind.
var (
	SchemaKind_name = map[int32]string{
		0: "SCHEMA_KIND_UNSPECIFIED",
		1: "SCHEMA_KIND_CONFIG",
		2: "SCHEMA_KIND_OUTBOUND",
		3: "SCHEMA_KIND_DNS_RULE",
	}
	SchemaKind_value = map[string]int32{
		"SCHEMA_KIND_UNSPECIFIED": 0,
		"SCHEMA_KIND_CONFIG":      1,
		"SCHEMA_KIND_OUTBOUND":    2,
		"SCHEMA_KIND_DNS_RULE":    3,
	}
)

func (x SchemaKind) Enum() *SchemaKind {
	p := new(SchemaKind)
	*p = x
	return p
}

func (x SchemaKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SchemaKind) Descriptor() protoreflect.EnumDescriptor {
	return file_husi_v1_application_proto_enumTypes[0].Descriptor()
}

func (SchemaKind) Type() protoreflect.EnumType {
	return &file_husi_v1_application_proto_enumTypes[0]
}

func (x SchemaKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SchemaKind.Descriptor instead.
func (SchemaKind) EnumDescriptor() ([]byte, []int) {
	return file_husi_v1_application_proto_rawDescGZIP(), []int{0}
}

// Mode for GetCert: TLS via HTTPS or QUIC.
type GetCertMode int32

const (
	GetCertMode_GET_CERT_MODE_UNSPECIFIED GetCertMode = 0
	GetCertMode_GET_CERT_MODE_HTTPS       GetCertMode = 1
	GetCertMode_GET_CERT_MODE_QUIC        GetCertMode = 2
)

// Enum value maps for GetCertMode.
var (
	GetCertMode_name = map[int32]string{
		0: "GET_CERT_MODE_UNSPECIFIED",
		1: "GET_CERT_MODE_HTTPS",
		2: "GET_CERT_MODE_QUIC",
	}
	GetCertMode_value = map[string]int32{
		"GET_CERT_MODE_UNSPECIFIED": 0,
		"GET_CERT_MODE_HTTPS":       1,
		"GET_CERT_MODE_QUIC":        2,
	}
)

func (x GetCertMode) Enum() *GetCertMode {
	p := new(GetCertMode)
	*p = x
	return p
}

func (x GetCertMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetCertMode) Descriptor() protoreflect.EnumDescriptor {
	return file_husi_v1_application_proto_enumTypes[1].Descriptor()
}

func (GetCertMode) Type() protoreflect.EnumType {
	return &file_husi_v1_application_proto_enumTypes[1]
}

func (x GetCertMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetCertMode.Descriptor instead.
func (GetCertMode) EnumDescriptor() ([]byte, []int) {
	return file_husi_v1_application_proto_rawDescGZIP(), []int{1}
}

type PingProtocol int32

const (
	PingProtocol_PING_PROTOCOL_UNSPECIFIED PingProtocol = 0
	PingProtocol_PING_PROTOCOL_ICMP        PingProtocol = 1
	PingProtocol_PING_PROTOCOL_TCP         PingProtocol = 2
)

// Enum value maps for PingProtocol.
var (
	PingProtocol_name = map[int32]string{
		0: "PING_PROTOCOL_UNSPECIFIED",
		1: "PING_PROTOCOL_ICMP",
		2: "PING_PROTOCOL_TCP",
	}
	PingProtocol_value = map[string]int32{
		"PING_PROTOCOL_UNSPECIFIED": 0,
		"PING_PROTOCOL_ICMP":        1,
		"PING_PROTOCOL_TCP":         2,
	}
)

func (x PingProtocol) Enum() *PingProtocol {
	p := new(PingProtocol)
	*p = x
	return p
}

func (x PingProtocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PingProtocol) Descriptor() protoreflect.EnumDescriptor {
	return file_husi_v1_application_proto_enumTypes[2].Descriptor()
}

func (PingProtocol) Type() protoreflect.EnumType {
	return &file_husi_v1_application_proto_enumTypes[2]
}

func (x PingProtocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PingProtocol.Descriptor instead.
func (PingProtocol) EnumDescriptor() ([]byte, []int) {
	return file_husi_v1_application_proto_rawDescGZIP(), []int{2}
}

type CheckConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        string                 `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckConfigRequest) Reset() {
	*x = CheckConfigRequest{}
	mi := &file_husi_v1_application_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckConfigRequest) ProtoMessage() {}

func (x *CheckConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_application_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckConfigRequest.ProtoReflect.Descriptor instead.
func (*CheckConfigRequest) Descriptor() ([]byte, []int) {
	return file_husi_v1_application_proto_rawDescGZIP(), []int{0}
}

func (x *CheckConfigRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

// An unusable config is reported as an INVALID_ARGUMENT error carrying the
// parser message, so a successful response has nothing left to say.
type CheckConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckConfigResponse) Reset() {
	*x = CheckConfigResponse{}
	mi := &file_husi_v1_application_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckConfigResponse) ProtoMessage() {}

func (x *CheckConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_application_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckConfigResponse.ProtoReflect.Descriptor instead.
func (*CheckConfigResponse) Descriptor() ([]byte, []int) {
	return file_husi_v1_application_proto_rawDescGZIP(), []int{1}
}

type FormatConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        string                 `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FormatConfigRequest) Reset() {
	*x = FormatConfigRequest{}
	mi := &file_husi_v1_application_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FormatConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormatConfigRequest) ProtoMessage() {}

func (x *FormatConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_application_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormatConfigRequest.ProtoReflect.Descriptor instead.
func (*FormatConfigRequest) Descriptor() ([]byte, []int) {
	return file_husi_v1_application_proto_rawDescGZIP(), []int{2}
}

func (x *FormatConfigRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

// Malformed JSON is reported as an INVALID_ARGUMENT error carrying the parser
// message.
type FormatConfigResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// config re-indented in sing-box style, comments preserved.
	Config        string `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FormatConfigResponse) Reset() {
	*x = FormatConfigResponse{}
	mi := &file_husi_v1_application_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FormatConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormatConfigResponse) ProtoMessage() {}

func (x *FormatConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_application_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormatConfigResponse.ProtoReflect.Descriptor instead.
func (*FormatConfigResponse) Descriptor() ([]byte, []int) {
	return file_husi_v1_application_proto_rawDescGZIP(), []int{3}
}

func (x *FormatConfigResponse) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

type GenerateSchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          SchemaKind             `protobuf:"varint,1,opt,name=kind,proto3,enum=husi.v1.SchemaKind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateSchemaRequest) Reset() {
	*x = GenerateSchemaRequest{}
	mi := &file_husi_v1_application_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateSchemaRequest) ProtoMessage() {}

func (x *GenerateSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_application_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateSchemaRequest.ProtoReflect.Descriptor instead.
func (*GenerateSchemaRequest) Descriptor() ([]byte, []int) {
	return file_husi_v1_application_proto_rawDescGZIP(), []int{4}
}

func (x *GenerateSchemaRequest) GetKind() SchemaKind {
	if x != nil {
		return x.Kind
	}
	return SchemaKind_SCHEMA_KIND_UNSPECIFIED
}

type GenerateSchemaResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JSON Schema document.
	Schema        string `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateSchemaResponse) Reset() {
	*x = GenerateSchemaResponse{}
	mi := &file_husi_v1_application_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateSchemaResponse) ProtoMessage() {}

func (x *GenerateSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_application_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateSchemaResponse.ProtoReflect.Descriptor instead.
func (*GenerateSchemaResponse) Descriptor() ([]byte, []int) {
	return file_husi_v1_application_proto_rawDescGZIP(), []int{5}
}

func (x *GenerateSchemaResponse) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

// StandaloneURLTest starts a throwaway instance from config, tests through it
// and closes it, leaving any running service untouched.
type StandaloneURLTestRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Config string                 `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	// Empty selects the default outbound of the throwaway instance.
	OutboundTag string `protobuf:"bytes,2,opt,name=outbound_tag,json=outboundTag,proto3" json:"outbound_tag,omitempty"`
	// Empty selects the host default test URL.
	Link      string          `protobuf:"bytes,3,opt,name=link,proto3" json:"link,omitempty"`
	TimeoutMs int32           `protobuf:"varint,4,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	Options   *URLTestOptions `protobuf:"bytes,5,opt,name=options,proto3" json:"options,omitempty"`
	// Spawned by the host for the duration of the test, same rules and trust
	// model as StartServiceRequest.plugins.
	Plugins       []*PluginProcessSpec `protobuf:"bytes,6,rep,name=plugins,proto3" json:"plugins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StandaloneURLTestRequest) Reset() {
	*x = StandaloneURLTestRequest{}
	mi := &file_husi_v1_application_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StandaloneURLTestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StandaloneURLTestRequest) ProtoMessage() {}

func (x *StandaloneURLTestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_application_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StandaloneURLTestRequest.ProtoReflect.Descriptor instead.
func (*StandaloneURLTestRequest) Descriptor() ([]byte, []int) {
	return file_husi_v1_application_proto_rawDescGZIP(), []int{6}
}

func (x *StandaloneURLTestRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *StandaloneURLTestRequest) GetOutboundTag() string {
	if x != nil {
		return x.OutboundTag
	}
	return ""
}

func (x *StandaloneURLTestRequest) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *StandaloneURLTestRequest) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *StandaloneURLTestRequest) GetOptions() *URLTestOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *StandaloneURLTestRequest) GetPlugins() []*PluginProcessSpec {
	if x != nil {
		return x.Plugins
	}
	return nil
}

type StandaloneURLTestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LatencyMs     int32                  `protobuf:"varint,1,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StandaloneURLTestResponse) Reset() {
	*x = StandaloneURLTestResponse{}
	mi := &file_husi_v1_application_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StandaloneURLTestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StandaloneURLTestResponse) ProtoMessage() {}

func (x *StandaloneURLTestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_application_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StandaloneURLTestResponse.ProtoReflect.Descriptor instead.
func (*StandaloneURLTestResponse) Descriptor() ([]byte, []int) {
	return file_husi_v1_application_proto_rawDescGZIP(), []int{7}
}

func (x *StandaloneURLTestResponse) GetLatencyMs() int32 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

type GetCertRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// host:port of the peer; port defaults to 443 on the host when empty.
	Server string `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	// SNI; empty means the server address itself.
	ServerName string      `protobuf:"bytes,2,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	Mode       GetCertMode `protobuf:"varint,3,opt,name=mode,proto3,enum=husi.v1.GetCertMode" json:"mode,omitempty"`
	// Optional socks proxy URL (socks5://…); empty dials directly.
	SocksProxyUrl string `protobuf:"bytes,4,opt,name=socks_proxy_url,json=socksProxyUrl,proto3" json:"socks_proxy_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCertRequest) Reset() {
	*x = GetCertRequest{}
	mi := &file_husi_v1_application_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCertRequest) ProtoMessage() {}

func (x *GetCertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_application_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCertRequest.ProtoReflect.Descriptor instead.
func (*GetCertRequest) Descriptor() ([]byte, []int) {
	return file_husi_v1_application_proto_rawDescGZIP(), []int{8}
}

func (x *GetCertRequest) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *GetCertRequest) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *GetCertRequest) GetMode() GetCertMode {
	if x != nil {
		return x.Mode
	}
	return GetCertMode_GET_CERT_MODE_UNSPECIFIED
}

func (x *GetCertRequest) GetSocksProxyUrl() string {
	if x != nil {
		return x.SocksProxyUrl
	}
	return ""
}

type GetCertResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// PEM-encoded certificate chain.
	Pem           string `protobuf:"bytes,1,opt,name=pem,proto3" json:"pem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCertResponse) Reset() {
	*x = GetCertResponse{}
	mi := &file_husi_v1_application_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCertResponse) ProtoMessage() {}

func (x *GetCertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_application_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCertResponse.ProtoReflect.Descriptor instead.
func (*GetCertResponse) Descriptor() ([]byte, []int) {
	return file_husi_v1_application_proto_rawDescGZIP(), []int{9}
}

func (x *GetCertResponse) GetPem() string {
	if x != nil {
		return x.Pem
	}
	return ""
}

// Same fields as sing-box desktop.StandaloneSTUNTestRequest. There is no
// outbound tag: with no service running there is nothing to route through.
type StandaloneSTUNTestRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Empty selects sing-box's default STUN server.
	Server        string `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StandaloneSTUNTestRequest) Reset() {
	*x = StandaloneSTUNTestRequest{}
	mi := &file_husi_v1_application_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StandaloneSTUNTestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StandaloneSTUNTestRequest) ProtoMessage() {}

func (x *StandaloneSTUNTestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_application_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StandaloneSTUNTestRequest.ProtoReflect.Descriptor instead.
func (*StandaloneSTUNTestRequest) Descriptor() ([]byte, []int) {
	return file_husi_v1_application_proto_rawDescGZIP(), []int{10}
}

func (x *StandaloneSTUNTestRequest) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

// Same fields as sing-box desktop.StandaloneNetworkQualityTestRequest.
type StandaloneNetworkQualityTestRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Empty selects sing-box's default responsiveness config URL.
	ConfigUrl string `protobuf:"bytes,1,opt,name=config_url,json=configUrl,proto3" json:"config_url,omitempty"`
	// Measure download and upload one after the other instead of together.
	Serial            bool  `protobuf:"varint,2,opt,name=serial,proto3" json:"serial,omitempty"`
	MaxRuntimeSeconds int32 `protobuf:"varint,3,opt,name=max_runtime_seconds,json=maxRuntimeSeconds,proto3" json:"max_runtime_seconds,omitempty"`
	Http3             bool  `protobuf:"varint,4,opt,name=http3,proto3" json:"http3,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StandaloneNetworkQualityTestRequest) Reset() {
	*x = StandaloneNetworkQualityTestRequest{}
	mi := &file_husi_v1_application_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StandaloneNetworkQualityTestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StandaloneNetworkQualityTestRequest) ProtoMessage() {}

func (x *StandaloneNetworkQualityTestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_application_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StandaloneNetworkQualityTestRequest.ProtoReflect.Descriptor instead.
func (*StandaloneNetworkQualityTestRequest) Descriptor() ([]byte, []int) {
	return file_husi_v1_application_proto_rawDescGZIP(), []int{11}
}

func (x *StandaloneNetworkQualityTestRequest) GetConfigUrl() string {
	if x != nil {
		return x.ConfigUrl
	}
	return ""
}

func (x *StandaloneNetworkQualityTestRequest) GetSerial() bool {
	if x != nil {
		return x.Serial
	}
	return false
}

func (x *StandaloneNetworkQualityTestRequest) GetMaxRuntimeSeconds() int32 {
	if x != nil {
		return x.MaxRuntimeSeconds
	}
	return 0
}

func (x *StandaloneNetworkQualityTestRequest) GetHttp3() bool {
	if x != nil {
		return x.Http3
	}
	return false
}

// Socks inbound on the host's loopback that HTTPFetch dials through.
type HTTPFetchSocks5 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Port          int32                  `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HTTPFetchSocks5) Reset() {
	*x = HTTPFetchSocks5{}
	mi := &file_husi_v1_application_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPFetchSocks5) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPFetchSocks5) ProtoMessage() {}

func (x *HTTPFetchSocks5) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_application_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPFetchSocks5.ProtoReflect.Descriptor instead.
func (*HTTPFetchSocks5) Descriptor() ([]byte, []int) {
	return file_husi_v1_application_proto_rawDescGZIP(), []int{12}
}

func (x *HTTPFetchSocks5) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *HTTPFetchSocks5) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *HTTPFetchSocks5) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// One GET. A status other than 200 fails the call with the start of the body
// in the error message.
type HTTPFetchRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Url     string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Headers map[string]string      `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Leaves the exchange without an overall deadline, for large downloads on
	// slow links. Connection setup still times out, and a body that stops making
	// progress still fails.
	NoOverallDeadline bool `protobuf:"varint,3,opt,name=no_overall_deadline,json=noOverallDeadline,proto3" json:"no_overall_deadline,omitempty"`
	// Forces TLS 1.3.
	RestrictedTls bool `protobuf:"varint,4,opt,name=restricted_tls,json=restrictedTls,proto3" json:"restricted_tls,omitempty"`
	// Hex SHA-256 of a leaf certificate accepted even when it does not chain to
	// a trusted root (OOCv1).
	PinnedSha256 string `protobuf:"bytes,5,opt,name=pinned_sha256,json=pinnedSha256,proto3" json:"pinned_sha256,omitempty"`
	// Unset dials the server directly.
	Socks5 *HTTPFetchSocks5 `protobuf:"bytes,6,opt,name=socks5,proto3" json:"socks5,omitempty"`
	// age identities that decrypt an armored response body.
	AgeIdentities string `protobuf:"bytes,7,opt,name=age_identities,json=ageIdentities,proto3" json:"age_identities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HTTPFetchRequest) Reset() {
	*x = HTTPFetchRequest{}
	mi := &file_husi_v1_application_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPFetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPFetchRequest) ProtoMessage() {}

func (x *HTTPFetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_application_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPFetchRequest.ProtoReflect.Descriptor instead.
func (*HTTPFetchRequest) Descriptor() ([]byte, []int) {
	return file_husi_v1_application_proto_rawDescGZIP(), []int{13}
}

func (x *HTTPFetchRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *HTTPFetchRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HTTPFetchRequest) GetNoOverallDeadline() bool {
	if x != nil {
		return x.NoOverallDeadline
	}
	return false
}

func (x *HTTPFetchRequest) GetRestrictedTls() bool {
	if x != nil {
		return x.RestrictedTls
	}
	return false
}

func (x *HTTPFetchRequest) GetPinnedSha256() string {
	if x != nil {
		return x.PinnedSha256
	}
	return ""
}

func (x *HTTPFetchRequest) GetSocks5() *HTTPFetchSocks5 {
	if x != nil {
		return x.Socks5
	}
	return nil
}

func (x *HTTPFetchRequest) GetAgeIdentities() string {
	if x != nil {
		return x.AgeIdentities
	}
	return ""
}

type HTTPFetchHead struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// First value of each response header, keyed by canonical header name.
	Headers map[string]string `protobuf:"bytes,1,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Length of the body that follows, or -1 when unknown.
	ContentLength int64 `protobuf:"varint,2,opt,name=content_length,json=contentLength,proto3" json:"content_length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HTTPFetchHead) Reset() {
	*x = HTTPFetchHead{}
	mi := &file_husi_v1_application_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPFetchHead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPFetchHead) ProtoMessage() {}

func (x *HTTPFetchHead) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_application_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPFetchHead.ProtoReflect.Descriptor instead.
func (*HTTPFetchHead) Descriptor() ([]byte, []int) {
	return file_husi_v1_application_proto_rawDescGZIP(), []int{14}
}

func (x *HTTPFetchHead) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HTTPFetchHead) GetContentLength() int64 {
	if x != nil {
		return x.ContentLength
	}
	return 0
}

// The stream carries one head, then the body in chunks.
type HTTPFetchResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*HTTPFetchResponse_Head
	//	*HTTPFetchResponse_Chunk
	Payload       isHTTPFetchResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HTTPFetchResponse) Reset() {
	*x = HTTPFetchResponse{}
	mi := &file_husi_v1_application_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPFetchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPFetchResponse) ProtoMessage() {}

func (x *HTTPFetchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_application_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPFetchResponse.ProtoReflect.Descriptor instead.
func (*HTTPFetchResponse) Descriptor() ([]byte, []int) {
	return file_husi_v1_application_proto_rawDescGZIP(), []int{15}
}

func (x *HTTPFetchResponse) GetPayload() isHTTPFetchResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *HTTPFetchResponse) GetHead() *HTTPFetchHead {
	if x != nil {
		if x, ok := x.Payload.(*HTTPFetchResponse_Head); ok {
			return x.Head
		}
	}
	return nil
}

func (x *HTTPFetchResponse) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Payload.(*HTTPFetchResponse_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isHTTPFetchResponse_Payload interface {
	isHTTPFetchResponse_Payload()
}

type HTTPFetchResponse_Head struct {
	Head *HTTPFetchHead `protobuf:"bytes,1,opt,name=head,proto3,oneof"`
}

type HTTPFetchResponse_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*HTTPFetchResponse_Head) isHTTPFetchResponse_Payload() {}

func (*HTTPFetchResponse_Chunk) isHTTPFetchResponse_Payload() {}

type PingRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Protocol PingProtocol           `protobuf:"varint,1,opt,name=protocol,proto3,enum=husi.v1.PingProtocol" json:"protocol,omitempty"`
	// IP address or domain name.
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	// Ignored by ICMP.
	Port          uint32 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	TimeoutMs     int32  `protobuf:"varint,4,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_husi_v1_application_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_application_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_husi_v1_application_proto_rawDescGZIP(), []int{16}
}

func (x *PingRequest) GetProtocol() PingProtocol {
	if x != nil {
		return x.Protocol
	}
	return PingProtocol_PING_PROTOCOL_UNSPECIFIED
}

func (x *PingRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *PingRequest) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *PingRequest) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LatencyMs     int32                  `protobuf:"varint,1,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_husi_v1_application_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_application_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_husi_v1_application_proto_rawDescGZIP(), []int{17}
}

func (x *PingResponse) GetLatencyMs() int32 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

type MatchRuleSetsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Domain name or IP address to match.
	Keyword string `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	// Directory searched recursively for binary (.srs) rule sets.
	Directory     string `protobuf:"bytes,2,opt,name=directory,proto3" json:"directory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchRuleSetsRequest) Reset() {
	*x = MatchRuleSetsRequest{}
	mi := &file_husi_v1_application_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchRuleSetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchRuleSetsRequest) ProtoMessage() {}

func (x *MatchRuleSetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_application_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchRuleSetsRequest.ProtoReflect.Descriptor instead.
func (*MatchRuleSetsRequest) Descriptor() ([]byte, []int) {
	return file_husi_v1_application_proto_rawDescGZIP(), []int{18}
}

func (x *MatchRuleSetsRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *MatchRuleSetsRequest) GetDirectory() string {
	if x != nil {
		return x.Directory
	}
	return ""
}

type MatchRuleSetsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// File names of the rule sets that have a rule matching the keyword.
	// Unreadable files are skipped, and a missing directory reports nothing.
	Names         []string `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchRuleSetsResponse) Reset() {
	*x = MatchRuleSetsResponse{}
	mi := &file_husi_v1_application_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchRuleSetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchRuleSetsResponse) ProtoMessage() {}

func (x *MatchRuleSetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_application_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchRuleSetsResponse.ProtoReflect.Descriptor instead.
func (*MatchRuleSetsResponse) Descriptor() ([]byte, []int) {
	return file_husi_v1_application_proto_rawDescGZIP(), []int{19}
}

func (x *MatchRuleSetsResponse) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type GetRootCertificatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Store         RootCertificateStore   `protobuf:"varint,1,opt,name=store,proto3,enum=husi.v1.RootCertificateStore" json:"store,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRootCertificatesRequest) Reset() {
	*x = GetRootCertificatesRequest{}
	mi := &file_husi_v1_application_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRootCertificatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRootCertificatesRequest) ProtoMessage() {}

func (x *GetRootCertificatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_application_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRootCertificatesRequest.ProtoReflect.Descriptor instead.
func (*GetRootCertificatesRequest) Descriptor() ([]byte, []int) {
	return file_husi_v1_application_proto_rawDescGZIP(), []int{20}
}

func (x *GetRootCertificatesRequest) GetStore() RootCertificateStore {
	if x != nil {
		return x.Store
	}
	return RootCertificateStore_ROOT_CERTIFICATE_STORE_UNSPECIFIED
}

type GetRootCertificatesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The roots of the store as PEM, falling back to Mozilla's bundle when the
	// store cannot be read.
	Pem           string `protobuf:"bytes,1,opt,name=pem,proto3" json:"pem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRootCertificatesResponse) Reset() {
	*x = GetRootCertificatesResponse{}
	mi := &file_husi_v1_application_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRootCertificatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRootCertificatesResponse) ProtoMessage() {}

func (x *GetRootCertificatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_application_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRootCertificatesResponse.ProtoReflect.Descriptor instead.
func (*GetRootCertificatesResponse) Descriptor() ([]byte, []int) {
	return file_husi_v1_application_proto_rawDescGZIP(), []int{21}
}

func (x *GetRootCertificatesResponse) GetPem() string {
	if x != nil {
		return x.Pem
	}
	return ""
}

type ReadAndroidVPNTypeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The base and split APKs of one package, tried in order.
	ApkPaths      []string `protobuf:"bytes,1,rep,name=apk_paths,json=apkPaths,proto3" json:"apk_paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadAndroidVPNTypeRequest) Reset() {
	*x = ReadAndroidVPNTypeRequest{}
	mi := &file_husi_v1_application_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAndroidVPNTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAndroidVPNTypeRequest) ProtoMessage() {}

func (x *ReadAndroidVPNTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_application_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAndroidVPNTypeRequest.ProtoReflect.Descriptor instead.
func (*ReadAndroidVPNTypeRequest) Descriptor() ([]byte, []int) {
	return file_husi_v1_application_proto_rawDescGZIP(), []int{22}
}

func (x *ReadAndroidVPNTypeRequest) GetApkPaths() []string {
	if x != nil {
		return x.ApkPaths
	}
	return nil
}

// The Go core another VPN app embeds, read from the Go build info of its
// native libraries.
type AndroidVPNType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CoreType      string                 `protobuf:"bytes,1,opt,name=core_type,json=coreType,proto3" json:"core_type,omitempty"`
	CorePath      string                 `protobuf:"bytes,2,opt,name=core_path,json=corePath,proto3" json:"core_path,omitempty"`
	GoVersion     string                 `protobuf:"bytes,3,opt,name=go_version,json=goVersion,proto3" json:"go_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AndroidVPNType) Reset() {
	*x = AndroidVPNType{}
	mi := &file_husi_v1_application_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AndroidVPNType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AndroidVPNType) ProtoMessage() {}

func (x *AndroidVPNType) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_application_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AndroidVPNType.ProtoReflect.Descriptor instead.
func (*AndroidVPNType) Descriptor() ([]byte, []int) {
	return file_husi_v1_application_proto_rawDescGZIP(), []int{23}
}

func (x *AndroidVPNType) GetCoreType() string {
	if x != nil {
		return x.CoreType
	}
	return ""
}

func (x *AndroidVPNType) GetCorePath() string {
	if x != nil {
		return x.CorePath
	}
	return ""
}

func (x *AndroidVPNType) GetGoVersion() string {
	if x != nil {
		return x.GoVersion
	}
	return ""
}

type ReadAndroidVPNTypeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unset when no APK has a native library that reveals its core.
	Type          *AndroidVPNType `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadAndroidVPNTypeResponse) Reset() {
	*x = ReadAndroidVPNTypeResponse{}
	mi := &file_husi_v1_application_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAndroidVPNTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAndroidVPNTypeResponse) ProtoMessage() {}

func (x *ReadAndroidVPNTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_application_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAndroidVPNTypeResponse.ProtoReflect.Descriptor instead.
func (*ReadAndroidVPNTypeResponse) Descriptor() ([]byte, []int) {
	return file_husi_v1_application_proto_rawDescGZIP(), []int{24}
}

func (x *ReadAndroidVPNTypeResponse) GetType() *AndroidVPNType {
	if x != nil {
		return x.Type
	}
	return nil
}

var File_husi_v1_application_proto protoreflect.FileDescriptor

const file_husi_v1_application_proto_rawDesc = "" +
	"\n" +
	"\x19husi/v1/application.proto\x12\ahusi.v1\x1a\x1cdaemon/started_service.proto\x1a\x12husi/v1/core.proto\x1a\x14husi/v1/daemon.proto\",\n" +
	"\x12CheckConfigRequest\x12\x16\n" +
	"\x06config\x18\x01 \x01(\tR\x06config\"\x15\n" +
	"\x13CheckConfigResponse\"-\n" +
	"\x13FormatConfigRequest\x12\x16\n" +
	"\x06config\x18\x01 \x01(\tR\x06config\".\n" +
	"\x14FormatConfigResponse\x12\x16\n" +
	"\x06config\x18\x01 \x01(\tR\x06config\"@\n" +
	"\x15GenerateSchemaRequest\x12'\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x13.husi.v1.SchemaKindR\x04kind\"0\n" +
	"\x16GenerateSchemaResponse\x12\x16\n" +
	"\x06schema\x18\x01 \x01(\tR\x06schema\"\xf1\x01\n" +
	"\x18StandaloneURLTestRequest\x12\x16\n" +
	"\x06config\x18\x01 \x01(\tR\x06config\x12!\n" +
	"\foutbound_tag\x18\x02 \x01(\tR\voutboundTag\x12\x12\n" +
	"\x04link\x18\x03 \x01(\tR\x04link\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x04 \x01(\x05R\ttimeoutMs\x121\n" +
	"\aoptions\x18\x05 \x01(\v2\x17.husi.v1.URLTestOptionsR\aoptions\x124\n" +
	"\aplugins\x18\x06 \x03(\v2\x1a.husi.v1.PluginProcessSpecR\aplugins\":\n" +
	"\x19StandaloneURLTestResponse\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x01 \x01(\x05R\tlatencyMs\"\x9b\x01\n" +
	"\x0eGetCertRequest\x12\x16\n" +
	"\x06server\x18\x01 \x01(\tR\x06server\x12\x1f\n" +
	"\vserver_name\x18\x02 \x01(\tR\n" +
	"serverName\x12(\n" +
	"\x04mode\x18\x03 \x01(\x0e2\x14.husi.v1.GetCertModeR\x04mode\x12&\n" +
	"\x0fsocks_proxy_url\x18\x04 \x01(\tR\rsocksProxyUrl\"#\n" +
	"\x0fGetCertResponse\x12\x10\n" +
	"\x03pem\x18\x01 \x01(\tR\x03pem\"3\n" +
	"\x19StandaloneSTUNTestRequest\x12\x16\n" +
	"\x06server\x18\x01 \x01(\tR\x06server\"\xa2\x01\n" +
	"#StandaloneNetworkQualityTestRequest\x12\x1d\n" +
	"\n" +
	"config_url\x18\x01 \x01(\tR\tconfigUrl\x12\x16\n" +
	"\x06serial\x18\x02 \x01(\bR\x06serial\x12.\n" +
	"\x13max_runtime_seconds\x18\x03 \x01(\x05R\x11maxRuntimeSeconds\x12\x14\n" +
	"\x05http3\x18\x04 \x01(\bR\x05http3\"]\n" +
	"\x0fHTTPFetchSocks5\x12\x12\n" +
	"\x04port\x18\x01 \x01(\x05R\x04port\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"\xf7\x02\n" +
	"\x10HTTPFetchRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12@\n" +
	"\aheaders\x18\x02 \x03(\v2&.husi.v1.HTTPFetchRequest.HeadersEntryR\aheaders\x12.\n" +
	"\x13no_overall_deadline\x18\x03 \x01(\bR\x11noOverallDeadline\x12%\n" +
	"\x0erestricted_tls\x18\x04 \x01(\bR\rrestrictedTls\x12#\n" +
	"\rpinned_sha256\x18\x05 \x01(\tR\fpinnedSha256\x120\n" +
	"\x06socks5\x18\x06 \x01(\v2\x18.husi.v1.HTTPFetchSocks5R\x06socks5\x12%\n" +
	"\x0eage_identities\x18\a \x01(\tR\rageIdentities\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb1\x01\n" +
	"\rHTTPFetchHead\x12=\n" +
	"\aheaders\x18\x01 \x03(\v2#.husi.v1.HTTPFetchHead.HeadersEntryR\aheaders\x12%\n" +
	"\x0econtent_length\x18\x02 \x01(\x03R\rcontentLength\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"d\n" +
	"\x11HTTPFetchResponse\x12,\n" +
	"\x04head\x18\x01 \x01(\v2\x16.husi.v1.HTTPFetchHeadH\x00R\x04head\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunkB\t\n" +
	"\apayload\"\x8d\x01\n" +
	"\vPingRequest\x121\n" +
	"\bprotocol\x18\x01 \x01(\x0e2\x15.husi.v1.PingProtocolR\bprotocol\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x03 \x01(\rR\x04port\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x04 \x01(\x05R\ttimeoutMs\"-\n" +
	"\fPingResponse\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x01 \x01(\x05R\tlatencyMs\"N\n" +
	"\x14MatchRuleSetsRequest\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x1c\n" +
	"\tdirectory\x18\x02 \x01(\tR\tdirectory\"-\n" +
	"\x15MatchRuleSetsResponse\x12\x14\n" +
	"\x05names\x18\x01 \x03(\tR\x05names\"Q\n" +
	"\x1aGetRootCertificatesRequest\x123\n" +
	"\x05store\x18\x01 \x01(\x0e2\x1d.husi.v1.RootCertificateStoreR\x05store\"/\n" +
	"\x1bGetRootCertificatesResponse\x12\x10\n" +
	"\x03pem\x18\x01 \x01(\tR\x03pem\"8\n" +
	"\x19ReadAndroidVPNTypeRequest\x12\x1b\n" +
	"\tapk_paths\x18\x01 \x03(\tR\bapkPaths\"i\n" +
	"\x0eAndroidVPNType\x12\x1b\n" +
	"\tcore_type\x18\x01 \x01(\tR\bcoreType\x12\x1b\n" +
	"\tcore_path\x18\x02 \x01(\tR\bcorePath\x12\x1d\n" +
	"\n" +
	"go_version\x18\x03 \x01(\tR\tgoVersion\"I\n" +
	"\x1aReadAndroidVPNTypeResponse\x12+\n" +
	"\x04type\x18\x01 \x01(\v2\x17.husi.v1.AndroidVPNTypeR\x04type*u\n" +
	"\n" +
	"SchemaKind\x12\x1b\n" +
	"\x17SCHEMA_KIND_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12SCHEMA_KIND_CONFIG\x10\x01\x12\x18\n" +
	"\x14SCHEMA_KIND_OUTBOUND\x10\x02\x12\x18\n" +
	"\x14SCHEMA_KIND_DNS_RULE\x10\x03*]\n" +
	"\vGetCertMode\x12\x1d\n" +
	"\x19GET_CERT_MODE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13GET_CERT_MODE_HTTPS\x10\x01\x12\x16\n" +
	"\x12GET_CERT_MODE_QUIC\x10\x02*\\\n" +
	"\fPingProtocol\x12\x1d\n" +
	"\x19PING_PROTOCOL_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12PING_PROTOCOL_ICMP\x10\x01\x12\x15\n" +
	"\x11PING_PROTOCOL_TCP\x10\x022\xee\a\n" +
	"\x12ApplicationService\x12H\n" +
	"\vCheckConfig\x12\x1b.husi.v1.CheckConfigRequest\x1a\x1c.husi.v1.CheckConfigResponse\x12K\n" +
	"\fFormatConfig\x12\x1c.husi.v1.FormatConfigRequest\x1a\x1d.husi.v1.FormatConfigResponse\x12Q\n" +
	"\x0eGenerateSchema\x12\x1e.husi.v1.GenerateSchemaRequest\x1a\x1f.husi.v1.GenerateSchemaResponse\x12Z\n" +
	"\x11StandaloneURLTest\x12!.husi.v1.StandaloneURLTestRequest\x1a\".husi.v1.StandaloneURLTestResponse\x12<\n" +
	"\aGetCert\x12\x17.husi.v1.GetCertRequest\x1a\x18.husi.v1.GetCertResponse\x12T\n" +
	"\x12StandaloneSTUNTest\x12\".husi.v1.StandaloneSTUNTestRequest\x1a\x18.daemon.STUNTestProgress0\x01\x12r\n" +
	"\x1cStandaloneNetworkQualityTest\x12,.husi.v1.StandaloneNetworkQualityTestRequest\x1a\".daemon.NetworkQualityTestProgress0\x01\x12D\n" +
	"\tHTTPFetch\x12\x19.husi.v1.HTTPFetchRequest\x1a\x1a.husi.v1.HTTPFetchResponse0\x01\x123\n" +
	"\x04Ping\x12\x14.husi.v1.PingRequest\x1a\x15.husi.v1.PingResponse\x12N\n" +
	"\rMatchRuleSets\x12\x1d.husi.v1.MatchRuleSetsRequest\x1a\x1e.husi.v1.MatchRuleSetsResponse\x12`\n" +
	"\x13GetRootCertificates\x12#.husi.v1.GetRootCertificatesRequest\x1a$.husi.v1.GetRootCertificatesResponse\x12]\n" +
	"\x12ReadAndroidVPNType\x12\".husi.v1.ReadAndroidVPNTypeRequest\x1a#.husi.v1.ReadAndroidVPNTypeResponseBA\n" +
	"\x10fr.husi.proto.v1B\x10ApplicationProtoP\x01Z\x19libcore/pb/husi/v1;husiv1b\x06proto3"

var (
	file_husi_v1_application_proto_rawDescOnce sync.Once
	file_husi_v1_application_proto_rawDescData []byte
)

func file_husi_v1_application_proto_rawDescGZIP() []byte {
	file_husi_v1_application_proto_rawDescOnce.Do(func() {
		file_husi_v1_application_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_husi_v1_application_proto_rawDesc), len(file_husi_v1_application_proto_rawDesc)))
	})
	return file_husi_v1_application_proto_rawDescData
}

var file_husi_v1_application_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_husi_v1_application_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_husi_v1_application_proto_goTypes = []any{
	(SchemaKind)(0),                             // 0: husi.v1.SchemaKind
	(GetCertMode)(0),                            // 1: husi.v1.GetCertMode
	(PingProtocol)(0),                           // 2: husi.v1.PingProtocol
	(*CheckConfigRequest)(nil),                  // 3: husi.v1.CheckConfigRequest
	(*CheckConfigResponse)(nil),                 // 4: husi.v1.CheckConfigResponse
	(*FormatConfigRequest)(nil),                 // 5: husi.v1.FormatConfigRequest
	(*FormatConfigResponse)(nil),                // 6: husi.v1.FormatConfigResponse
	(*GenerateSchemaRequest)(nil),               // 7: husi.v1.GenerateSchemaRequest
	(*GenerateSchemaResponse)(nil),              // 8: husi.v1.GenerateSchemaResponse
	(*StandaloneURLTestRequest)(nil),            // 9: husi.v1.StandaloneURLTestRequest
	(*StandaloneURLTestResponse)(nil),           // 10: husi.v1.StandaloneURLTestResponse
	(*GetCertRequest)(nil),                      // 11: husi.v1.GetCertRequest
	(*GetCertResponse)(nil),                     // 12: husi.v1.GetCertResponse
	(*StandaloneSTUNTestRequest)(nil),           // 13: husi.v1.StandaloneSTUNTestRequest
	(*StandaloneNetworkQualityTestRequest)(nil), // 14: husi.v1.StandaloneNetworkQualityTestRequest
	(*HTTPFetchSocks5)(nil),                     // 15: husi.v1.HTTPFetchSocks5
	(*HTTPFetchRequest)(nil),                    // 16: husi.v1.HTTPFetchRequest
	(*HTTPFetchHead)(nil),                       // 17: husi.v1.HTTPFetchHead
	(*HTTPFetchResponse)(nil),                   // 18: husi.v1.HTTPFetchResponse
	(*PingRequest)(nil),                         // 19: husi.v1.PingRequest
	(*PingResponse)(nil),                        // 20: husi.v1.PingResponse
	(*MatchRuleSetsRequest)(nil),                // 21: husi.v1.MatchRuleSetsRequest
	(*MatchRuleSetsResponse)(nil),               // 22: husi.v1.MatchRuleSetsResponse
	(*GetRootCertificatesRequest)(nil),          // 23: husi.v1.GetRootCertificatesRequest
	(*GetRootCertificatesResponse)(nil),         // 24: husi.v1.GetRootCertificatesResponse
	(*ReadAndroidVPNTypeRequest)(nil),           // 25: husi.v1.ReadAndroidVPNTypeRequest
	(*AndroidVPNType)(nil),                      // 26: husi.v1.AndroidVPNType
	(*ReadAndroidVPNTypeResponse)(nil),          // 27: husi.v1.ReadAndroidVPNTypeResponse
	nil,                                         // 28: husi.v1.HTTPFetchRequest.HeadersEntry
	nil,                                         // 29: husi.v1.HTTPFetchHead.HeadersEntry
	(*URLTestOptions)(nil),                      // 30: husi.v1.URLTestOptions
	(*PluginProcessSpec)(nil),                   // 31: husi.v1.PluginProcessSpec
	(RootCertificateStore)(0),                   // 32: husi.v1.RootCertificateStore
	(*daemon.STUNTestProgress)(nil),             // 33: daemon.STUNTestProgress
	(*daemon.NetworkQualityTestProgress)(nil),   // 34: daemon.NetworkQualityTestProgress
}
var file_husi_v1_application_proto_depIdxs = []int32{
	0,  // 0: husi.v1.GenerateSchemaRequest.kind:type_name -> husi.v1.SchemaKind
	30, // 1: husi.v1.StandaloneURLTestRequest.options:type_name -> husi.v1.URLTestOptions
	31, // 2: husi.v1.StandaloneURLTestRequest.plugins:type_name -> husi.v1.PluginProcessSpec
	1,  // 3: husi.v1.GetCertRequest.mode:type_name -> husi.v1.GetCertMode
	28, // 4: husi.v1.HTTPFetchRequest.headers:type_name -> husi.v1.HTTPFetchRequest.HeadersEntry
	15, // 5: husi.v1.HTTPFetchRequest.socks5:type_name -> husi.v1.HTTPFetchSocks5
	29, // 6: husi.v1.HTTPFetchHead.headers:type_name -> husi.v1.HTTPFetchHead.HeadersEntry
	17, // 7: husi.v1.HTTPFetchResponse.head:type_name -> husi.v1.HTTPFetchHead
	2,  // 8: husi.v1.PingRequest.protocol:type_name -> husi.v1.PingProtocol
	32, // 9: husi.v1.GetRootCertificatesRequest.store:type_name -> husi.v1.RootCertificateStore
	26, // 10: husi.v1.ReadAndroidVPNTypeResponse.type:type_name -> husi.v1.AndroidVPNType
	3,  // 11: husi.v1.ApplicationService.CheckConfig:input_type -> husi.v1.CheckConfigRequest
	5,  // 12: husi.v1.ApplicationService.FormatConfig:input_type -> husi.v1.FormatConfigRequest
	7,  // 13: husi.v1.ApplicationService.GenerateSchema:input_type -> husi.v1.GenerateSchemaRequest
	9,  // 14: husi.v1.ApplicationService.StandaloneURLTest:input_type -> husi.v1.StandaloneURLTestRequest
	11, // 15: husi.v1.ApplicationService.GetCert:input_type -> husi.v1.GetCertRequest
	13, // 16: husi.v1.ApplicationService.StandaloneSTUNTest:input_type -> husi.v1.StandaloneSTUNTestRequest
	14, // 17: husi.v1.ApplicationService.StandaloneNetworkQualityTest:input_type -> husi.v1.StandaloneNetworkQualityTestRequest
	16, // 18: husi.v1.ApplicationService.HTTPFetch:input_type -> husi.v1.HTTPFetchRequest
	19, // 19: husi.v1.ApplicationService.Ping:input_type -> husi.v1.PingRequest
	21, // 20: husi.v1.ApplicationService.MatchRuleSets:input_type -> husi.v1.MatchRuleSetsRequest
	23, // 21: husi.v1.ApplicationService.GetRootCertificates:input_type -> husi.v1.GetRootCertificatesRequest
	25, // 22: husi.v1.ApplicationService.ReadAndroidVPNType:input_type -> husi.v1.ReadAndroidVPNTypeRequest
	4,  // 23: husi.v1.ApplicationService.CheckConfig:output_type -> husi.v1.CheckConfigResponse
	6,  // 24: husi.v1.ApplicationService.FormatConfig:output_type -> husi.v1.FormatConfigResponse
	8,  // 25: husi.v1.ApplicationService.GenerateSchema:output_type -> husi.v1.GenerateSchemaResponse
	10, // 26: husi.v1.ApplicationService.StandaloneURLTest:output_type -> husi.v1.StandaloneURLTestResponse
	12, // 27: husi.v1.ApplicationService.GetCert:output_type -> husi.v1.GetCertResponse
	33, // 28: husi.v1.ApplicationService.StandaloneSTUNTest:output_type -> daemon.STUNTestProgress
	34, // 29: husi.v1.ApplicationService.StandaloneNetworkQualityTest:output_type -> daemon.NetworkQualityTestProgress
	18, // 30: husi.v1.ApplicationService.HTTPFetch:output_type -> husi.v1.HTTPFetchResponse
	20, // 31: husi.v1.ApplicationService.Ping:output_type -> husi.v1.PingResponse
	22, // 32: husi.v1.ApplicationService.MatchRuleSets:output_type -> husi.v1.MatchRuleSetsResponse
	24, // 33: husi.v1.ApplicationService.GetRootCertificates:output_type -> husi.v1.GetRootCertificatesResponse
	27, // 34: husi.v1.ApplicationService.ReadAndroidVPNType:output_type -> husi.v1.ReadAndroidVPNTypeResponse
	23, // [23:35] is the sub-list for method output_type
	11, // [11:23] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_husi_v1_application_proto_init() }
func file_husi_v1_application_proto_init() {
	if File_husi_v1_application_proto != nil {
		return
	}
	file_husi_v1_core_proto_init()
	file_husi_v1_daemon_proto_init()
	file_husi_v1_application_proto_msgTypes[15].OneofWrappers = []any{
		(*HTTPFetchResponse_Head)(nil),
		(*HTTPFetchResponse_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_husi_v1_application_proto_rawDesc), len(file_husi_v1_application_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_husi_v1_application_proto_goTypes,
		DependencyIndexes: file_husi_v1_application_proto_depIdxs,
		EnumInfos:         file_husi_v1_application_proto_enumTypes,
		MessageInfos:      file_husi_v1_application_proto_msgTypes,
	}.Build()
	File_husi_v1_application_proto = out.File
	file_husi_v1_application_proto_goTypes = nil
	file_husi_v1_application_proto_depIdxs = nil
}
