// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: husi/v1/core.proto

package husiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CoreService_GetVersion_FullMethodName             = "/husi.v1.CoreService/GetVersion"
	CoreService_URLTest_FullMethodName                = "/husi.v1.CoreService/URLTest"
	CoreService_ResetNetwork_FullMethodName           = "/husi.v1.CoreService/ResetNetwork"
	CoreService_SubscribeServiceEvents_FullMethodName = "/husi.v1.CoreService/SubscribeServiceEvents"
)

// CoreServiceClient is the client API for CoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CoreService is what husi adds to a running instance beyond the contract it
// shares with sing-box. Everything sing-box's daemon.StartedService already
// answers — status, log, connections, groups, clash mode, outbound selection,
// OpenConnect authentication — is served from that schema instead, unchanged,
// so a husi host and a sing-box host stay interchangeable on the wire.
//
// Every hosting serves this service alongside daemon.StartedService: the
// desktop daemon, the desktop session child and the Android ":bg" process.
type CoreServiceClient interface {
	GetVersion(ctx context.Context, in *GetVersionRequest, opts ...grpc.CallOption) (*GetVersionResponse, error)
	URLTest(ctx context.Context, in *URLTestRequest, opts ...grpc.CallOption) (*URLTestResponse, error)
	ResetNetwork(ctx context.Context, in *ResetNetworkRequest, opts ...grpc.CallOption) (*ResetNetworkResponse, error)
	// SubscribeServiceEvents carries what only the host that started the service
	// knows: husi's own lifecycle state with the profile behind it, the
	// proxy/direct speed split derived from the built config, and the alerts the
	// UI raises to the user. daemon.ServiceStatus answers a narrower question —
	// whether the instance is up — and knows nothing about profiles or plugins.
	//
	// On Android this replaces the binder observer the UI process used to
	// register on ":bg". Desktop hosts serve it too, and simply have no publisher.
	SubscribeServiceEvents(ctx context.Context, in *SubscribeServiceEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeServiceEventsResponse], error)
}

type coreServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCoreServiceClient(cc grpc.ClientConnInterface) CoreServiceClient {
	return &coreServiceClient{cc}
}

func (c *coreServiceClient) GetVersion(ctx context.Context, in *GetVersionRequest, opts ...grpc.CallOption) (*GetVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVersionResponse)
	err := c.cc.Invoke(ctx, CoreService_GetVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) URLTest(ctx context.Context, in *URLTestRequest, opts ...grpc.CallOption) (*URLTestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(URLTestResponse)
	err := c.cc.Invoke(ctx, CoreService_URLTest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) ResetNetwork(ctx context.Context, in *ResetNetworkRequest, opts ...grpc.CallOption) (*ResetNetworkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResetNetworkResponse)
	err := c.cc.Invoke(ctx, CoreService_ResetNetwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) SubscribeServiceEvents(ctx context.Context, in *SubscribeServiceEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeServiceEventsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CoreService_ServiceDesc.Streams[0], CoreService_SubscribeServiceEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeServiceEventsRequest, SubscribeServiceEventsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CoreService_SubscribeServiceEventsClient = grpc.ServerStreamingClient[SubscribeServiceEventsResponse]

// CoreServiceServer is the server API for CoreService service.
// All implementations must embed UnimplementedCoreServiceServer
// for forward compatibility.
//
// CoreService is what husi adds to a running instance beyond the contract it
// shares with sing-box. Everything sing-box's daemon.StartedService already
// answers — status, log, connections, groups, clash mode, outbound selection,
// OpenConnect authentication — is served from that schema instead, unchanged,
// so a husi host and a sing-box host stay interchangeable on the wire.
//
// Every hosting serves this service alongside daemon.StartedService: the
// desktop daemon, the desktop session child and the Android ":bg" process.
type CoreServiceServer interface {
	GetVersion(context.Context, *GetVersionRequest) (*GetVersionResponse, error)
	URLTest(context.Context, *URLTestRequest) (*URLTestResponse, error)
	ResetNetwork(context.Context, *ResetNetworkRequest) (*ResetNetworkResponse, error)
	// SubscribeServiceEvents carries what only the host that started the service
	// knows: husi's own lifecycle state with the profile behind it, the
	// proxy/direct speed split derived from the built config, and the alerts the
	// UI raises to the user. daemon.ServiceStatus answers a narrower question —
	// whether the instance is up — and knows nothing about profiles or plugins.
	//
	// On Android this replaces the binder observer the UI process used to
	// register on ":bg". Desktop hosts serve it too, and simply have no publisher.
	SubscribeServiceEvents(*SubscribeServiceEventsRequest, grpc.ServerStreamingServer[SubscribeServiceEventsResponse]) error
	mustEmbedUnimplementedCoreServiceServer()
}

// UnimplementedCoreServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoreServiceServer struct{}

func (UnimplementedCoreServiceServer) GetVersion(context.Context, *GetVersionRequest) (*GetVersionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVersion not implemented")
}
func (UnimplementedCoreServiceServer) URLTest(context.Context, *URLTestRequest) (*URLTestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method URLTest not implemented")
}
func (UnimplementedCoreServiceServer) ResetNetwork(context.Context, *ResetNetworkRequest) (*ResetNetworkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResetNetwork not implemented")
}
func (UnimplementedCoreServiceServer) SubscribeServiceEvents(*SubscribeServiceEventsRequest, grpc.ServerStreamingServer[SubscribeServiceEventsResponse]) error {
	return status.Error(codes.Unimplemented, "method SubscribeServiceEvents not implemented")
}
func (UnimplementedCoreServiceServer) mustEmbedUnimplementedCoreServiceServer() {}
func (UnimplementedCoreServiceServer) testEmbeddedByValue()                     {}

// UnsafeCoreServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoreServiceServer will
// result in compilation errors.
type UnsafeCoreServiceServer interface {
	mustEmbedUnimplementedCoreServiceServer()
}

func RegisterCoreServiceServer(s grpc.ServiceRegistrar, srv CoreServiceServer) {
	// If the following call panics, it indicates UnimplementedCoreServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoreService_ServiceDesc, srv)
}

func _CoreService_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_GetVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).GetVersion(ctx, req.(*GetVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_URLTest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(URLTestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).URLTest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_URLTest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).URLTest(ctx, req.(*URLTestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_ResetNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).ResetNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_ResetNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).ResetNetwork(ctx, req.(*ResetNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_SubscribeServiceEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeServiceEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CoreServiceServer).SubscribeServiceEvents(m, &grpc.GenericServerStream[SubscribeServiceEventsRequest, SubscribeServiceEventsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CoreService_SubscribeServiceEventsServer = grpc.ServerStreamingServer[SubscribeServiceEventsResponse]

// CoreService_ServiceDesc is the grpc.ServiceDesc for CoreService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoreService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "husi.v1.CoreService",
	HandlerType: (*CoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVersion",
			Handler:    _CoreService_GetVersion_Handler,
		},
		{
			MethodName: "URLTest",
			Handler:    _CoreService_URLTest_Handler,
		},
		{
			MethodName: "ResetNetwork",
			Handler:    _CoreService_ResetNetwork_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeServiceEvents",
			Handler:       _CoreService_SubscribeServiceEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "husi/v1/core.proto",
}
