// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: husi/v1/core.proto

package husiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceRunState int32

const (
	ServiceRunState_SERVICE_RUN_STATE_UNSPECIFIED ServiceRunState = 0
	ServiceRunState_SERVICE_RUN_STATE_IDLE        ServiceRunState = 1
	ServiceRunState_SERVICE_RUN_STATE_CONNECTING  ServiceRunState = 2
	ServiceRunState_SERVICE_RUN_STATE_CONNECTED   ServiceRunState = 3
	ServiceRunState_SERVICE_RUN_STATE_STOPPING    ServiceRunState = 4
	ServiceRunState_SERVICE_RUN_STATE_STOPPED     ServiceRunState = 5
)

// Enum value maps for ServiceRunState.
var (
	ServiceRunState_name = map[int32]string{
		0: "SERVICE_RUN_STATE_UNSPECIFIED",
		1: "SERVICE_RUN_STATE_IDLE",
		2: "SERVICE_RUN_STATE_CONNECTING",
		3: "SERVICE_RUN_STATE_CONNECTED",
		4: "SERVICE_RUN_STATE_STOPPING",
		5: "SERVICE_RUN_STATE_STOPPED",
	}
	ServiceRunState_value = map[string]int32{
		"SERVICE_RUN_STATE_UNSPECIFIED": 0,
		"SERVICE_RUN_STATE_IDLE":        1,
		"SERVICE_RUN_STATE_CONNECTING":  2,
		"SERVICE_RUN_STATE_CONNECTED":   3,
		"SERVICE_RUN_STATE_STOPPING":    4,
		"SERVICE_RUN_STATE_STOPPED":     5,
	}
)

func (x ServiceRunState) Enum() *ServiceRunState {
	p := new(ServiceRunState)
	*p = x
	return p
}

func (x ServiceRunState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceRunState) Descriptor() protoreflect.EnumDescriptor {
	return file_husi_v1_core_proto_enumTypes[0].Descriptor()
}

func (ServiceRunState) Type() protoreflect.EnumType {
	return &file_husi_v1_core_proto_enumTypes[0]
}

func (x ServiceRunState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceRunState.Descriptor instead.
func (ServiceRunState) EnumDescriptor() ([]byte, []int) {
	return file_husi_v1_core_proto_rawDescGZIP(), []int{0}
}

type AlertKind int32

const (
	AlertKind_ALERT_KIND_UNSPECIFIED          AlertKind = 0
	AlertKind_ALERT_KIND_COMMON               AlertKind = 1
	AlertKind_ALERT_KIND_MISSING_PLUGIN       AlertKind = 2
	AlertKind_ALERT_KIND_NEED_WIFI_PERMISSION AlertKind = 3
)

// Enum value maps for AlertKind.
var (
	AlertKind_name = map[int32]string{
		0: "ALERT_KIND_UNSPECIFIED",
		1: "ALERT_KIND_COMMON",
		2: "ALERT_KIND_MISSING_PLUGIN",
		3: "ALERT_KIND_NEED_WIFI_PERMISSION",
	}
	AlertKind_value = map[string]int32{
		"ALERT_KIND_UNSPECIFIED":          0,
		"ALERT_KIND_COMMON":               1,
		"ALERT_KIND_MISSING_PLUGIN":       2,
		"ALERT_KIND_NEED_WIFI_PERMISSION": 3,
	}
)

func (x AlertKind) Enum() *AlertKind {
	p := new(AlertKind)
	*p = x
	return p
}

func (x AlertKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AlertKind) Descriptor() protoreflect.EnumDescriptor {
	return file_husi_v1_core_proto_enumTypes[1].Descriptor()
}

func (AlertKind) Type() protoreflect.EnumType {
	return &file_husi_v1_core_proto_enumTypes[1]
}

func (x AlertKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AlertKind.Descriptor instead.
func (AlertKind) EnumDescriptor() ([]byte, []int) {
	return file_husi_v1_core_proto_rawDescGZIP(), []int{1}
}

type GetVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionRequest) Reset() {
	*x = GetVersionRequest{}
	mi := &file_husi_v1_core_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionRequest) ProtoMessage() {}

func (x *GetVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_core_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionRequest.ProtoReflect.Descriptor instead.
func (*GetVersionRequest) Descriptor() ([]byte, []int) {
	return file_husi_v1_core_proto_rawDescGZIP(), []int{0}
}

// daemon.StartedService.GetVersion reports the sing-box side of the same host,
// including the revision of sing-box's contract. This one reports husi's.
type GetVersionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Husi version of the core host, as in husi.properties.
	Version        string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	SingBoxVersion string `protobuf:"bytes,2,opt,name=sing_box_version,json=singBoxVersion,proto3" json:"sing_box_version,omitempty"`
	// Go version, platform and build tags of the core host.
	BuildEnvironment string `protobuf:"bytes,3,opt,name=build_environment,json=buildEnvironment,proto3" json:"build_environment,omitempty"`
	// sing-box daemon API version (daemon.APIVersion in the pinned sing-box).
	// Matches GetDaemonInfoResponse.api_version.
	ApiVersion    uint32 `protobuf:"varint,4,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionResponse) Reset() {
	*x = GetVersionResponse{}
	mi := &file_husi_v1_core_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionResponse) ProtoMessage() {}

func (x *GetVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_core_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionResponse.ProtoReflect.Descriptor instead.
func (*GetVersionResponse) Descriptor() ([]byte, []int) {
	return file_husi_v1_core_proto_rawDescGZIP(), []int{1}
}

func (x *GetVersionResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetVersionResponse) GetSingBoxVersion() string {
	if x != nil {
		return x.SingBoxVersion
	}
	return ""
}

func (x *GetVersionResponse) GetBuildEnvironment() string {
	if x != nil {
		return x.BuildEnvironment
	}
	return ""
}

func (x *GetVersionResponse) GetApiVersion() uint32 {
	if x != nil {
		return x.ApiVersion
	}
	return 0
}

// URLTest measures one outbound, unlike daemon.StartedService.URLTest, which
// tests a whole group through the link the config gave it. Husi lets the user
// pick the link, the timeout and how the latency is counted, so it asks here.
type URLTestRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	OutboundTag string                 `protobuf:"bytes,1,opt,name=outbound_tag,json=outboundTag,proto3" json:"outbound_tag,omitempty"`
	// Empty selects the host default test URL.
	Link          string          `protobuf:"bytes,2,opt,name=link,proto3" json:"link,omitempty"`
	TimeoutMs     int32           `protobuf:"varint,3,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	Options       *URLTestOptions `protobuf:"bytes,4,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *URLTestRequest) Reset() {
	*x = URLTestRequest{}
	mi := &file_husi_v1_core_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URLTestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLTestRequest) ProtoMessage() {}

func (x *URLTestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_core_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URLTestRequest.ProtoReflect.Descriptor instead.
func (*URLTestRequest) Descriptor() ([]byte, []int) {
	return file_husi_v1_core_proto_rawDescGZIP(), []int{2}
}

func (x *URLTestRequest) GetOutboundTag() string {
	if x != nil {
		return x.OutboundTag
	}
	return ""
}

func (x *URLTestRequest) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *URLTestRequest) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *URLTestRequest) GetOptions() *URLTestOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type URLTestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LatencyMs     int32                  `protobuf:"varint,1,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *URLTestResponse) Reset() {
	*x = URLTestResponse{}
	mi := &file_husi_v1_core_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URLTestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLTestResponse) ProtoMessage() {}

func (x *URLTestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_core_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URLTestResponse.ProtoReflect.Descriptor instead.
func (*URLTestResponse) Descriptor() ([]byte, []int) {
	return file_husi_v1_core_proto_rawDescGZIP(), []int{3}
}

func (x *URLTestResponse) GetLatencyMs() int32 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

type URLTestOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Count the latency from the request rather than from the connection, which
	// hides the cost of a handshake the proxy would have paid anyway.
	UnifiedDelay bool `protobuf:"varint,1,opt,name=unified_delay,json=unifiedDelay,proto3" json:"unified_delay,omitempty"`
	// Report the response time alone, leaving the handshake out entirely.
	IgnoreHandshakeTime bool `protobuf:"varint,2,opt,name=ignore_handshake_time,json=ignoreHandshakeTime,proto3" json:"ignore_handshake_time,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *URLTestOptions) Reset() {
	*x = URLTestOptions{}
	mi := &file_husi_v1_core_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URLTestOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLTestOptions) ProtoMessage() {}

func (x *URLTestOptions) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_core_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URLTestOptions.ProtoReflect.Descriptor instead.
func (*URLTestOptions) Descriptor() ([]byte, []int) {
	return file_husi_v1_core_proto_rawDescGZIP(), []int{4}
}

func (x *URLTestOptions) GetUnifiedDelay() bool {
	if x != nil {
		return x.UnifiedDelay
	}
	return false
}

func (x *URLTestOptions) GetIgnoreHandshakeTime() bool {
	if x != nil {
		return x.IgnoreHandshakeTime
	}
	return false
}

// ResetNetwork closes every connection and rebuilds the network state, which
// is how the user recovers from a network change the host did not notice.
type ResetNetworkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetNetworkRequest) Reset() {
	*x = ResetNetworkRequest{}
	mi := &file_husi_v1_core_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetNetworkRequest) ProtoMessage() {}

func (x *ResetNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_core_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetNetworkRequest.ProtoReflect.Descriptor instead.
func (*ResetNetworkRequest) Descriptor() ([]byte, []int) {
	return file_husi_v1_core_proto_rawDescGZIP(), []int{5}
}

type ResetNetworkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetNetworkResponse) Reset() {
	*x = ResetNetworkResponse{}
	mi := &file_husi_v1_core_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetNetworkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetNetworkResponse) ProtoMessage() {}

func (x *ResetNetworkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_core_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetNetworkResponse.ProtoReflect.Descriptor instead.
func (*ResetNetworkResponse) Descriptor() ([]byte, []int) {
	return file_husi_v1_core_proto_rawDescGZIP(), []int{6}
}

type SubscribeServiceEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeServiceEventsRequest) Reset() {
	*x = SubscribeServiceEventsRequest{}
	mi := &file_husi_v1_core_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeServiceEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeServiceEventsRequest) ProtoMessage() {}

func (x *SubscribeServiceEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_core_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeServiceEventsRequest.ProtoReflect.Descriptor instead.
func (*SubscribeServiceEventsRequest) Descriptor() ([]byte, []int) {
	return file_husi_v1_core_proto_rawDescGZIP(), []int{7}
}

// The last state and the last speed are replayed on subscribe, so a UI that
// attaches to an already running service is immediately correct.
// Named SubscribeServiceEventsResponse (not ServiceEvent) to satisfy the
// project's per-RPC Request/Response lint rule.
type SubscribeServiceEventsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*SubscribeServiceEventsResponse_State
	//	*SubscribeServiceEventsResponse_Speed
	//	*SubscribeServiceEventsResponse_Alert
	Event         isSubscribeServiceEventsResponse_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeServiceEventsResponse) Reset() {
	*x = SubscribeServiceEventsResponse{}
	mi := &file_husi_v1_core_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeServiceEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeServiceEventsResponse) ProtoMessage() {}

func (x *SubscribeServiceEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_core_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeServiceEventsResponse.ProtoReflect.Descriptor instead.
func (*SubscribeServiceEventsResponse) Descriptor() ([]byte, []int) {
	return file_husi_v1_core_proto_rawDescGZIP(), []int{8}
}

func (x *SubscribeServiceEventsResponse) GetEvent() isSubscribeServiceEventsResponse_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *SubscribeServiceEventsResponse) GetState() *ServiceStateUpdate {
	if x != nil {
		if x, ok := x.Event.(*SubscribeServiceEventsResponse_State); ok {
			return x.State
		}
	}
	return nil
}

func (x *SubscribeServiceEventsResponse) GetSpeed() *SpeedUpdate {
	if x != nil {
		if x, ok := x.Event.(*SubscribeServiceEventsResponse_Speed); ok {
			return x.Speed
		}
	}
	return nil
}

func (x *SubscribeServiceEventsResponse) GetAlert() *ServiceAlert {
	if x != nil {
		if x, ok := x.Event.(*SubscribeServiceEventsResponse_Alert); ok {
			return x.Alert
		}
	}
	return nil
}

type isSubscribeServiceEventsResponse_Event interface {
	isSubscribeServiceEventsResponse_Event()
}

type SubscribeServiceEventsResponse_State struct {
	State *ServiceStateUpdate `protobuf:"bytes,1,opt,name=state,proto3,oneof"`
}

type SubscribeServiceEventsResponse_Speed struct {
	Speed *SpeedUpdate `protobuf:"bytes,2,opt,name=speed,proto3,oneof"`
}

type SubscribeServiceEventsResponse_Alert struct {
	Alert *ServiceAlert `protobuf:"bytes,3,opt,name=alert,proto3,oneof"`
}

func (*SubscribeServiceEventsResponse_State) isSubscribeServiceEventsResponse_Event() {}

func (*SubscribeServiceEventsResponse_Speed) isSubscribeServiceEventsResponse_Event() {}

func (*SubscribeServiceEventsResponse_Alert) isSubscribeServiceEventsResponse_Event() {}

type ServiceStateUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	State ServiceRunState        `protobuf:"varint,1,opt,name=state,proto3,enum=husi.v1.ServiceRunState" json:"state,omitempty"`
	// Display name of the profile the running service came from, empty when idle.
	ProfileName   string `protobuf:"bytes,2,opt,name=profile_name,json=profileName,proto3" json:"profile_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceStateUpdate) Reset() {
	*x = ServiceStateUpdate{}
	mi := &file_husi_v1_core_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceStateUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceStateUpdate) ProtoMessage() {}

func (x *ServiceStateUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_core_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceStateUpdate.ProtoReflect.Descriptor instead.
func (*ServiceStateUpdate) Descriptor() ([]byte, []int) {
	return file_husi_v1_core_proto_rawDescGZIP(), []int{9}
}

func (x *ServiceStateUpdate) GetState() ServiceRunState {
	if x != nil {
		return x.State
	}
	return ServiceRunState_SERVICE_RUN_STATE_UNSPECIFIED
}

func (x *ServiceStateUpdate) GetProfileName() string {
	if x != nil {
		return x.ProfileName
	}
	return ""
}

// Bytes per second, plus the totals of the current session. Mirrors
// fr.husi.bg.SpeedStats; "bypass" outbound usage is not counted.
type SpeedUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxRateProxy   int64                  `protobuf:"varint,1,opt,name=tx_rate_proxy,json=txRateProxy,proto3" json:"tx_rate_proxy,omitempty"`
	RxRateProxy   int64                  `protobuf:"varint,2,opt,name=rx_rate_proxy,json=rxRateProxy,proto3" json:"rx_rate_proxy,omitempty"`
	TxRateDirect  int64                  `protobuf:"varint,3,opt,name=tx_rate_direct,json=txRateDirect,proto3" json:"tx_rate_direct,omitempty"`
	RxRateDirect  int64                  `protobuf:"varint,4,opt,name=rx_rate_direct,json=rxRateDirect,proto3" json:"rx_rate_direct,omitempty"`
	TxTotal       int64                  `protobuf:"varint,5,opt,name=tx_total,json=txTotal,proto3" json:"tx_total,omitempty"`
	RxTotal       int64                  `protobuf:"varint,6,opt,name=rx_total,json=rxTotal,proto3" json:"rx_total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpeedUpdate) Reset() {
	*x = SpeedUpdate{}
	mi := &file_husi_v1_core_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpeedUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpeedUpdate) ProtoMessage() {}

func (x *SpeedUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_core_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpeedUpdate.ProtoReflect.Descriptor instead.
func (*SpeedUpdate) Descriptor() ([]byte, []int) {
	return file_husi_v1_core_proto_rawDescGZIP(), []int{10}
}

func (x *SpeedUpdate) GetTxRateProxy() int64 {
	if x != nil {
		return x.TxRateProxy
	}
	return 0
}

func (x *SpeedUpdate) GetRxRateProxy() int64 {
	if x != nil {
		return x.RxRateProxy
	}
	return 0
}

func (x *SpeedUpdate) GetTxRateDirect() int64 {
	if x != nil {
		return x.TxRateDirect
	}
	return 0
}

func (x *SpeedUpdate) GetRxRateDirect() int64 {
	if x != nil {
		return x.RxRateDirect
	}
	return 0
}

func (x *SpeedUpdate) GetTxTotal() int64 {
	if x != nil {
		return x.TxTotal
	}
	return 0
}

func (x *SpeedUpdate) GetRxTotal() int64 {
	if x != nil {
		return x.RxTotal
	}
	return 0
}

type ServiceAlert struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Kind  AlertKind              `protobuf:"varint,1,opt,name=kind,proto3,enum=husi.v1.AlertKind" json:"kind,omitempty"`
	// Meaning depends on the kind: the message for COMMON, the plugin name for
	// MISSING_PLUGIN, empty for NEED_WIFI_PERMISSION.
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceAlert) Reset() {
	*x = ServiceAlert{}
	mi := &file_husi_v1_core_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceAlert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceAlert) ProtoMessage() {}

func (x *ServiceAlert) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_core_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceAlert.ProtoReflect.Descriptor instead.
func (*ServiceAlert) Descriptor() ([]byte, []int) {
	return file_husi_v1_core_proto_rawDescGZIP(), []int{11}
}

func (x *ServiceAlert) GetKind() AlertKind {
	if x != nil {
		return x.Kind
	}
	return AlertKind_ALERT_KIND_UNSPECIFIED
}

func (x *ServiceAlert) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_husi_v1_core_proto protoreflect.FileDescriptor

const file_husi_v1_core_proto_rawDesc = "" +
	"\n" +
	"\x12husi/v1/core.proto\x12\ahusi.v1\"\x13\n" +
	"\x11GetVersionRequest\"\xa6\x01\n" +
	"\x12GetVersionResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12(\n" +
	"\x10sing_box_version\x18\x02 \x01(\tR\x0esingBoxVersion\x12+\n" +
	"\x11build_environment\x18\x03 \x01(\tR\x10buildEnvironment\x12\x1f\n" +
	"\vapi_version\x18\x04 \x01(\rR\n" +
	"apiVersion\"\x99\x01\n" +
	"\x0eURLTestRequest\x12!\n" +
	"\foutbound_tag\x18\x01 \x01(\tR\voutboundTag\x12\x12\n" +
	"\x04link\x18\x02 \x01(\tR\x04link\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x03 \x01(\x05R\ttimeoutMs\x121\n" +
	"\aoptions\x18\x04 \x01(\v2\x17.husi.v1.URLTestOptionsR\aoptions\"0\n" +
	"\x0fURLTestResponse\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x01 \x01(\x05R\tlatencyMs\"i\n" +
	"\x0eURLTestOptions\x12#\n" +
	"\runified_delay\x18\x01 \x01(\bR\funifiedDelay\x122\n" +
	"\x15ignore_handshake_time\x18\x02 \x01(\bR\x13ignoreHandshakeTime\"\x15\n" +
	"\x13ResetNetworkRequest\"\x16\n" +
	"\x14ResetNetworkResponse\"\x1f\n" +
	"\x1dSubscribeServiceEventsRequest\"\xbb\x01\n" +
	"\x1eSubscribeServiceEventsResponse\x123\n" +
	"\x05state\x18\x01 \x01(\v2\x1b.husi.v1.ServiceStateUpdateH\x00R\x05state\x12,\n" +
	"\x05speed\x18\x02 \x01(\v2\x14.husi.v1.SpeedUpdateH\x00R\x05speed\x12-\n" +
	"\x05alert\x18\x03 \x01(\v2\x15.husi.v1.ServiceAlertH\x00R\x05alertB\a\n" +
	"\x05event\"g\n" +
	"\x12ServiceStateUpdate\x12.\n" +
	"\x05state\x18\x01 \x01(\x0e2\x18.husi.v1.ServiceRunStateR\x05state\x12!\n" +
	"\fprofile_name\x18\x02 \x01(\tR\vprofileName\"\xd7\x01\n" +
	"\vSpeedUpdate\x12\"\n" +
	"\rtx_rate_proxy\x18\x01 \x01(\x03R\vtxRateProxy\x12\"\n" +
	"\rrx_rate_proxy\x18\x02 \x01(\x03R\vrxRateProxy\x12$\n" +
	"\x0etx_rate_direct\x18\x03 \x01(\x03R\ftxRateDirect\x12$\n" +
	"\x0erx_rate_direct\x18\x04 \x01(\x03R\frxRateDirect\x12\x19\n" +
	"\btx_total\x18\x05 \x01(\x03R\atxTotal\x12\x19\n" +
	"\brx_total\x18\x06 \x01(\x03R\arxTotal\"P\n" +
	"\fServiceAlert\x12&\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x12.husi.v1.AlertKindR\x04kind\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*\xd2\x01\n" +
	"\x0fServiceRunState\x12!\n" +
	"\x1dSERVICE_RUN_STATE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16SERVICE_RUN_STATE_IDLE\x10\x01\x12 \n" +
	"\x1cSERVICE_RUN_STATE_CONNECTING\x10\x02\x12\x1f\n" +
	"\x1bSERVICE_RUN_STATE_CONNECTED\x10\x03\x12\x1e\n" +
	"\x1aSERVICE_RUN_STATE_STOPPING\x10\x04\x12\x1d\n" +
	"\x19SERVICE_RUN_STATE_STOPPED\x10\x05*\x82\x01\n" +
	"\tAlertKind\x12\x1a\n" +
	"\x16ALERT_KIND_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11ALERT_KIND_COMMON\x10\x01\x12\x1d\n" +
	"\x19ALERT_KIND_MISSING_PLUGIN\x10\x02\x12#\n" +
	"\x1fALERT_KIND_NEED_WIFI_PERMISSION\x10\x032\xcc\x02\n" +
	"\vCoreService\x12E\n" +
	"\n" +
	"GetVersion\x12\x1a.husi.v1.GetVersionRequest\x1a\x1b.husi.v1.GetVersionResponse\x12<\n" +
	"\aURLTest\x12\x17.husi.v1.URLTestRequest\x1a\x18.husi.v1.URLTestResponse\x12K\n" +
	"\fResetNetwork\x12\x1c.husi.v1.ResetNetworkRequest\x1a\x1d.husi.v1.ResetNetworkResponse\x12k\n" +
	"\x16SubscribeServiceEvents\x12&.husi.v1.SubscribeServiceEventsRequest\x1a'.husi.v1.SubscribeServiceEventsResponse0\x01B:\n" +
	"\x10fr.husi.proto.v1B\tCoreProtoP\x01Z\x19libcore/pb/husi/v1;husiv1b\x06proto3"

var (
	file_husi_v1_core_proto_rawDescOnce sync.Once
	file_husi_v1_core_proto_rawDescData []byte
)

func file_husi_v1_core_proto_rawDescGZIP() []byte {
	file_husi_v1_core_proto_rawDescOnce.Do(func() {
		file_husi_v1_core_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_husi_v1_core_proto_rawDesc), len(file_husi_v1_core_proto_rawDesc)))
	})
	return file_husi_v1_core_proto_rawDescData
}

var file_husi_v1_core_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_husi_v1_core_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_husi_v1_core_proto_goTypes = []any{
	(ServiceRunState)(0),                   // 0: husi.v1.ServiceRunState
	(AlertKind)(0),                         // 1: husi.v1.AlertKind
	(*GetVersionRequest)(nil),              // 2: husi.v1.GetVersionRequest
	(*GetVersionResponse)(nil),             // 3: husi.v1.GetVersionResponse
	(*URLTestRequest)(nil),                 // 4: husi.v1.URLTestRequest
	(*URLTestResponse)(nil),                // 5: husi.v1.URLTestResponse
	(*URLTestOptions)(nil),                 // 6: husi.v1.URLTestOptions
	(*ResetNetworkRequest)(nil),            // 7: husi.v1.ResetNetworkRequest
	(*ResetNetworkResponse)(nil),           // 8: husi.v1.ResetNetworkResponse
	(*SubscribeServiceEventsRequest)(nil),  // 9: husi.v1.SubscribeServiceEventsRequest
	(*SubscribeServiceEventsResponse)(nil), // 10: husi.v1.SubscribeServiceEventsResponse
	(*ServiceStateUpdate)(nil),             // 11: husi.v1.ServiceStateUpdate
	(*SpeedUpdate)(nil),                    // 12: husi.v1.SpeedUpdate
	(*ServiceAlert)(nil),                   // 13: husi.v1.ServiceAlert
}
var file_husi_v1_core_proto_depIdxs = []int32{
	6,  // 0: husi.v1.URLTestRequest.options:type_name -> husi.v1.URLTestOptions
	11, // 1: husi.v1.SubscribeServiceEventsResponse.state:type_name -> husi.v1.ServiceStateUpdate
	12, // 2: husi.v1.SubscribeServiceEventsResponse.speed:type_name -> husi.v1.SpeedUpdate
	13, // 3: husi.v1.SubscribeServiceEventsResponse.alert:type_name -> husi.v1.ServiceAlert
	0,  // 4: husi.v1.ServiceStateUpdate.state:type_name -> husi.v1.ServiceRunState
	1,  // 5: husi.v1.ServiceAlert.kind:type_name -> husi.v1.AlertKind
	2,  // 6: husi.v1.CoreService.GetVersion:input_type -> husi.v1.GetVersionRequest
	4,  // 7: husi.v1.CoreService.URLTest:input_type -> husi.v1.URLTestRequest
	7,  // 8: husi.v1.CoreService.ResetNetwork:input_type -> husi.v1.ResetNetworkRequest
	9,  // 9: husi.v1.CoreService.SubscribeServiceEvents:input_type -> husi.v1.SubscribeServiceEventsRequest
	3,  // 10: husi.v1.CoreService.GetVersion:output_type -> husi.v1.GetVersionResponse
	5,  // 11: husi.v1.CoreService.URLTest:output_type -> husi.v1.URLTestResponse
	8,  // 12: husi.v1.CoreService.ResetNetwork:output_type -> husi.v1.ResetNetworkResponse
	10, // 13: husi.v1.CoreService.SubscribeServiceEvents:output_type -> husi.v1.SubscribeServiceEventsResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_husi_v1_core_proto_init() }
func file_husi_v1_core_proto_init() {
	if File_husi_v1_core_proto != nil {
		return
	}
	file_husi_v1_core_proto_msgTypes[8].OneofWrappers = []any{
		(*SubscribeServiceEventsResponse_State)(nil),
		(*SubscribeServiceEventsResponse_Speed)(nil),
		(*SubscribeServiceEventsResponse_Alert)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_husi_v1_core_proto_rawDesc), len(file_husi_v1_core_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_husi_v1_core_proto_goTypes,
		DependencyIndexes: file_husi_v1_core_proto_depIdxs,
		EnumInfos:         file_husi_v1_core_proto_enumTypes,
		MessageInfos:      file_husi_v1_core_proto_msgTypes,
	}.Build()
	File_husi_v1_core_proto = out.File
	file_husi_v1_core_proto_goTypes = nil
	file_husi_v1_core_proto_depIdxs = nil
}
