// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: husi/v1/daemon.proto

package husiv1

import (
	daemon "github.com/sagernet/sing-box/daemon"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Hosting int32

const (
	Hosting_HOSTING_UNSPECIFIED Hosting = 0
	// Privileged system service, registered with systemd, launchd or the
	// Windows service manager. Survives the UI and can restore on boot.
	Hosting_HOSTING_DAEMON Hosting = 1
	// Unprivileged child of the UI, which it dies with.
	Hosting_HOSTING_SESSION Hosting = 2
)

// Enum value maps for Hosting.
var (
	Hosting_name = map[int32]string{
		0: "HOSTING_UNSPECIFIED",
		1: "HOSTING_DAEMON",
		2: "HOSTING_SESSION",
	}
	Hosting_value = map[string]int32{
		"HOSTING_UNSPECIFIED": 0,
		"HOSTING_DAEMON":      1,
		"HOSTING_SESSION":     2,
	}
)

func (x Hosting) Enum() *Hosting {
	p := new(Hosting)
	*p = x
	return p
}

func (x Hosting) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Hosting) Descriptor() protoreflect.EnumDescriptor {
	return file_husi_v1_daemon_proto_enumTypes[0].Descriptor()
}

func (Hosting) Type() protoreflect.EnumType {
	return &file_husi_v1_daemon_proto_enumTypes[0]
}

func (x Hosting) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Hosting.Descriptor instead.
func (Hosting) EnumDescriptor() ([]byte, []int) {
	return file_husi_v1_daemon_proto_rawDescGZIP(), []int{0}
}

type GetDaemonInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDaemonInfoRequest) Reset() {
	*x = GetDaemonInfoRequest{}
	mi := &file_husi_v1_daemon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDaemonInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDaemonInfoRequest) ProtoMessage() {}

func (x *GetDaemonInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_daemon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDaemonInfoRequest.ProtoReflect.Descriptor instead.
func (*GetDaemonInfoRequest) Descriptor() ([]byte, []int) {
	return file_husi_v1_daemon_proto_rawDescGZIP(), []int{0}
}

type GetDaemonInfoResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Version string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// Revision of this contract, matching CoreService.GetVersion. A client whose
	// own revision differs blocks service control and offers a daemon update.
	ApiVersion   uint32        `protobuf:"varint,2,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Hosting      Hosting       `protobuf:"varint,3,opt,name=hosting,proto3,enum=husi.v1.Hosting" json:"hosting,omitempty"`
	Ownership    *Ownership    `protobuf:"bytes,4,opt,name=ownership,proto3" json:"ownership,omitempty"`
	Capabilities *Capabilities `protobuf:"bytes,5,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	// Whether the daemon is configured to restore the last service on boot
	// (StartAtBoot marker). Distinct from Capabilities.start_at_boot, which
	// only says the host supports the feature.
	StartAtBoot   bool `protobuf:"varint,6,opt,name=start_at_boot,json=startAtBoot,proto3" json:"start_at_boot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDaemonInfoResponse) Reset() {
	*x = GetDaemonInfoResponse{}
	mi := &file_husi_v1_daemon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDaemonInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDaemonInfoResponse) ProtoMessage() {}

func (x *GetDaemonInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_daemon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDaemonInfoResponse.ProtoReflect.Descriptor instead.
func (*GetDaemonInfoResponse) Descriptor() ([]byte, []int) {
	return file_husi_v1_daemon_proto_rawDescGZIP(), []int{1}
}

func (x *GetDaemonInfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetDaemonInfoResponse) GetApiVersion() uint32 {
	if x != nil {
		return x.ApiVersion
	}
	return 0
}

func (x *GetDaemonInfoResponse) GetHosting() Hosting {
	if x != nil {
		return x.Hosting
	}
	return Hosting_HOSTING_UNSPECIFIED
}

func (x *GetDaemonInfoResponse) GetOwnership() *Ownership {
	if x != nil {
		return x.Ownership
	}
	return nil
}

func (x *GetDaemonInfoResponse) GetCapabilities() *Capabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *GetDaemonInfoResponse) GetStartAtBoot() bool {
	if x != nil {
		return x.StartAtBoot
	}
	return false
}

type Ownership struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Claimed       bool                   `protobuf:"varint,1,opt,name=claimed,proto3" json:"claimed,omitempty"`
	OwnedByCaller bool                   `protobuf:"varint,2,opt,name=owned_by_caller,json=ownedByCaller,proto3" json:"owned_by_caller,omitempty"`
	// Platform identifier of the owner: the numeric uid on unix, the SID on
	// Windows. Empty while unclaimed.
	OwnerId string `protobuf:"bytes,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	// Human readable owner, for the conflict message the UI shows.
	OwnerName     string `protobuf:"bytes,4,opt,name=owner_name,json=ownerName,proto3" json:"owner_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ownership) Reset() {
	*x = Ownership{}
	mi := &file_husi_v1_daemon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ownership) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ownership) ProtoMessage() {}

func (x *Ownership) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_daemon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ownership.ProtoReflect.Descriptor instead.
func (*Ownership) Descriptor() ([]byte, []int) {
	return file_husi_v1_daemon_proto_rawDescGZIP(), []int{2}
}

func (x *Ownership) GetClaimed() bool {
	if x != nil {
		return x.Claimed
	}
	return false
}

func (x *Ownership) GetOwnedByCaller() bool {
	if x != nil {
		return x.OwnedByCaller
	}
	return false
}

func (x *Ownership) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Ownership) GetOwnerName() string {
	if x != nil {
		return x.OwnerName
	}
	return ""
}

type Capabilities struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// False in session mode, where opening a tun device is out of reach.
	Tun           bool `protobuf:"varint,1,opt,name=tun,proto3" json:"tun,omitempty"`
	StartAtBoot   bool `protobuf:"varint,2,opt,name=start_at_boot,json=startAtBoot,proto3" json:"start_at_boot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Capabilities) Reset() {
	*x = Capabilities{}
	mi := &file_husi_v1_daemon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capabilities) ProtoMessage() {}

func (x *Capabilities) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_daemon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capabilities.ProtoReflect.Descriptor instead.
func (*Capabilities) Descriptor() ([]byte, []int) {
	return file_husi_v1_daemon_proto_rawDescGZIP(), []int{3}
}

func (x *Capabilities) GetTun() bool {
	if x != nil {
		return x.Tun
	}
	return false
}

func (x *Capabilities) GetStartAtBoot() bool {
	if x != nil {
		return x.StartAtBoot
	}
	return false
}

type ClaimServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimServiceRequest) Reset() {
	*x = ClaimServiceRequest{}
	mi := &file_husi_v1_daemon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimServiceRequest) ProtoMessage() {}

func (x *ClaimServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_daemon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimServiceRequest.ProtoReflect.Descriptor instead.
func (*ClaimServiceRequest) Descriptor() ([]byte, []int) {
	return file_husi_v1_daemon_proto_rawDescGZIP(), []int{4}
}

type ClaimServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimServiceResponse) Reset() {
	*x = ClaimServiceResponse{}
	mi := &file_husi_v1_daemon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimServiceResponse) ProtoMessage() {}

func (x *ClaimServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_daemon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimServiceResponse.ProtoReflect.Descriptor instead.
func (*ClaimServiceResponse) Descriptor() ([]byte, []int) {
	return file_husi_v1_daemon_proto_rawDescGZIP(), []int{5}
}

// TakeOverService claims a daemon another user owns. The previous owner's
// connections are dropped and the running service keeps going under the new
// owner until it is stopped or replaced.
type TakeOverServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TakeOverServiceRequest) Reset() {
	*x = TakeOverServiceRequest{}
	mi := &file_husi_v1_daemon_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TakeOverServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TakeOverServiceRequest) ProtoMessage() {}

func (x *TakeOverServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_daemon_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TakeOverServiceRequest.ProtoReflect.Descriptor instead.
func (*TakeOverServiceRequest) Descriptor() ([]byte, []int) {
	return file_husi_v1_daemon_proto_rawDescGZIP(), []int{6}
}

type TakeOverServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TakeOverServiceResponse) Reset() {
	*x = TakeOverServiceResponse{}
	mi := &file_husi_v1_daemon_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TakeOverServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TakeOverServiceResponse) ProtoMessage() {}

func (x *TakeOverServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_daemon_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TakeOverServiceResponse.ProtoReflect.Descriptor instead.
func (*TakeOverServiceResponse) Descriptor() ([]byte, []int) {
	return file_husi_v1_daemon_proto_rawDescGZIP(), []int{7}
}

type StartServiceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Rendered config, pushed as content so starting never depends on the
	// daemon reading the caller's config storage. Paths inside the config
	// (local rule sets, custom config fragments) are owner-supplied like the
	// rest of it: the daemon acts with owner-level trust, and cross-user
	// protection comes from ownership authentication, not path restrictions.
	Config         string               `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	Plugins        []*PluginProcessSpec `protobuf:"bytes,2,rep,name=plugins,proto3" json:"plugins,omitempty"`
	Options        *ServiceOptions      `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
	ClientMetadata *ClientMetadata      `protobuf:"bytes,4,opt,name=client_metadata,json=clientMetadata,proto3" json:"client_metadata,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StartServiceRequest) Reset() {
	*x = StartServiceRequest{}
	mi := &file_husi_v1_daemon_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartServiceRequest) ProtoMessage() {}

func (x *StartServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_daemon_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartServiceRequest.ProtoReflect.Descriptor instead.
func (*StartServiceRequest) Descriptor() ([]byte, []int) {
	return file_husi_v1_daemon_proto_rawDescGZIP(), []int{8}
}

func (x *StartServiceRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *StartServiceRequest) GetPlugins() []*PluginProcessSpec {
	if x != nil {
		return x.Plugins
	}
	return nil
}

func (x *StartServiceRequest) GetOptions() *ServiceOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *StartServiceRequest) GetClientMetadata() *ClientMetadata {
	if x != nil {
		return x.ClientMetadata
	}
	return nil
}

// PluginProcessSpec describes one protocol plugin the host spawns and
// supervises alongside the instance. The daemon runs these with the owner
// user's credentials, never with its own.
//
// Arguments and environment values may reference a file by name with the token
// "${file:<name>}", which the host replaces with the absolute path it wrote.
// Callers cannot know that path, since the working directory belongs to the
// host.
type PluginProcessSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Plugin identifier such as "mieru-plugin", used in logs and errors.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Executable followed by its arguments.
	Command     []string          `protobuf:"bytes,2,rep,name=command,proto3" json:"command,omitempty"`
	Environment map[string]string `protobuf:"bytes,3,rep,name=environment,proto3" json:"environment,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Written into the host working directory before the process starts, and
	// removed when it stops.
	Files         []*PluginFile `protobuf:"bytes,4,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginProcessSpec) Reset() {
	*x = PluginProcessSpec{}
	mi := &file_husi_v1_daemon_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginProcessSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginProcessSpec) ProtoMessage() {}

func (x *PluginProcessSpec) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_daemon_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginProcessSpec.ProtoReflect.Descriptor instead.
func (*PluginProcessSpec) Descriptor() ([]byte, []int) {
	return file_husi_v1_daemon_proto_rawDescGZIP(), []int{9}
}

func (x *PluginProcessSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginProcessSpec) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *PluginProcessSpec) GetEnvironment() map[string]string {
	if x != nil {
		return x.Environment
	}
	return nil
}

func (x *PluginProcessSpec) GetFiles() []*PluginFile {
	if x != nil {
		return x.Files
	}
	return nil
}

type PluginFile struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// File name inside the host working directory, without a separator.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Content       []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginFile) Reset() {
	*x = PluginFile{}
	mi := &file_husi_v1_daemon_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginFile) ProtoMessage() {}

func (x *PluginFile) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_daemon_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginFile.ProtoReflect.Descriptor instead.
func (*PluginFile) Descriptor() ([]byte, []int) {
	return file_husi_v1_daemon_proto_rawDescGZIP(), []int{10}
}

func (x *PluginFile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginFile) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type ServiceOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogLevel      daemon.LogLevel        `protobuf:"varint,1,opt,name=log_level,json=logLevel,proto3,enum=daemon.LogLevel" json:"log_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceOptions) Reset() {
	*x = ServiceOptions{}
	mi := &file_husi_v1_daemon_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceOptions) ProtoMessage() {}

func (x *ServiceOptions) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_daemon_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceOptions.ProtoReflect.Descriptor instead.
func (*ServiceOptions) Descriptor() ([]byte, []int) {
	return file_husi_v1_daemon_proto_rawDescGZIP(), []int{11}
}

func (x *ServiceOptions) GetLogLevel() daemon.LogLevel {
	if x != nil {
		return x.LogLevel
	}
	return daemon.LogLevel(0)
}

// Which profile the running service came from. The daemon only stores it and
// hands it back, so a UI that reconnects to a daemon it did not start knows
// what it is looking at. Service state itself comes from sing-box's
// daemon.StartedService.SubscribeServiceStatus, the single source of truth the
// Kotlin state machine mirrors.
type ClientMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileId     int64                  `protobuf:"varint,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	ProfileName   string                 `protobuf:"bytes,2,opt,name=profile_name,json=profileName,proto3" json:"profile_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMetadata) Reset() {
	*x = ClientMetadata{}
	mi := &file_husi_v1_daemon_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMetadata) ProtoMessage() {}

func (x *ClientMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_daemon_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMetadata.ProtoReflect.Descriptor instead.
func (*ClientMetadata) Descriptor() ([]byte, []int) {
	return file_husi_v1_daemon_proto_rawDescGZIP(), []int{12}
}

func (x *ClientMetadata) GetProfileId() int64 {
	if x != nil {
		return x.ProfileId
	}
	return 0
}

func (x *ClientMetadata) GetProfileName() string {
	if x != nil {
		return x.ProfileName
	}
	return ""
}

type StartServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartServiceResponse) Reset() {
	*x = StartServiceResponse{}
	mi := &file_husi_v1_daemon_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartServiceResponse) ProtoMessage() {}

func (x *StartServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_daemon_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartServiceResponse.ProtoReflect.Descriptor instead.
func (*StartServiceResponse) Descriptor() ([]byte, []int) {
	return file_husi_v1_daemon_proto_rawDescGZIP(), []int{13}
}

type StopServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopServiceRequest) Reset() {
	*x = StopServiceRequest{}
	mi := &file_husi_v1_daemon_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopServiceRequest) ProtoMessage() {}

func (x *StopServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_daemon_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopServiceRequest.ProtoReflect.Descriptor instead.
func (*StopServiceRequest) Descriptor() ([]byte, []int) {
	return file_husi_v1_daemon_proto_rawDescGZIP(), []int{14}
}

type StopServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopServiceResponse) Reset() {
	*x = StopServiceResponse{}
	mi := &file_husi_v1_daemon_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopServiceResponse) ProtoMessage() {}

func (x *StopServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_daemon_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopServiceResponse.ProtoReflect.Descriptor instead.
func (*StopServiceResponse) Descriptor() ([]byte, []int) {
	return file_husi_v1_daemon_proto_rawDescGZIP(), []int{15}
}

type GetClientMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClientMetadataRequest) Reset() {
	*x = GetClientMetadataRequest{}
	mi := &file_husi_v1_daemon_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClientMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientMetadataRequest) ProtoMessage() {}

func (x *GetClientMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_daemon_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClientMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetClientMetadataRequest) Descriptor() ([]byte, []int) {
	return file_husi_v1_daemon_proto_rawDescGZIP(), []int{16}
}

type GetClientMetadataResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// What the last StartService carried, empty once the service is idle.
	ClientMetadata *ClientMetadata `protobuf:"bytes,1,opt,name=client_metadata,json=clientMetadata,proto3" json:"client_metadata,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetClientMetadataResponse) Reset() {
	*x = GetClientMetadataResponse{}
	mi := &file_husi_v1_daemon_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClientMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientMetadataResponse) ProtoMessage() {}

func (x *GetClientMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_daemon_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClientMetadataResponse.ProtoReflect.Descriptor instead.
func (*GetClientMetadataResponse) Descriptor() ([]byte, []int) {
	return file_husi_v1_daemon_proto_rawDescGZIP(), []int{17}
}

func (x *GetClientMetadataResponse) GetClientMetadata() *ClientMetadata {
	if x != nil {
		return x.ClientMetadata
	}
	return nil
}

type SetStartAtBootRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// When enabled, the daemon restores the last started service on boot,
	// provided it was running when the machine went down.
	Enabled       bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetStartAtBootRequest) Reset() {
	*x = SetStartAtBootRequest{}
	mi := &file_husi_v1_daemon_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetStartAtBootRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetStartAtBootRequest) ProtoMessage() {}

func (x *SetStartAtBootRequest) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_daemon_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetStartAtBootRequest.ProtoReflect.Descriptor instead.
func (*SetStartAtBootRequest) Descriptor() ([]byte, []int) {
	return file_husi_v1_daemon_proto_rawDescGZIP(), []int{18}
}

func (x *SetStartAtBootRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type SetStartAtBootResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetStartAtBootResponse) Reset() {
	*x = SetStartAtBootResponse{}
	mi := &file_husi_v1_daemon_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetStartAtBootResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetStartAtBootResponse) ProtoMessage() {}

func (x *SetStartAtBootResponse) ProtoReflect() protoreflect.Message {
	mi := &file_husi_v1_daemon_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetStartAtBootResponse.ProtoReflect.Descriptor instead.
func (*SetStartAtBootResponse) Descriptor() ([]byte, []int) {
	return file_husi_v1_daemon_proto_rawDescGZIP(), []int{19}
}

var File_husi_v1_daemon_proto protoreflect.FileDescriptor

const file_husi_v1_daemon_proto_rawDesc = "" +
	"\n" +
	"\x14husi/v1/daemon.proto\x12\ahusi.v1\x1a\x1cdaemon/started_service.proto\"\x16\n" +
	"\x14GetDaemonInfoRequest\"\x8f\x02\n" +
	"\x15GetDaemonInfoResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1f\n" +
	"\vapi_version\x18\x02 \x01(\rR\n" +
	"apiVersion\x12*\n" +
	"\ahosting\x18\x03 \x01(\x0e2\x10.husi.v1.HostingR\ahosting\x120\n" +
	"\townership\x18\x04 \x01(\v2\x12.husi.v1.OwnershipR\townership\x129\n" +
	"\fcapabilities\x18\x05 \x01(\v2\x15.husi.v1.CapabilitiesR\fcapabilities\x12\"\n" +
	"\rstart_at_boot\x18\x06 \x01(\bR\vstartAtBoot\"\x87\x01\n" +
	"\tOwnership\x12\x18\n" +
	"\aclaimed\x18\x01 \x01(\bR\aclaimed\x12&\n" +
	"\x0fowned_by_caller\x18\x02 \x01(\bR\rownedByCaller\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\tR\aownerId\x12\x1d\n" +
	"\n" +
	"owner_name\x18\x04 \x01(\tR\townerName\"D\n" +
	"\fCapabilities\x12\x10\n" +
	"\x03tun\x18\x01 \x01(\bR\x03tun\x12\"\n" +
	"\rstart_at_boot\x18\x02 \x01(\bR\vstartAtBoot\"\x15\n" +
	"\x13ClaimServiceRequest\"\x16\n" +
	"\x14ClaimServiceResponse\"\x18\n" +
	"\x16TakeOverServiceRequest\"\x19\n" +
	"\x17TakeOverServiceResponse\"\xd8\x01\n" +
	"\x13StartServiceRequest\x12\x16\n" +
	"\x06config\x18\x01 \x01(\tR\x06config\x124\n" +
	"\aplugins\x18\x02 \x03(\v2\x1a.husi.v1.PluginProcessSpecR\aplugins\x121\n" +
	"\aoptions\x18\x03 \x01(\v2\x17.husi.v1.ServiceOptionsR\aoptions\x12@\n" +
	"\x0fclient_metadata\x18\x04 \x01(\v2\x17.husi.v1.ClientMetadataR\x0eclientMetadata\"\xfb\x01\n" +
	"\x11PluginProcessSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acommand\x18\x02 \x03(\tR\acommand\x12M\n" +
	"\venvironment\x18\x03 \x03(\v2+.husi.v1.PluginProcessSpec.EnvironmentEntryR\venvironment\x12)\n" +
	"\x05files\x18\x04 \x03(\v2\x13.husi.v1.PluginFileR\x05files\x1a>\n" +
	"\x10EnvironmentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\":\n" +
	"\n" +
	"PluginFile\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\"?\n" +
	"\x0eServiceOptions\x12-\n" +
	"\tlog_level\x18\x01 \x01(\x0e2\x10.daemon.LogLevelR\blogLevel\"R\n" +
	"\x0eClientMetadata\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\x03R\tprofileId\x12!\n" +
	"\fprofile_name\x18\x02 \x01(\tR\vprofileName\"\x16\n" +
	"\x14StartServiceResponse\"\x14\n" +
	"\x12StopServiceRequest\"\x15\n" +
	"\x13StopServiceResponse\"\x1a\n" +
	"\x18GetClientMetadataRequest\"]\n" +
	"\x19GetClientMetadataResponse\x12@\n" +
	"\x0fclient_metadata\x18\x01 \x01(\v2\x17.husi.v1.ClientMetadataR\x0eclientMetadata\"1\n" +
	"\x15SetStartAtBootRequest\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\"\x18\n" +
	"\x16SetStartAtBootResponse*K\n" +
	"\aHosting\x12\x17\n" +
	"\x13HOSTING_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eHOSTING_DAEMON\x10\x01\x12\x13\n" +
	"\x0fHOSTING_SESSION\x10\x022\xc8\x04\n" +
	"\rDaemonService\x12N\n" +
	"\rGetDaemonInfo\x12\x1d.husi.v1.GetDaemonInfoRequest\x1a\x1e.husi.v1.GetDaemonInfoResponse\x12K\n" +
	"\fClaimService\x12\x1c.husi.v1.ClaimServiceRequest\x1a\x1d.husi.v1.ClaimServiceResponse\x12T\n" +
	"\x0fTakeOverService\x12\x1f.husi.v1.TakeOverServiceRequest\x1a .husi.v1.TakeOverServiceResponse\x12K\n" +
	"\fStartService\x12\x1c.husi.v1.StartServiceRequest\x1a\x1d.husi.v1.StartServiceResponse\x12H\n" +
	"\vStopService\x12\x1b.husi.v1.StopServiceRequest\x1a\x1c.husi.v1.StopServiceResponse\x12Z\n" +
	"\x11GetClientMetadata\x12!.husi.v1.GetClientMetadataRequest\x1a\".husi.v1.GetClientMetadataResponse\x12Q\n" +
	"\x0eSetStartAtBoot\x12\x1e.husi.v1.SetStartAtBootRequest\x1a\x1f.husi.v1.SetStartAtBootResponseB<\n" +
	"\x10fr.husi.proto.v1B\vDaemonProtoP\x01Z\x19libcore/pb/husi/v1;husiv1b\x06proto3"

var (
	file_husi_v1_daemon_proto_rawDescOnce sync.Once
	file_husi_v1_daemon_proto_rawDescData []byte
)

func file_husi_v1_daemon_proto_rawDescGZIP() []byte {
	file_husi_v1_daemon_proto_rawDescOnce.Do(func() {
		file_husi_v1_daemon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_husi_v1_daemon_proto_rawDesc), len(file_husi_v1_daemon_proto_rawDesc)))
	})
	return file_husi_v1_daemon_proto_rawDescData
}

var file_husi_v1_daemon_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_husi_v1_daemon_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_husi_v1_daemon_proto_goTypes = []any{
	(Hosting)(0),                      // 0: husi.v1.Hosting
	(*GetDaemonInfoRequest)(nil),      // 1: husi.v1.GetDaemonInfoRequest
	(*GetDaemonInfoResponse)(nil),     // 2: husi.v1.GetDaemonInfoResponse
	(*Ownership)(nil),                 // 3: husi.v1.Ownership
	(*Capabilities)(nil),              // 4: husi.v1.Capabilities
	(*ClaimServiceRequest)(nil),       // 5: husi.v1.ClaimServiceRequest
	(*ClaimServiceResponse)(nil),      // 6: husi.v1.ClaimServiceResponse
	(*TakeOverServiceRequest)(nil),    // 7: husi.v1.TakeOverServiceRequest
	(*TakeOverServiceResponse)(nil),   // 8: husi.v1.TakeOverServiceResponse
	(*StartServiceRequest)(nil),       // 9: husi.v1.StartServiceRequest
	(*PluginProcessSpec)(nil),         // 10: husi.v1.PluginProcessSpec
	(*PluginFile)(nil),                // 11: husi.v1.PluginFile
	(*ServiceOptions)(nil),            // 12: husi.v1.ServiceOptions
	(*ClientMetadata)(nil),            // 13: husi.v1.ClientMetadata
	(*StartServiceResponse)(nil),      // 14: husi.v1.StartServiceResponse
	(*StopServiceRequest)(nil),        // 15: husi.v1.StopServiceRequest
	(*StopServiceResponse)(nil),       // 16: husi.v1.StopServiceResponse
	(*GetClientMetadataRequest)(nil),  // 17: husi.v1.GetClientMetadataRequest
	(*GetClientMetadataResponse)(nil), // 18: husi.v1.GetClientMetadataResponse
	(*SetStartAtBootRequest)(nil),     // 19: husi.v1.SetStartAtBootRequest
	(*SetStartAtBootResponse)(nil),    // 20: husi.v1.SetStartAtBootResponse
	nil,                               // 21: husi.v1.PluginProcessSpec.EnvironmentEntry
	(daemon.LogLevel)(0),              // 22: daemon.LogLevel
}
var file_husi_v1_daemon_proto_depIdxs = []int32{
	0,  // 0: husi.v1.GetDaemonInfoResponse.hosting:type_name -> husi.v1.Hosting
	3,  // 1: husi.v1.GetDaemonInfoResponse.ownership:type_name -> husi.v1.Ownership
	4,  // 2: husi.v1.GetDaemonInfoResponse.capabilities:type_name -> husi.v1.Capabilities
	10, // 3: husi.v1.StartServiceRequest.plugins:type_name -> husi.v1.PluginProcessSpec
	12, // 4: husi.v1.StartServiceRequest.options:type_name -> husi.v1.ServiceOptions
	13, // 5: husi.v1.StartServiceRequest.client_metadata:type_name -> husi.v1.ClientMetadata
	21, // 6: husi.v1.PluginProcessSpec.environment:type_name -> husi.v1.PluginProcessSpec.EnvironmentEntry
	11, // 7: husi.v1.PluginProcessSpec.files:type_name -> husi.v1.PluginFile
	22, // 8: husi.v1.ServiceOptions.log_level:type_name -> daemon.LogLevel
	13, // 9: husi.v1.GetClientMetadataResponse.client_metadata:type_name -> husi.v1.ClientMetadata
	1,  // 10: husi.v1.DaemonService.GetDaemonInfo:input_type -> husi.v1.GetDaemonInfoRequest
	5,  // 11: husi.v1.DaemonService.ClaimService:input_type -> husi.v1.ClaimServiceRequest
	7,  // 12: husi.v1.DaemonService.TakeOverService:input_type -> husi.v1.TakeOverServiceRequest
	9,  // 13: husi.v1.DaemonService.StartService:input_type -> husi.v1.StartServiceRequest
	15, // 14: husi.v1.DaemonService.StopService:input_type -> husi.v1.StopServiceRequest
	17, // 15: husi.v1.DaemonService.GetClientMetadata:input_type -> husi.v1.GetClientMetadataRequest
	19, // 16: husi.v1.DaemonService.SetStartAtBoot:input_type -> husi.v1.SetStartAtBootRequest
	2,  // 17: husi.v1.DaemonService.GetDaemonInfo:output_type -> husi.v1.GetDaemonInfoResponse
	6,  // 18: husi.v1.DaemonService.ClaimService:output_type -> husi.v1.ClaimServiceResponse
	8,  // 19: husi.v1.DaemonService.TakeOverService:output_type -> husi.v1.TakeOverServiceResponse
	14, // 20: husi.v1.DaemonService.StartService:output_type -> husi.v1.StartServiceResponse
	16, // 21: husi.v1.DaemonService.StopService:output_type -> husi.v1.StopServiceResponse
	18, // 22: husi.v1.DaemonService.GetClientMetadata:output_type -> husi.v1.GetClientMetadataResponse
	20, // 23: husi.v1.DaemonService.SetStartAtBoot:output_type -> husi.v1.SetStartAtBootResponse
	17, // [17:24] is the sub-list for method output_type
	10, // [10:17] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_husi_v1_daemon_proto_init() }
func file_husi_v1_daemon_proto_init() {
	if File_husi_v1_daemon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_husi_v1_daemon_proto_rawDesc), len(file_husi_v1_daemon_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_husi_v1_daemon_proto_goTypes,
		DependencyIndexes: file_husi_v1_daemon_proto_depIdxs,
		EnumInfos:         file_husi_v1_daemon_proto_enumTypes,
		MessageInfos:      file_husi_v1_daemon_proto_msgTypes,
	}.Build()
	File_husi_v1_daemon_proto = out.File
	file_husi_v1_daemon_proto_goTypes = nil
	file_husi_v1_daemon_proto_depIdxs = nil
}
