// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: husi/v1/daemon.proto

package husiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DaemonService_GetDaemonInfo_FullMethodName     = "/husi.v1.DaemonService/GetDaemonInfo"
	DaemonService_ClaimService_FullMethodName      = "/husi.v1.DaemonService/ClaimService"
	DaemonService_TakeOverService_FullMethodName   = "/husi.v1.DaemonService/TakeOverService"
	DaemonService_StartService_FullMethodName      = "/husi.v1.DaemonService/StartService"
	DaemonService_StopService_FullMethodName       = "/husi.v1.DaemonService/StopService"
	DaemonService_GetClientMetadata_FullMethodName = "/husi.v1.DaemonService/GetClientMetadata"
	DaemonService_SetStartAtBoot_FullMethodName    = "/husi.v1.DaemonService/SetStartAtBoot"
)

// DaemonServiceClient is the client API for DaemonService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DaemonService owns the lifecycle of the instance that daemon.StartedService
// exposes. Only the desktop hostings serve it: the privileged daemon and the
// unprivileged session child. Android keeps its own start path, because the
// platform mandates startService, VpnService.prepare and a notification.
//
// sing-box's own desktop.DesktopService covers the same ground, and husi
// deliberately does not speak it: it cannot carry husi's plugin processes or
// pushed assets, and its generated Go lives in a main package that nothing can
// import. The core-scoped contract is where compatibility pays, and that one
// husi shares verbatim.
//
// The daemon may outlive several UI processes and serve several local users,
// so it has an owner: the first client to claim it. Other local users are
// refused until they take over.
type DaemonServiceClient interface {
	GetDaemonInfo(ctx context.Context, in *GetDaemonInfoRequest, opts ...grpc.CallOption) (*GetDaemonInfoResponse, error)
	ClaimService(ctx context.Context, in *ClaimServiceRequest, opts ...grpc.CallOption) (*ClaimServiceResponse, error)
	TakeOverService(ctx context.Context, in *TakeOverServiceRequest, opts ...grpc.CallOption) (*TakeOverServiceResponse, error)
	StartService(ctx context.Context, in *StartServiceRequest, opts ...grpc.CallOption) (*StartServiceResponse, error)
	StopService(ctx context.Context, in *StopServiceRequest, opts ...grpc.CallOption) (*StopServiceResponse, error)
	GetClientMetadata(ctx context.Context, in *GetClientMetadataRequest, opts ...grpc.CallOption) (*GetClientMetadataResponse, error)
	SetStartAtBoot(ctx context.Context, in *SetStartAtBootRequest, opts ...grpc.CallOption) (*SetStartAtBootResponse, error)
}

type daemonServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDaemonServiceClient(cc grpc.ClientConnInterface) DaemonServiceClient {
	return &daemonServiceClient{cc}
}

func (c *daemonServiceClient) GetDaemonInfo(ctx context.Context, in *GetDaemonInfoRequest, opts ...grpc.CallOption) (*GetDaemonInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDaemonInfoResponse)
	err := c.cc.Invoke(ctx, DaemonService_GetDaemonInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) ClaimService(ctx context.Context, in *ClaimServiceRequest, opts ...grpc.CallOption) (*ClaimServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClaimServiceResponse)
	err := c.cc.Invoke(ctx, DaemonService_ClaimService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) TakeOverService(ctx context.Context, in *TakeOverServiceRequest, opts ...grpc.CallOption) (*TakeOverServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TakeOverServiceResponse)
	err := c.cc.Invoke(ctx, DaemonService_TakeOverService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) StartService(ctx context.Context, in *StartServiceRequest, opts ...grpc.CallOption) (*StartServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartServiceResponse)
	err := c.cc.Invoke(ctx, DaemonService_StartService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) StopService(ctx context.Context, in *StopServiceRequest, opts ...grpc.CallOption) (*StopServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopServiceResponse)
	err := c.cc.Invoke(ctx, DaemonService_StopService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) GetClientMetadata(ctx context.Context, in *GetClientMetadataRequest, opts ...grpc.CallOption) (*GetClientMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetClientMetadataResponse)
	err := c.cc.Invoke(ctx, DaemonService_GetClientMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) SetStartAtBoot(ctx context.Context, in *SetStartAtBootRequest, opts ...grpc.CallOption) (*SetStartAtBootResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetStartAtBootResponse)
	err := c.cc.Invoke(ctx, DaemonService_SetStartAtBoot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DaemonServiceServer is the server API for DaemonService service.
// All implementations must embed UnimplementedDaemonServiceServer
// for forward compatibility.
//
// DaemonService owns the lifecycle of the instance that daemon.StartedService
// exposes. Only the desktop hostings serve it: the privileged daemon and the
// unprivileged session child. Android keeps its own start path, because the
// platform mandates startService, VpnService.prepare and a notification.
//
// sing-box's own desktop.DesktopService covers the same ground, and husi
// deliberately does not speak it: it cannot carry husi's plugin processes or
// pushed assets, and its generated Go lives in a main package that nothing can
// import. The core-scoped contract is where compatibility pays, and that one
// husi shares verbatim.
//
// The daemon may outlive several UI processes and serve several local users,
// so it has an owner: the first client to claim it. Other local users are
// refused until they take over.
type DaemonServiceServer interface {
	GetDaemonInfo(context.Context, *GetDaemonInfoRequest) (*GetDaemonInfoResponse, error)
	ClaimService(context.Context, *ClaimServiceRequest) (*ClaimServiceResponse, error)
	TakeOverService(context.Context, *TakeOverServiceRequest) (*TakeOverServiceResponse, error)
	StartService(context.Context, *StartServiceRequest) (*StartServiceResponse, error)
	StopService(context.Context, *StopServiceRequest) (*StopServiceResponse, error)
	GetClientMetadata(context.Context, *GetClientMetadataRequest) (*GetClientMetadataResponse, error)
	SetStartAtBoot(context.Context, *SetStartAtBootRequest) (*SetStartAtBootResponse, error)
	mustEmbedUnimplementedDaemonServiceServer()
}

// UnimplementedDaemonServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDaemonServiceServer struct{}

func (UnimplementedDaemonServiceServer) GetDaemonInfo(context.Context, *GetDaemonInfoRequest) (*GetDaemonInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDaemonInfo not implemented")
}
func (UnimplementedDaemonServiceServer) ClaimService(context.Context, *ClaimServiceRequest) (*ClaimServiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClaimService not implemented")
}
func (UnimplementedDaemonServiceServer) TakeOverService(context.Context, *TakeOverServiceRequest) (*TakeOverServiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TakeOverService not implemented")
}
func (UnimplementedDaemonServiceServer) StartService(context.Context, *StartServiceRequest) (*StartServiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartService not implemented")
}
func (UnimplementedDaemonServiceServer) StopService(context.Context, *StopServiceRequest) (*StopServiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopService not implemented")
}
func (UnimplementedDaemonServiceServer) GetClientMetadata(context.Context, *GetClientMetadataRequest) (*GetClientMetadataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetClientMetadata not implemented")
}
func (UnimplementedDaemonServiceServer) SetStartAtBoot(context.Context, *SetStartAtBootRequest) (*SetStartAtBootResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetStartAtBoot not implemented")
}
func (UnimplementedDaemonServiceServer) mustEmbedUnimplementedDaemonServiceServer() {}
func (UnimplementedDaemonServiceServer) testEmbeddedByValue()                       {}

// UnsafeDaemonServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DaemonServiceServer will
// result in compilation errors.
type UnsafeDaemonServiceServer interface {
	mustEmbedUnimplementedDaemonServiceServer()
}

func RegisterDaemonServiceServer(s grpc.ServiceRegistrar, srv DaemonServiceServer) {
	// If the following call panics, it indicates UnimplementedDaemonServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DaemonService_ServiceDesc, srv)
}

func _DaemonService_GetDaemonInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDaemonInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).GetDaemonInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_GetDaemonInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).GetDaemonInfo(ctx, req.(*GetDaemonInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_ClaimService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ClaimService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_ClaimService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ClaimService(ctx, req.(*ClaimServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_TakeOverService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TakeOverServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).TakeOverService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_TakeOverService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).TakeOverService(ctx, req.(*TakeOverServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_StartService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).StartService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_StartService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).StartService(ctx, req.(*StartServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_StopService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).StopService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_StopService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).StopService(ctx, req.(*StopServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_GetClientMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClientMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).GetClientMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_GetClientMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).GetClientMetadata(ctx, req.(*GetClientMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_SetStartAtBoot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetStartAtBootRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).SetStartAtBoot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_SetStartAtBoot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).SetStartAtBoot(ctx, req.(*SetStartAtBootRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DaemonService_ServiceDesc is the grpc.ServiceDesc for DaemonService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DaemonService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "husi.v1.DaemonService",
	HandlerType: (*DaemonServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDaemonInfo",
			Handler:    _DaemonService_GetDaemonInfo_Handler,
		},
		{
			MethodName: "ClaimService",
			Handler:    _DaemonService_ClaimService_Handler,
		},
		{
			MethodName: "TakeOverService",
			Handler:    _DaemonService_TakeOverService_Handler,
		},
		{
			MethodName: "StartService",
			Handler:    _DaemonService_StartService_Handler,
		},
		{
			MethodName: "StopService",
			Handler:    _DaemonService_StopService_Handler,
		},
		{
			MethodName: "GetClientMetadata",
			Handler:    _DaemonService_GetClientMetadata_Handler,
		},
		{
			MethodName: "SetStartAtBoot",
			Handler:    _DaemonService_SetStartAtBoot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "husi/v1/daemon.proto",
}
